### ISSUE TITLE
Generating *.d.ts files for type checking in TypeScript

### ISSUE THREAD

**Issue by aiosifelis** [teambit/bit#1011]
As per our discussion on Gitter, I'm opening this issue in order to include type checking for TypeScript.

![image](https://user-images.githubusercontent.com/36890905/40562516-47f8bfb8-602f-11e8-9202-81c03573d417.png)

**Comment by tim-smart** [comment]
👍 +1

**Comment by itaymendel** [comment]
@tomlandau @GiladShoham - we've talked about this one. Let's try and implement it within the TS compiler itself. Bit should handle it as part of the links it creates.

**Comment by stonecold123** [comment]
Looking forward to this feature

**Comment by qballer** [comment]
Our current env implementation has the typescript config hard coded in the compiler. It also uses a low level API of the compiler for transpilation. This API misses the notion of `ts.program` and doesn't use the Typescript language service API. This prevents us, for now, to generate a d.ts files for the compiled modules. 

A possible workaround to this issue is to generate the d.ts file in the component author environment using typescript directly. Track the generated d.ts as a part of the component. We are working on a new set of envs in order to resolve both type generation and hard coded configuration.  You can get more information in #1156.

In case the hard coded configuration might not work for you, you can fork the current TS compiler and change the configuration as needed. The current compiler options are [these](https://github.com/teambit/bit.envs/blob/master/src/compilers/typescript/index.js#L25).

**Comment by PatrickGeyer** [comment]
Hi guys, any update here?

**Comment by williamluke4** [comment]
Has there been any movement on this?

**Comment by williamluke4** [comment]
I believe this is the right place https://github.com/teambit/bit.envs/issues/8

**Comment by GiladShoham** [comment]
@williamluke4 You are right.
For everyone coming to this thread later, please follow progress on:

The current status of this today is:
There is a compiler version which emits the d.ts files, that can be found [here](https://bit.dev/bit/envs-dev/compilers/typescript)
It's based on something created by @WassimBenzarti (thanks for this)
It's not production ready yet, mainly because of performance issues.
I'm working in order to solve the performance issue.
It will take some time since it requires some new APIs by bit core.

**Comment by itaymendel** [comment]
Resolved in the latest version on the ts compiler
