### ISSUE TITLE
CI failing on AppVeyor

### ISSUE THREAD

**Issue by DanielRuf** [teambit/bit#1113]
Currently the tests fail on AppVeyor (Windows).
Can I help here with fixing this?

**Comment by GiladShoham** [comment]
Hi @DanielRuf 
That will be great!

There are few issues with the AppVeyor:

1. Execution time - AppVeyor is limited to 90min - there is no way to increase it (even if you pay). (I know their support team can increase it because they increased it from 60 to 90 minutes).
Anyway, the better way to solve this issue is to enable [parallel-testing](https://www.appveyor.com/docs/parallel-testing/).
This doc about parallel-testing talking only about .NET code so it's irrelevant, but I know there is a way to do it using the matrix features as described here - [build-matrix](https://www.appveyor.com/docs/build-configuration/#build-matrix) and [testing-under-multiple-versions](https://www.appveyor.com/docs/lang/nodejs-iojs/#testing-under-multiple-versions-of-nodejs-or-iojs)
The first step will be to break it to few different jobs which will run in sequence. Once this will work as expected (means running all the tests from the different jobs) we of course end with the same problem with the time limit, but then we can pay to AppVeyor which will make them run in parallel and solve this issue.
2. Tests which fails due to differences in paths - most of the fail tests in windows are usually a result of differences in the paths separator (a.k.a / in Linux and \\ in windows), this usually fixed by updating the paths in the test cases to support both by using path.join for example. 
There are also cases where we use path.join and got the correct paths in windows, but we store the data in our models always in Linux format so it's also create failing tests (in such cases we need to make sure the test always return Linux path).
3. Some of the tests fail because of bugs in windows, those cases need to be checked one by one and fixed.

The most valuable contribution for us is about the first point (since the second and third we usually can fix pretty easily), but you are welcome to address those as well.

We also open to a suggestion about using different service rather than AppVeyor which support windows.

We really appreciate your help.

**Comment by GiladShoham** [comment]
Update:
Number 2 and 3 are basically solved.
Still, need to implement the parallel mechanism to make sure everything is running (there might be more failing tests once all the tests will actually run)

**Comment by qballer** [comment]
Issue was resolved for now, tests pass on appveyor and everywhere please refer to PR #1127 for more information.
