### ISSUE TITLE
 Vue packages version mismatch

### ISSUE THREAD

**Issue by ghaiat** [teambit/bit#1139]
## Expected Behavior
be able to do `bit init`

## Actual Behavior
The command fails with the following errors: 
``` Failed loading the driver for javascript. Got an error from the driver: Error:

Vue packages version mismatch:

- vue@2.4.4
- vue-template-compiler@2.5.16

This may cause things to work incorrectly. Make sure to use the same version for both.
If you are using vue-loader@>=10.0, simply update vue-template-compiler.
If you are using vue-loader@<10.0 or vueify, re-installing vue-loader/vueify should bump vue-template-compiler to the latest. 
```

I m not using Vue at all in my project. any idea?

## Specifications

  - Bit version: 13.0.3
  - Node version: 8.9.0
  - npm / yarn version: 6.2.0
  - Platform: OSX

**Comment by ghaiat** [comment]
`bit cc` solved it

**Comment by fsblemos** [comment]
Same here yet:

```
Failed loading the driver for javascript. Got an error from the driver: Error: 

Vue packages version mismatch:

- vue@2.5.16
- vue-template-compiler@2.5.17

This may cause things to work incorrectly. Make sure to use the same version for both.
If you are using vue-loader@>=10.0, simply update vue-template-compiler.
If you are using vue-loader@<10.0 or vueify, re-installing vue-loader/vueify should bump vue-template-compiler to the latest.
```

`bit cc` didn't solve

**Comment by fsblemos** [comment]
@ghaiat can you reopen the issue?

**Comment by GiladShoham** [comment]
@fsblemos 
I was able to reproduce the issue.
It seems that the reason for this conflict is that you installed bit-bin locally instead of globally.
Can you try to remove the local install and reinstall bit-bin globally?
I'm reopening the issue and waiting for your response.

**Comment by fsblemos** [comment]
Thanks @GiladShoham!
`bit-bin` was global already, but based on your comment I remove the global `vue` and `bit init` worked!
After running `bit init`, I installed `vue` globally again and still working.

**Comment by MarcCoet** [comment]
Hey, just want to report in case it can help someone.
I ran into this issue as well.
I removed the global packages vue-cli and quasar-cli using yarn but I don't know if it solved the initial issue because after removing bit-bin and reinstalling it using yarn it was failing with a yarn error:
`ENOENT: no such file or directory, open '/home/.../.config/yarn/global/node_modules/brace-expansion/node_modules/balanced-match/index.js'`
I removed bit-bin again using yarn then reinstalled it with npm and now it works.
Happy coding folks

### Specifications
Bit version: 13.0.4
Node version: 11.5.0
yarn version: 1.12.3
npm version: 6.5.0
Platform: Arch Linux

**Comment by thanosasimo** [comment]
Re-importing vue compiler solved the mismatch for me.
``
$bit import bit.envs/bundlers/vue -c
``
