### ISSUE TITLE
Can't recognise .jsx file while bundling 

### ISSUE THREAD

**Issue by qballer** [teambit/bit#1148]
When trying to bundle jsx file using webpack bit doesn't recognise .jsx file. 

## Expected Behavior
Component is bundled without errors. 

## Actual Behavior
```ModuleNotFoundError: Module not found: Error: Can't resolve...```

## Steps to Reproduce the Problem

this is the component structure which reproduces the bug.
``` js
// main.js 
import Component from './my-component';
export default Component;
```
my-component corresponds to ```my-component.jsx```

## Specifications
  - Bit version: 13.0.3
  - Node version: 10.6.0 (reproduces on node 8.11.3 as well)
  - npm / yarn version: npm 6.1.0
  - Platform: mac
  - Bit compiler (include version): webpack 0.0.13
  - Bit tester (include version): N/A

**Comment by GiladShoham** [comment]
@qballer 
Thanks for reporting this.
My guess is that this is related to the file extension.
In webpack sometime you define the resolveExtension which tell webpack to search files with those extensions when there is no extensions.
Bit doesn't know to do this but we might add this feature.
Anyway, we will check this and let you know.

**Comment by davidfirst** [comment]
@qballer , do you think it's still an issue or we can close it?

**Comment by qballer** [comment]
I have no idea. We need to test it again and see.

**Comment by itaymendel** [comment]
The entire component compilation process is going to major changes. We are rebuilding them using the new Capsule infrastructure that enables compilers to run undisturbed by Bit.

Given that there are no STR in this issue, and that the Bit maintained Webpack bundler has been updated since - I'm closing this issue. If anyone is experiencing this, please send here a comment, and I'll reopen.
