### ISSUE TITLE
vuejs components

### ISSUE THREAD

**Issue by iboldurev** [teambit/bit#1152]
Please add support vuejs components, at the moment I see there is support for compilation, but here's a preview not documentation for vuejs

**Comment by itaymendel** [comment]
Hi @iboldurev 

We are working to improve the underline infrastructure for the entire rendering feature. Once it is released, we will be able to support additional renderers in the system.

This is a very requested feature, and as such, a top priority for the [bitsrc.io](https://bitsrc.io) component hosting platform.

Even though this is not a Bit feature request, I'm keeping this issue open to having a place to update on the process of the Vue renderer.

**Comment by ljelewis** [comment]
Bump. 

Any news on when this improvement will be available? The feature of Bit that makes it really stand out from using native npm is interactive previews, but we use Vue components here.

**Comment by jasir** [comment]
any news here? just started with bit, it is awesome. vue is also awesome...

**Comment by GiladShoham** [comment]
@jasir @alexandre1985 @siem684 @lukenofurther @iboldurev @agrantham 
Just a quick update - We are working on Vue support for the playground, and we already have it working on our test env and we are testing it at the moment. It should be deployed pretty soon (don't have an exact eta yet)
I'll update once it released of course.

**Comment by bmillspaugh** [comment]
Checking in.  It has been 10 months since you mentioned "This is a very requested feature, and as such, a top priority..." but it is still not working.  We can't wait forever...do you have an ETA?

**Comment by itaymendel** [comment]
Hi @bmillspaugh 

It indeed a very requested feature and we worked very hard in the past months to support it.

The reason it is still delayed is that initially, we implemented the isolated component environment based on Yarn PnP. We had to ensure that the rendering is as fast as possible.
Unfortunately, we found that PNP is not compatible with many tools and frameworks (such as Vue and Angular). So we had to start from scratch.
Since we were not able to find any compatible solution that we can depend on (sadly npm's tink is very far away) - we had to implement our tool. One that will be able to fetch and install dependencies fast and reliable, as well as fully compatible with the current node eco-system.
This entire cycle took us a long time. More than anticipated.

The good news is that we just deployed the new architecture to production yesterday. Now the playground uses the new infrastructure.
There are still some leftover tasks to do to support rendering of Vue. For example, creating a meta-project to act as a boilerplate, connecting it to the screenshot workflow, UI upgrades, syntax highlight support, etc.

While there is no ETA for the availability of it, I would consider these as minor features. However, we would not release it before we ensure the new workflow is fully working.
You can create vue components and use them in different projects. You can find the compiler [here](https://bit.dev/bit/envs/bundlers/vue).

**Comment by xrr2016** [comment]
> Hi @bmillspaugh
> 
> It indeed a very requested feature and we worked very hard in the past months to support it.
> 
> The reason it is still delayed is that initially, we implemented the isolated component environment based on Yarn PnP. We had to ensure that the rendering is as fast as possible.
> Unfortunately, we found that PNP is not compatible with many tools and frameworks (such as Vue and Angular). So we had to start from scratch.
> Since we were not able to find any compatible solution that we can depend on (sadly npm's tink is very far away) - we had to implement our tool. One that will be able to fetch and install dependencies fast and reliable, as well as fully compatible with the current node eco-system.
> This entire cycle took us a long time. More than anticipated.
> 
> The good news is that we just deployed the new architecture to production yesterday. Now the playground uses the new infrastructure.
> There are still some leftover tasks to do to support rendering of Vue. For example, creating a meta-project to act as a boilerplate, connecting it to the screenshot workflow, UI upgrades, syntax highlight support, etc.
> 
> While there is no ETA for the availability of it, I would consider these as minor features. However, we would not release it before we ensure the new workflow is fully working.
> You can create vue components and use them in different projects. You can find the compiler [here](https://bit.dev/bit/envs/bundlers/vue).

Hi, bro, any news now?

**Comment by itaymendel** [comment]
@xrr2016 we're testing it in our staging environment :)
There are still some rough edges that need some polishing. But we're getting super close.

![Screen Shot 2019-06-10 at 8 52 57 PM](https://user-images.githubusercontent.com/4623056/59251130-ba655500-8c31-11e9-89c1-c72557737530.png)

**Comment by xrr2016** [comment]
> @xrr2016 we're testing it in our staging environment :)
> There are still some rough edges that need some polishing. But we're getting super close.
> 
> ![Screen Shot 2019-06-10 at 8 52 57 PM](https://user-images.githubusercontent.com/4623056/59251130-ba655500-8c31-11e9-89c1-c72557737530.png)

That sounds great, thank a lot.

**Comment by itaymendel** [comment]
**Update**

A few days ago we've added support for Vue rendering.
We are working now on improve the Vue compiler to support more usecases and setups.

**Comment by GiladShoham** [comment]
The new version of the Vue compiler has been released (2.6.10), you can found it here - https://bit.dev/bit/envs/bundlers/vue
