### ISSUE TITLE
Cant import components with same name but different scope 

### ISSUE THREAD

**Issue by amitgilad3** [teambit/bit#1190]
## Expected Behavior
when i import two components with the same name but different scopes i get the following message:
**your id bitId-1 is duplicated with bitId-2**

i configured componentsDefaultDirectory in my bit.json key to be src/{scope}/{name} so that each component would be set in a different directory but this did not help.

## Specifications

  - Bit version: 13.0.4
  - Node version: v7.10.0
  - npm / yarn version: 4.2.0
  - Platform: osx

**Comment by GiladShoham** [comment]
@amitgilad3 Thanks for reporting this,
We are aware of this issue.
It's on our roadmap to solve this issue.
I'll update this issue once it's resolved.

**Comment by bmillspaugh** [comment]
I have the same issue.  I thought that the namespace would make the component names unique but it just errors.  I tried "bit add components/*/*.vue --namespace {PARENT}" but I get the error "unable to add 10 components with the same ID: {parent}/nav-bar" even though all of the namespace/component names are unique (i.e. module1/nav-bar, module2/nav-bar, module3/nav-bar, etc.).  What is the point of the namespace if not to create unique areas of separation?  I would consider this a bug (not a feature request) because you have a namespace attribute which should provide separation of components, but it doesn't work, and the error is wrong because the name {parent}/nav-bar is not the same when you replace {parent}.  This bug was reported 9 months ago...when will it be fixed?

**Comment by itaymendel** [comment]
Hi @bmillspaugh , I think that both issues are unrelated.
In @amitgilad3 's case, he had two components with the same name but on different collections, and he tried to import them to the same project.

I think that your case is different. It seems that your issue happens when you use `bit add` to track components.
For some reason Bit was unable to set a unique name for a component, even though you use `namespace` to distinguish between component names. I don't fully understand your project file structure to help you with figuring out the correct syntax to use `bit add` with.
Can you please open another issue and demo the file structure and how you want to have them named?

**Comment by GiladShoham** [comment]
@bmillspaugh Your issue with the naming collision is because of the namespace flag doesn't support {PARENT}. so eventually some of your components get the same id.
Please open a new issue about supporting {PARENT} in `namespace` flag.

**Comment by bmillspaugh** [comment]
Thanks @itaymendel & @GiladShoham!  I tried it without the {PARENT} variable and it worked great, so that is the bug and it is not the same as what @amitgilad3 reported.  Thanks for the help!  Much appreciated.

**Comment by itaymendel** [comment]
resolved for v15

We'll start rolling out v15 of Bit this week, please reach out to me privately on the [public slack community](https://join.slack.com/t/bit-dev-community/shared_invite/zt-9egg85xv-trr_QBkWr1XcVgtrgCvtfQ) for a sneak peek and getting early access to it.
