### ISSUE TITLE
Bit components to have comments or some way to give feedback

### ISSUE THREAD

**Issue by jcguarinpenaranda** [teambit/bit#1207]
## Expected Behavior
I am trying to edit the typescript compiler (https://bitsrc.io/bit/envs/compilers/typescript/code) to add the possibility to emit declaration files, but there's no way to contact the developer, nor a way to submit an issue to ask request the author to make the change or get some advice on merging back to the component.

Getting more in depth with the declaration files, having them emitted would be very useful because there are editors like VSCode that already now how to work with those .d.ts files to consume the published modules.

## Actual Behavior
There is no way to contact the developer or to comment or submit an issue into a module (at least I have not found one)

**Comment by itaymendel** [comment]
hi @jcguarinpenaranda , this feature is in the works, and not yet available in Bit.
Until this is released we keep a Git repo for each collection, in order to allow collaboration.

Here's the repo that you can use to collaborate with the maintainers of the envs.
https://github.com/teambit/bit.envs

By the way - we are working on publishing new compilers/testers that will include support for newer APIs that Bit support (for example passing compiler configuration).
If you want to browse the new ones, they are here:
https://github.com/teambit/bit-envs


I'm closing the issue, as environments are managed in their own repositories.
