### ISSUE TITLE
Linking components

### ISSUE THREAD

**Issue by ThomasKientz** [teambit/bit#1228]
I don't get how to use the link command.

I have successfully tracked 2 components, lets say A and B.

Components A is importing components B with an absolute link like :

`import padLeft from '@bit/bit.examples.string.left-pad';`

I have run `bit link`

But when I make local changes to B, A is not considering them.

Am I missing something ?

**Comment by GiladShoham** [comment]
have you imported both A and B? if not, try to import both.

**Comment by ThomasKientz** [comment]
@GiladShoham A and B are local components that I just tracked and exported. And I am trying to modify B without changing the import in A.

So A and B are not imported, at least not using `bit import`, because they are the original components that I originally tracked.

**Comment by GiladShoham** [comment]
@ThomasKientz 
In such case, the @bit/b under the node_modules should be a symlink to the folder where b is defined.
Can you check if it's a symlink?
Maybe you are running on old windows without symlinks support (in such case the node_modules/@bit/b will be a copy of the b files instead of a symlink which can explain the state).
Also, if there is you defined a compiler, you should probably build B before building a, so you have to run `bit build` (which will build everything) or `bit build b` before building A. (that should happen automatically when building A but it might be a bug in this process, I'll check this).

**Comment by ThomasKientz** [comment]
I am not able to reproduce this issue as a new issue is happening : https://github.com/teambit/bit/issues/1232

**Comment by davidfirst** [comment]
Actually, in this case of authored components, `bit link` doesn't create symlink but generate link files.
@ThomasKientz , the end result of `bit link` as described in the last comment is as expected. Bit creates these index.js files to point to the component location. (Symlinks are created in a different scenario).
I'm wondering why in your case index.js is never read. 
Is there any chance you could provide some steps to reproduce the issue? (if you prefer, you can also zip and email me one of the components to david@bitsrc.io).

**Comment by dgoerdes** [comment]
Are there any news on this?
I am currently having the same issue as @ThomasKientz described above.

**bit.json:**
```json
{
  "env": {
    "tester": "bit.envs/testers/mocha@0.0.14"
  },
  "dependencies": {},
  "packageManager": "yarn",
  "useWorkspaces": true,
  "componentsDefaultDirectory": "bit/components/{namespace}/{name}",
  "dist": {
    "target": "bit/dist"
  }
}
```

**Steps to reproduce:**

1. `bit add packages/package-A/`
2. `bit tag packages/package-A 0.0.1`
3. `bit export org.scope`
4. `cd packages/package-B`
5. `yarn add @bit.org.scope.packages.package-A`
5. `bit link`

The output of `bit link` looks fine and all the files and paths are correct.
But any change to package-A is not reflected when rerunning package-B.

**Comment by davidfirst** [comment]
@dgoerdes , in your case, since you installed packageA as a package inside packageB, there is no link between this package and the Bit component.

What needs to be done in your case is only steps 1-3. As soon as you export the component, Bit creates a link inside node_modules with the name of the package, so you can require packageA from packageB immediately without installing it directly inside packageB.

Please re-open if this is still an issue.
