### ISSUE TITLE
JSDOCs don't support optional and default values for properties

### ISSUE THREAD

**Issue by danawoodman** [teambit/bit#1246]
## Expected Behavior

JSDOC syntax for properties works according to JSDOC spec

## Actual Behavior

The following JSDOCs:

![](https://cl.ly/d02ac6020fe3/Screen%20Shot%202018-10-02%20at%208.54.28%20PM.png)

Produce the following docs on bitsrc.io:

![](https://cl.ly/a023bb03a9a5/Screen%20Shot%202018-10-02%20at%208.55.39%20PM.png)

## Specifications

  - Bit version: 13.0.4
  - Node version: 10.11.0
  - npm / yarn version: 6.4.1
  - Platform: OSX
  - Bit compiler (include version): React (0.0.14)
  - Bit tester (include version):

**Comment by davidfirst** [comment]
Bit uses Doctrine to parse the JSDocs. Turned out that in order to support optional parameter, a flag `sloppy=true` needs to be added to Doctrine, which I have done in the PR attached above. 

@itaymendel , before merging, a decision needs to be made as to how to show these types.
So far we have followed Doctrine convention. Doctrine indicates the optional parameter by adding `=` suffix. For instance, `string` becomes `string=`. When there is a default value, the type is the same but it adds a new property "default".

Here are two examples from the unit tests I added:
```
* @param {string} [optionalParameter] my optional parameter
* @param {string} [optionalParameterWithDefaultValue=value] my optional parameter with default value
```
Doctrine parses them as following:
```
{
                    "description": "my optional parameter",
                    "type": "string=",
                    "name": "optionalParameter"
                },
                {
                    "description": "my optional parameter with default value",
                    "type": "string=",
                    "name": "optionalParameterWithDefaultValue",
                    "default": "value"
                }
```
 The questions are:
1) are we good with showing optional parameter as `string=`, maybe we prefer the more common syntax `string?`.
2) where do we show default value when a parameter has a default value?

**Comment by davidfirst** [comment]
Just to keep this issue up to date. 
Regarding the questions above:
1) the optional parameters are going to have the `?` syntax. (e.g. `string?`).
2) the default value is saved under "default" property.

The PR has been merged into master.

**Comment by danawoodman** [comment]
Is `?` more common? JSDocs says it is `=`, at least [according to this](http://usejsdoc.org/tags-param.html#optional-parameters-and-default-values)
