### ISSUE TITLE
Bit import bit import bit.movie-app/components/hero-button is wrong directories hierarchy

### ISSUE THREAD

**Issue by mrkhanakia** [teambit/bit#1308]
## Expected Behavior
file:./components/components/hero-button

## Actual Behavior
file:./components/components/hero-button/components/hero-button

## Steps to Reproduce the Problem

  1. bit import bit.movie-app/components/hero-button

Screen shot of Root Directory 
![download](https://user-images.githubusercontent.com/2174170/47916971-0565ff80-dece-11e8-8da4-1763db29ba2e.png)

## Specifications

  - Bit version: 13.0.4
  - Node version: v10.11.0
  - npm / yarn version: 6.4.1
  - Platform: Mac OS
  - Bit compiler (include version):
  - Bit tester (include version):

**Comment by GiladShoham** [comment]
Hi @mrkhanakia , Thanks for reporting this.

The behavior you describe is, in fact, the expected. I'll try to explain why:

1. The first `components` folder is the `defaultComponentsDirectory`, as configured in the `bit.json` file (`components` is the default value).
2. Secondly, `components/hero-button` folders are the dynamic parts of the component directory (the namespace and name of the component). This translate to the root folder for each component.
3. The next `components/hero-button` is necessary to make the relative import to `style.css` work (there you go - https://github.com/teambit/movie-app/blob/master/src/components/hero-button/HeroButton.js#L5).
To make the relative require statement work, Bit need to nest `HeroButton.js` file two folders deep. So when Node resolves the relative require, it will find the file.
BIt copies the names of these directories as they were in the original project the component exported from. This is so since those are probably the most reasonable names.

If `style.css` were next to the js file, the resulted file structure would be as you described.
