### ISSUE TITLE
Creates node_modules on every export

### ISSUE THREAD

**Issue by ChuksFestus** [teambit/bit#1322]
I noticed on every update bit creates a node_module folder within my component, like say i update button.js and run `bit export component-name` It always download a node_module folder within the component I'm working on

**Comment by GiladShoham** [comment]
@ChuksFestus
It's Not a Bug; it's a Feature :)

When exporting a component, Bit generates a symlink in the `node_modules` directory to the exported component's directory. It is not downloading process, just locally creating a folder (symlink).

Bit does this to allow you to allow you to require the component using an absolute path, rather than relative require statement from anywhere in your project. 
For example:

```js
import myComp from @bit/[user].[scope].[namespace].[name]
```

You can read more about it [here](https://docs.bitsrc.io/docs/importing-components.html#link-components) (The doc refer to importing component, but it's the same for exporting).

I hope this clarifies things.
