### ISSUE TITLE
Add ability to support bitignore file

### ISSUE THREAD

**Issue by michaelryancaputo** [teambit/bit#1333]
## Expected Behavior
I would like to be able to create a `.bitignore` file in my project's folder that will automatically ignore files when tracking components - much like a `.gitignore` would do.

## Actual Behavior
Currently I have to specify this parameter when I track a new component: https://docs.bitsrc.io/docs/isolating-and-tracking-components.html#ignoring-files-when-tracking-components

**Comment by michaelryancaputo** [comment]
Yeah,
so I use bit in conjunction with Storybook to build components locally. We've noticed that if we don't manually export bit components (containing a story file) while excluding those files in the same folder, it also packages up storybook.

So i'd like to do a `.bitignore` containing `*.story.js` to exclude those files.

**Comment by Abramovick** [comment]
what's the status for this? I'm also interested in this feature.
@michaelryancaputo how are you currently ignore your story files?

**Comment by GiladShoham** [comment]
@michaelryancaputo @Abramovick Until this feature will be available you can use the `--exclude` flag during the `bit add` command.
Read more here [tracking-a-component-with-just-the-right-files](https://docs.bitsrc.io/docs/cli-add.html#tracking-a-component-with-just-the-right-files)

**Comment by michaelryancaputo** [comment]
Yup, this is how i'm doing, and also using `.story` files in a different folder. Not the optimal workflow, but it works!

**Comment by KoshiroKun** [comment]
I'm interested in this feature too. I have some `README.md` in each component for Storybook that I don't need on bit and I want to ignore them.

@michaelryancaputo how you ignore the story files? I perform `bit add componentId --exclude *.md --override true` this works in `.bitmap` because I saw the `.md` disappear but when I do `bit status` the md file returns. How you did it?

**Comment by GiladShoham** [comment]
@KoshiroKun The reason it's back on bit status is probably since you track a whole folder. when you track a folder, during bit status, bit checks if there are new files and add them. 
You can check it by looking in the bitmap for the component, and see if there is trackDir / rootDir property for the component.
You can workaround it by tracking the files rather than tracking the dir. (this, of course, will come with a cost that you will have to manually `bit add` new files for the component.
The real solution for this is described on this issue: https://github.com/teambit/bit/issues/1611
track this issue to get updates about it. 
I don't have an exact ETA when we will implement it.

**Comment by patrickcze** [comment]
Would also like to see this implemented :) It would prevent the need to --exclude story files for our team as well.

**Comment by yhjor** [comment]
+1 for this feature

**Comment by davidfirst** [comment]
@GiladShoham , we should rethink about this with Harmony. 
The `--exclude` flag of `bit add` is not allowed anymore because only directories are tracked and if you track a directory and constantly need to exclude files from there, you'll have to have in the `ComponentMap` the exclude paths. Since we aim to remove paths completely from .bitmap, a better solution would be `.bitignore` file.

**Comment by GiladShoham** [comment]
@davidfirst i totally understand the need.
I'm not sure if we should go with bitignore file or with config for some extension to achieve it.

**Comment by itaymendel** [comment]
not supporting excluding files from components.
for v15, a component is a complete directory and all it's included files.

We'll start rolling out v15 of Bit this week, please reach out to me privately on the [public slack community](https://join.slack.com/t/bit-dev-community/shared_invite/zt-9egg85xv-trr_QBkWr1XcVgtrgCvtfQ) for a sneak peek and getting early access to it.

**Comment by hyoretsu** [comment]
I found this looking to exclude directories from being adopted by Bit. I'm migrating to it and I tried putting my old folder in `tmp`, but `bit install` was failing in its pre-commit hook.
