### ISSUE TITLE
Component with dependencies need auth token via .npmrc file

### ISSUE THREAD

**Issue by jeremy-habit** [teambit/bit#1344]
Hello, 

I exported a component to my scope and this last one use some icons from fontawesome pro license. This package need auth token available in .nprmc file. 

If I don't export the .npmrc file with the component, it's impossible to import it correctly. I mean that all files are mounted with the good folder's architecture but ...npm install fail and it's impossible to update the component. If I update the main file for example, bit will not track the component as a modified component.

I didn't find an other solution that export .npmrc file with the component, is there an other one ?

Thank you

## Specifications

  - Bit version: 13.04
  - Node version: v11
  - npm / yarn version: 6.4.1
  - Platform: Mac OS 10.14.1
  - Bit compiler (include version): custom compiler based on react compiler from bit envs
  - Bit tester (include version): jest from bit envs

**Comment by GiladShoham** [comment]
Hi @jeremy-habit 
You can add a `.npmrc` file to a component. When installing the component that config file is fetched with the component. However, npm (or yarn) does not support reading `.npmrc` files that are downloaded with packages. This is a limitation forced by npm (and yarn). Bit can't mitigate this issue.
At the moment, bitsrc's CI does not support downloading packages from repositories other than the public npm registry.

The best way to resolve it is to ensure that developers that consume these packages has their `.npmrc` file configured.

**Comment by fabgallo** [comment]
Hey @GiladShoham 
I am almost exactly in the same predicament as @jeremy-habit with FontAwesome Pro. Our issues, though, it's with the Bit playground, as on our project(s) we have the necessary `.npmrc` files and the components work correctly.
On the playground, though, exactly because what you said above, we are unable to consume packages from private registries.
The service we create to provide our subset of icons (a mix of FontAwesome Pro and custom SVGs) fails with the very ambiguous "You cannot require a package that is not declared in your dependencies" error, like someone else described in https://github.com/teambit/bit/issues/1482.
Therefore, our React component using the icon library fails as well (same error) and that waterfalls on all other components using the icon component. When using just the free icons from FontAwesom, everything works. For now we are avoiding the issue by creating another private Bit collection and hosting the icons there directly, but we would like to avoid that.

Do you guys have in the roadmap to add the possibility to upload `.npmrc` files (or other way to provide the auth token) in the playground itself and allow Bit's CI to use it?

**Comment by GiladShoham** [comment]
@fabgallo Yes, we do have it on our roadmap but I don't have a time frame at the moment.

**Comment by itaymendel** [comment]
resolved as part of v15

We'll start rolling out v15 of Bit this week, please reach out to me privately on the [public slack community](https://join.slack.com/t/bit-dev-community/shared_invite/zt-9egg85xv-trr_QBkWr1XcVgtrgCvtfQ) for a sneak peek and getting early access to it.
