### ISSUE TITLE
Component export succeeds and --eject fails

### ISSUE THREAD

**Issue by PatrickGeyer** [teambit/bit#1345]
## Expected Behavior
The component exports to bit and then removes local files and adds package as npm dependency.

## Actual Behavior
The component exports correctly, however the following error message appears.

`The components evolut.shared/shared/model@0.0.26 were exported successfully.
      However, the eject operation has failed due to an error: failed running npm install at /Users/mac/Desktop/link/frontend
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @bit/evolut.shared.shared.model@0.0.26
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget`

The last version of the package I can install from npm is 0.0.22

**Comment by GiladShoham** [comment]
@PatrickGeyer Thanks for reporting this.
I will take a look at this and post an update.

**Comment by GiladShoham** [comment]
@PatrickGeyer 
After looking into the issue and the component, I trust that the issue is a resolve of a component using an absolute import to itself via `@bit` bindings.
For example:
```js
// From components/model/module/post/model/model.ts
import { Image } from '@bit/evolut.shared.shared.model';
```

This is a bug in Bit. I'm keeping the issue open until I resolve the issue.

As a workaround, change all components that require themselves using `@bit` bindings to a relative path.

**Comment by davidfirst** [comment]
The issue has been fixed with the commit above and an e2e-test was added.
It'll be part of the next release. Hopefully soon.
