### ISSUE TITLE
Keep imported files after bit remove

### ISSUE THREAD

**Issue by rshirts** [teambit/bit#1361]
## Expected Behavior
The ability to remove an imported component from tracking without removing the source files.

## Actual Behavior
When you use bit remove with the --delete-files [false] it still deletes the files.

## Steps to Reproduce the Problem

1. bit Import <component>
2. bit remove <classname><name> ---delete-files false

## Specifications

  - Bit version: 13.0.4
  - Node version: 8.10.0
  - npm / yarn version: 6.5.0
  - Platform: linux/mint
  - Bit compiler (include version): react@0.0.14
  - Bit tester (include version): n/a

**Comment by GiladShoham** [comment]
@rshirts thanks for reporting this.
We will solve this issue

**Comment by davidfirst** [comment]
It's not resolved yet, but just to clarify, the `--delete-files` flag is relevant only for the components you as the author created. For imported component, the flag does nothing. 
I updated the CLI help to indicate this.

**Comment by davidfirst** [comment]
@GiladShoham , @itaymendel , 
Not sure about the option of adding a new flag `--no-delete-files` it'll be very confusing because we have `--delete-files`. 
The problem is that for author components it makes sense to keep the files but for imported components, it makes sense to remove the files.

I'm thinking maybe we could re-use the `bit untrack` command for this purpose. 
In this case, the user wants to untrack the imported components but keep the source files. The objects are not important, they can be kept or deleted. 
I know that currently is only for new components, but we can remove this limitation and enable un-tracking any component.

**Comment by itaymendel** [comment]
I'm not sure `untrack` should handle such a case.
As what would happen when I run `bit untrack --all`? I'll lose all the imported components?
We'll need to think deeper about the duality of `remove`, so we can have a proper flow that does not cause a duality or other edge cases.
