### ISSUE TITLE
Comparison with Bower

### ISSUE THREAD

**Issue by niutech** [teambit/bit#1362]
Sorry for asking here, but I did not find any Q&A section on your page.

How is Bit different from good old Bower? Both allow developers to easily create and import components. And both Bit and Bower even have registries of public components (packages).

Could you add this info to the README?

**Comment by qballer** [comment]
Package managers control a "binary", meaning compiled code, or otherwise ready code  for consumption.  npm, yarn, pnpm etc manage the binary product of source code.  Bit in essence manages the source and how to consume that source within other code bases. So while these share similar properties these are not the same.

Why use bit? 
1. its easier to publish a bit component.
2. You can update a component from a project which consumes it (not waiting for PR's in the author env).
3. You have access to the component tooling (compiler/tester/linter/whatever)
4. You get component dependencies (similar to package managers)
5. components tend to be smaller from packages
6. You can play with components before installing them and in the future discover them on bitsrc.io

**Comment by niutech** [comment]
Thanks for the explanation, but the first argument is not necessarily true. Bower components contain both source files as well as minified files.

**Comment by qballer** [comment]
Closing the issue for now, let me know if you need anything else.
