### ISSUE TITLE
Create a component for each file in each sub-directory

### ISSUE THREAD

**Issue by namieluss** [teambit/bit#1406]
## Expected Behavior
This should create a component for each of the files in src and in its sub-directories, according to the documentation.

## Actual Behavior
error: one or more of the added components does not contain a main file.
please either use --id to group all added files as one component or use our DSL to define the main file dynamically.

## Steps to Reproduce the Problem
  1. Create a file structure
![create a component for each file in each sub-directory](https://user-images.githubusercontent.com/8718504/51907728-a6e3eb00-2402-11e9-864f-12f85babba0d.png)

  2. bit add src/**/*

## Specifications
  - Bit version: 13.0.4
  - Node version: v9.9.0
  - npm version: 6.5.0
  - Platform: Macbook Pro

**Comment by davidfirst** [comment]
@namieluss , thanks for reporting the bug.
In this case, the command passes the following paths:
```
'src/fourth.js',
'src/one',
'src/one/first.js',
'src/one/second.js',
'src/two',
'src/two/third.js'
```
Because `src/one` is a directory that has two files, it doesn't know which one is the main file.
Bit should probably identify that all files of this directory are passed and then ignore the directory.
For now, as a workaround, you can use `bit add src/*/*` to add all the files in subdirectories of `src`, then, add the files that are directly on `src`.

I'll update once this bug is fixed.
