### ISSUE TITLE
More descriptive authentication errors

### ISSUE THREAD

**Issue by itaymendel** [teambit/bit#1415]
## Expected Behavior

When my remote command fails due to an authentication issue, have a more descriptive error presented, instead of looking into the logs.

## Actual Behavior

Bit fails to authenticate, prompts username/password request, and fails again. The actual error is found in the logs.

## Examples

While there are few examples of it, and different flow Bit tries to do when authenticating, this might be somewhat problematic... As Bit has a fallback mechanism between different ways it tries to authenticate.

* SSH key defined in `bit config`.
* SSH key fetches from ssh-agent.
* `user.token` not defined...
* ssh key has passphrase and Bit can't handle it at the moment.
* an actual authentication issue with the remote scope.

each issue needs to be asserted in an error message.
also - consider add `--verbose` option to show each of the fallbacks.

**Comment by GiladShoham** [comment]
Thanks, we will improve our logs.
@davidfirst can we improve our ssh logs?

**Comment by davidfirst** [comment]
To address this issue, two PRs were opened.
1. https://github.com/teambit/bit/pull/1481 (merged), which enabled printing a specific chunk of the log to the console. In this case, to print only log messages of the ssh module, prefix the command with `BIT_LOG=ssh`.

2. https://github.com/teambit/bit/pull/1480 (will be merged), which changes all the previous obscure messages to be descriptive and meaningful. An example of a case where all strategies were failed:

`BIT_LOG=ssh bit import david.utils/is-string`
> ssh trying to connect using token
> ssh, token exists but failed to authenticate. either, the token is invalid or invoked
> ssh failed connecting with token, trying with ssh-agent authentication
> ssh there is no ssh-agent socket or it has been disabled
> ssh failed connecting with ssh-agent, trying with ssh-key authentication
> ssh, reading ssh key at /Users/davidfirst/.ssh/id_rsa
> ssh failed connecting with ssh-key authentication, trying with user/password prompt
> username:
> password:
> ssh, failed connecting using the provided user and password
> ssh all connection strategies have been failed!
> authentication failed. see troubleshooting at https://docs.bitsrc.io/docs/authentication-issues.html

The reason of printing the log this way and not by adding `--verbose` is because the ssh connection may happen in different commands, some have 'verbose' flag, some not and the meaning is not the same.

As to the five points in the 'Examples' section, I believe are all implemented, except #4 "ssh key has passphrase and Bit can't handle it at the moment." it's problematic because we don't get this info from SSH2 lib. It just shows that the authentication failed without a reference to the passphrase.
