### ISSUE TITLE
Improve sync between .bitmap file and local component store

### ISSUE THREAD

**Issue by itaymendel** [teambit/bit#1543]
There are some occasions in which the project workspace changes and with it the contents of the `.bitmap` file. However, the contents of Bit's local storage does not change. In most cases, this does not cause an issue. When it does - some workflows in Bit might break, forcing a reinitialization of the Bit workspace. Listed below are all the cases which may happen, and how Bit should handle them. In addition to handling the edge-cases, Bit should constantly check and if they exist in the local workspace, and prompt about to the terminal.
The goal of this issue is to make Bit more resilient to diffs between the `.bitmap` file and its local store.

Generally, Bit should assume that the component state is the one logged to the local store.

**`.bitmap` reverts to a state that a component has no version, but the component is actually `staged`.**
Bit should assume that the staged version of the conflicted component is checked-out. For example, when running `bit status` (or`bit list`), assume that the checked out version is the latest version in the store. `bit tag` should increment semver to be above the one in the store. Additionaly, running `bit export` should export the component and update the `.bitmap` entry accordingly.

**`.bitmap` reverts to a state that a component has no remote collection, but the component was actually exported (has a remote).**
This should be similar to the previous case. Bit should take the component's actual state from the store (ie - component is exported and has a remote collection defined).

**`.bitmap` has a component with a version, but without a collection defined, but the store has no references to that component.**
If this happens, Bit should assume that the component is `new`.
> note - if there is a `collection` defined the developer should run `bit import` to fetch remote objects. This is already implemented.

**`.bitmap` is empty, but there are staged components in the local store.**
This case works in general. However, when the developer runs `bit export`, Bit fails when trying to update the `.bitmap` file post-export (as there is no entry to update). What should happen is that Bit needs to export the components, but skip updating `.bitmap`. When this case happens, Bit should prompt a message to the terminal saying that the components where exported, but there were no `.bitmap` entries to update.

**`.bitmap` has a component with a version, but the component does not have that specific version in the local store.**
In this case, there are two options. Either there is a remote version that is not imported, so the developer should run `bit import`. If there is no such version on the remote collection, then Bit should assume that the `.bitmap` refers to the latest version of the component in the local store.

**`.bitmap` is empty, but the local store has exported components.**
The main issue that this case might cause is when trying to run `bit add`, and create a component with the same ID. If this happens, Bit should let the developer run the `bit add` command, but afterward, update the contents of the entry in the `.bitmap` file to have the remote collection and version of the component, as it is in the `add` process. It is important to prompt a message to the terminal that this sync has happened and why.

**Comment by odedre** [comment]
![Screen Shot 2019-05-13 at 6 47 20 PM](https://user-images.githubusercontent.com/15064762/57635630-35ded280-75b0-11e9-9835-fdc2dc7a56f4.png)

In this screenshot you can see I had a component (bit.capsule/playground-client@0.0.4 - see in the test results table).
This component is originated from this project, but after clone i didn't have the objects. 
I run `bit tag --all` and it tagged this component as new in version 0.0.1 instead of ask me to run `bit import`

**Comment by davidfirst** [comment]
Found another out-of-sync case.
`.bitmap` has a component with a remote collection, but the component doesn't exist in the local store nor in the remote store. (similar to the fifth case but here the component is missing from a local store).

It happens when one user deletes a component remotely and another user clones the project. 
For the last user, the objects weren't fetched yet, so when running `bit status`, Bit suggests to run `bit import` to pull the latest objects. However, when running `bit import`, it shows an error that the component is missing.

In this case, I wouldn't suggest changing the `.bitmap`, because the remote-scope might not be available temporarily for some reason. Instead, I'd add a command to change a component from any state to a new state. (similar to an extension @GiladShoham  wrote), so then the user has an option to resolve it.
@itaymendel , @GiladShoham , if it makes sense, I'll open a new task for it. If you do think it should be resolved as part of the out-of-sync, please suggest how.

**Comment by davidfirst** [comment]
All cases above are implemented. Added e2e-tests for all of them.

**Comment by GiladShoham** [comment]
@davidfirst Tried with 14.1.2-dev.6
.bitmap reverts to a state that a component has no remote collection, but the component was actually exported (has a remote).

```
tag a component
export it
delete the scope from bitmap 
```
got
`error: component ID is invalid, please use the following format: [scope]/<name>`
tried to delete also the version, got the same error.

**Comment by GiladShoham** [comment]
@davidfirst 

running this:
.bitmap has a component with a version, but without a collection defined, but the store has no references to that component.

Got an error about the index.json file (which is of course not updated)
let's just rebuild it ourselves..

**Comment by itaymendel** [comment]
> In this case, I wouldn't suggest changing the .bitmap, because the remote-scope might not be available temporarily for some reason. Instead, I'd add a command to change a component from any state to a new state. (similar to an extension @GiladShoham wrote), so then the user has an option to resolve it.

I think it's a basic case for the user to decide if they need to either remove the local component or wait for their wifi to work and connect with their remote ;)

**Comment by davidfirst** [comment]
@GiladShoham , about your two comments above.

1) The error you got `component ID is invalid` is because you have deleted the scope name but left the `exported: true`, as a result, Bit assumes that this component is exported and must have a scope name but it doesn't find any. It's not related to this task, but it won't happen in reality, unless a user changes manually the `.bitmap` file.

2) the error with the `index.json` file is again a result of manually deleting part of the scope and leaving some files behind. In this case, the objects were deleted but not the `index.json`.
So, it shouldn't be part of the sync issue, probably a new Github issue if you think it's needed to be taken care of.
