### ISSUE TITLE
Bit does not read package.json file of sub-package in a repo

### ISSUE THREAD

**Issue by itaymendel** [teambit/bit#1564]
## Expected Behavior

When tracking a component that is structured as a sub-package, with its own `package.json`, Bit should be able to read the dependencies defined in it, and include them (if needed) in the component.

## Actual Behavior

When tracking a component that is structured as a sub-package, with its own `package.json`, dependencies defined in the sub-`package.json` are ignored by Bit.

## Steps to Reproduce the Problem

```
git clone git@github.com:wiredjs/wired-elements.git
cd wired-elements
npm i
bit init
bit add packages/wired-button/src/* packages/wired-button/README.md -i wired-button -m packages/wired-button/src/wired-button.ts
bit status
```

## Specifications

  - Bit version: 14.0.6
  - Node version: 8.4.1
  - npm / yarn version: 5.5.1

**Comment by davidfirst** [comment]
After some debugging, the problem was that the build process of the `wired-elements` repo was skipped. 
Bit knows how to handle sub-packages. However, without building the project, the main file of wired-lib is incorrect. It's expected to be at `lib/wired-lib.js`, but the lib directory is missing before building the project.

To run 'bit status' successfully, the following steps need to be done instead.
```
git clone git@github.com:wiredjs/wired-elements.git
cd wired-elements
npm run bootstrap
npm run tsc
bit init
bit add packages/wired-button/src/* packages/wired-button/README.md -i wired-button -m packages/wired-button/src/wired-button.ts
bit status
```
