### ISSUE TITLE
support exclude when use tracked dir

### ISSUE THREAD

**Issue by JoshK2** [teambit/bit#1611]
## Expected Behavior
I want to track a dir (and keep the dir tracked) but exclude some files / dir within that dir.
consider this structure:
```
➜  tt tree
.
├── bit.json
└── comp
    ├── index.js
    └── test
        └── index.spec.js

2 directories, 3 files
```
I want to track the comp dir but exclude everything within the test folder.

## Actual Behavior
When trying to exclude files within a track dir it will remove the track dir.
When using glob patterns it sometimes even not possible to achieve this.

**Comment by GiladShoham** [comment]
@JoshK2 Thanks for reporting, we will add it to our roadmap:)

**Comment by davidfirst** [comment]
Here is a question. 
To support this feature, a new field `trackDirExclude` needs be added to `.bitmap`.
How / in what format the`trackDirExclude` will be written in the `.bitmap` file?
There are two main options. 

1. copy the value the user entered in the CLI. 
e.g. `trackDirExclude: [ 'foo1.js', 'spec/*.js' ]`
pros: the patterns users entered might do nothing now but will be relevant in the future.
In this example, for this specific component, the directory `spec` might not be created yet but will be in the future.
cons: a user might add the entire workspace with one `add` command and the `exclude` flag is not relevant to this component. Nevertheless, because it was saved in .bitmap for this component, the glob pattern will be resolved every time the component is loaded to check for new files.

2. resolve the `exclude` user entered, check what files were practically excluded from this component and add only them to the new `trackDirExclude` field. 
e.g. `trackDirExclude: [ 'spec/foo2.js', 'spec/foo1.js' ]`
pros: performance is better. no need to resolve anything.
cons: a user may add files to the `spec` dir in the above example, which will not be excluded anymore.

More consideration we should think of:
- how a user can change/remove this `trackDirExclude` field.
- a component might be added within an internal dir, so before saving it into `trackDirExclude`, it must be changed to be relative to the workspace.
- the add command might be originated from Windows and consume later on Linux. (it may sound trivial, but so far we haven't changed glob patters from one OS to another. Only full paths).

A few examples of how the `exclude` can be:
- one file `-e foo.js` or multiple files. `-e "foo1.js, foo2.js"`.
- a directory `-e bar` or multiple dirs. `-e "bar1, bar2"`.
- glob pattern `-e test/*.spec`.
- DSL `-e {PARENT}/spec`

**Comment by Tallyb** [comment]
I think a better option is to include negates in the pattern and store then as an array:
`[src/foo !src/foo/bar.js]` etc. 
minimatch is doing that AFAIK

**Comment by davidfirst** [comment]
Thanks @Tallyb . I'm going to wait with this task until the product about negate/minimatch is ready. (will be in a separate task).

**Comment by jackguoAtJogg** [comment]
I want to follow up on this feature! When will this be available?

**Comment by Tallyb** [comment]
@jackguoAtJogg  - we are considering removing this feature. Can you explain your use case?

**Comment by jackguoAtJogg** [comment]
@Tallyb I have jest mock along with the test and I dont want to include them when I track the component.

**Comment by Tallyb** [comment]
@jackguoAtJogg  - Are those defined per component? 
Do they have a glob pattern that can be ignored globally?

**Comment by jackguoAtJogg** [comment]
Yes, is defined per component. I guess I can have global pattern like `*/components/__mocks__/*`.

**Comment by davidfirst** [comment]
@jackguoAtJogg , any reason why not adding them to the component?

**Comment by itaymendel** [comment]
not supporting excluding files from dirs.
