### ISSUE TITLE
tests take a long time to run

### ISSUE THREAD

**Issue by odedre** [teambit/bit#1619]
## Expected Behavior
bit should run the tests

## Actual Behavior
Tried to run bit test but it's been over 10 minutes and the tests don't run
see attached tar file
[tar file](https://github.com/teambit/bit/files/3156348/imdb_tests_dont_run.tar.gz)

## Steps to Reproduce the Problem

  1. run bit test

## Specifications

Bit version: 14.1.0
Node version: v10.15.3
yarn version: 1.13.0
Platform: macOs
Bit compiler (include version): bit.envs/compilers/typescript@3.0.0
Bit tester (include version): bit.envs/testers/mocha@5.0.2

**Comment by GiladShoham** [comment]
@odedre Thanks for reporting this.
First for others which might hit this issue - when you face problems with `bit test` it's recommended to use `bit test --fork-level NONE`, this will prevent running tests in a child process and might catch some errors.
Regarding your specific issue, it's because the json files of the component are defined as tests files, which then mocha trying to run and get stuck.
This is an issue with mocha API which never returns.
I've tried a lot of events from the [mocha code](https://github.com/mochajs/mocha/blob/8cae7a34f0b6eafeb16567beb8852b827cc5956b/lib/runner.js#L47-L57) and none of them triggered.
We might improve the experience by prevent the mocha tester from running such files.
For this, please open an issue in the [bit.envs repo](https://github.com/teambit/bit.envs) for this and link it to here.
Once I've changed the files to be regular files, everything runs fine.
