### ISSUE TITLE
Bit overrides my readme file with an autogenerated file during export

### ISSUE THREAD

**Issue by GiladShoham** [teambit/bit#1628]
## Expected Behavior
The readme file should not be changed.

## Actual Behavior
The readme file changed to a link file:
```
/* THIS IS A BIT-AUTO-GENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY. */

module.exports = require('../../../../dist/my-comp/my-comp');
```

## Steps to Reproduce the Problem
```sh
bit init
mkdir my-comp
touch my-comp/my-comp.js
touch my-comp/my-comp.md
echo "some content" > my-comp/my-comp.md
bit add my-comp
bit tag -a
bit export my-collection
bit import bit.envs/compilers/react -c
bit tag -a
bit export my-collection
```
When not using a compiler it didn't happen.
It might be related to the fact that the main file and the MD file are with the same name (didn't test it)

The exported file contains the correct content, so it only changes after the export itself.

## Specifications

  - Bit version: 14.1.0
  - Node version: 8.10.0
  - npm / yarn version: 6.8.0
  - Platform: mac os 10.14
  - Bit compiler (include version): bit.envs/compilers/react@1.0.2
  - Bit tester (include version): NA

**Comment by davidfirst** [comment]
@GiladShoham , I'm unable to reproduce.
when I run the `add` command, I get an error about missing mainFile, I tried both, my-comp.md and my-comp.js as the main files. After the export, the `my-comp.md` file looked the same.

**Comment by davidfirst** [comment]
It happened due to the link-generation process creating a wrong link file on a symlink. 
The symlink from node_modules of `my-comp.md` points to the author file `my-comp.md`. Writing anything to that symlink causes the author file to be overwritten.

The fix above includes two parts:
1. Bit used to find `my-comp.js` as the dist file of `my-comp.md`. It has been fixed to first look for an exact match and only when not found, look for a match without an extension.
2. when a link-file finds out that the previous record was a symlink it throws an error and not trying to override it.

Added an e2e-test and merged.
