### ISSUE TITLE
Remove component(s) directly from bit.dev website

### ISSUE THREAD

**Issue by yairEO** [teambit/bit#1655]
Why isn't it possible to directly remove component(s) from the website UI itself?

I have some that got accidentally published and I want to remove them easily, with a click of a button, without using the **extremely annoying** CLI.

After being able to remove a component, I would simply sync my code with remote so the component will get unpublished locally as well.

**Comment by itaymendel** [comment]
While not a part of the Bit OSS project, I'll keep this issue to have an open discussion.

By design, we first implement features in Bit and later incorporate them to the UI. This is because the actual Bit remotes hosted on the cloud are the source of truth for [bit.dev](https://bit.dev).

As for the specifics of the delete-component capability - I'm seeing this as part of a general ability to modify and working with components on the web app alone, without a local workspace. We are working towards running isolated workspaces for components and collections that will be capable of doing many actions on top of components.

I would, however, would like to touch the reason why you find Bit's CLI as annoying for deleting components? How can we improve the flow to make it less cumbersome?

**Comment by yairEO** [comment]
It is annoying **mostly** because there is no easy integration with the IDE (I like to use vscode) so lets say I have 50 components in `/src/components` which are published to Bit, I simply do not know their published names.

Lets say I want to remove one completely from Bit, both on Local & Remote bit (but keep the local files as un-added), so right not I must figure out the name of the component by typing `bit ls`, finding the bit package I want to remove out of the long printed list of components, and then manually typing the command to remove it and then again to remove it with from remote (`-r`) since the only removing from remote does not remove from local Bit for some reason.

This is tedious, I do not like typing things, even after being a programmer for 20 years, I prefer working with GUI, since it's faster and less prone to typos.

**Comment by yairEO** [comment]
![Screen Shot 2019-05-22 at 1 03 55 PM](https://user-images.githubusercontent.com/845031/58166253-19b6f180-7c92-11e9-9c2b-c6c9ee3355ab.png)

My VSCODE sidebar with some of the Bit shared components. This is a view of my repository which is dedicated **only** for shared components, and is all about the tools other repositories consume.

Would be great if there was some icon next to each folder, indicating that a direct file in it is a Bit component, and hovering that icon would show a tooltip with the name for that component.

Just an idea

**Comment by itaymendel** [comment]
I totally understand the frustration. Doing repetitive stuff is no fun. I do think that if you had to go to each component on the site and remove it you'll still be frustrated from it.

Putting this aside, I do think that we can make the process of removing components to be less tedious.  Even from the CLI. If we add an ability to remove a component from the remote and the workspace, it should be less tedious. (@davidfirst I'd like to hear your take on it).

Additionally, you can list the components you are removing. So instead of running a command per delete, you can run `bit remove comp-a comp-b comp-c`. While reducing the number of commands issued, it is still prone to typos. You can run `bit ls` and copy-paste component names from there to a single `bit remove` command.

@GiladShoham and I have started playing around with adding an auto-complete feature to Bit that supports for command syntax completion as well as content (local and remote). It will be a bit longer to reach GA, but I hope that it'll make the experience of using Bit to be less cumbersome.

As for IDE extensions - we have [implemented a VS code extension](https://github.com/teambit/vscode-bit). But we felt that we don't have enough resource to keep maintaining it. It's been a while since then, and perhaps we're reaching a point where it makes sense to revive it.

**Comment by yairEO** [comment]
> I totally understand the frustration. Doing repetitive stuff is no fun. I do think that if you had to go to each component on the site and remove it you'll still be frustrated from it.

Not if there was a checkbox next to each component, and some high-level action that can be taken on all the selected components (like **move** or **delete**)

> You can run bit ls and copy-paste component names from there to a single bit remove command.

This is what I was doing, but I need to find those components from the list, and having a large list can make this annoying, since it's a simple text printed to the console. imagine working with 100+ bit components.. using the list doesn't help much.

I feel there is a lack of transparency between the IDE and Bit, and there's a need for to bridge that gap, as bit is quite complex to work with in, it slows my workflow considerably finding myself writing down commands on sticky notes, clearing bit cache, using `bit import` with `--override` (inconsistency with components versions) so on. I would like to have deeper integration between my IDE and bit.
looking at my `/src/components` I have no idea which component is shared and which isn't, and I have no idea for those who are shared, if they are already tagged not to mention exported. 

If there was a way, within the IDE, that opening a file would show me somewhere the name of the component, the local version vs remote version (with a link to it) that would be AMAZING. (I have many ideas of improvements)

The number of ongoing issues related to bit is a flood on my first week of trying bit, and I would somehow need to introduce bit to a whole team of developers, some are juniors, and I'm afraid the learning curve is too steep for them. too many edge cases arise until things smooth out. too many commands to remember.

This can be compared to git but while using git is not optional, bit is, and it more tools can go a long way within a diverse team.

**Comment by davidfirst** [comment]
@itaymendel , in regards to a flag of removing from both remote and locally, it makes sense to me and should be pretty straightforward to implement.

**Comment by GiladShoham** [comment]
@yairEO Just a few more words. As @itaymendel  mentioned we are working on some cool interactive experience.
I can add to the list, an option to add a checkbox for bit remove for all the workspace components. which combined with the flag to remove local and remote together, will give much better experience. I agree that an IDE plugin will be great, and I hope we will get there soon.

**Comment by yairEO** [comment]
Another `bit.dev` UI suggestion: "clone" per collection and "clone" per component, so I could clone someone's collection, in a click of a button, and rename it to be as my own collection (under my bit account) so I could make whatever modifications I desire.

**Comment by GiladShoham** [comment]
Thanks for the feedback.
Those features are already in our roadmap:)
(However, it's a bit more complicated than it seems since it requires some changed in bit's core to support it)

**Comment by yairEO** [comment]
Related - https://github.com/teambit/bit/issues/879#issuecomment-384733106
