### ISSUE TITLE
Terminology (discussion)

### ISSUE THREAD

**Issue by davidfirst** [teambit/bit#1684]
The terminology we use to describe some terms are sometimes inconsistent, mostly in the code and perhaps some in the docs. 
I started the discussion with what I have on top of my head, feel free to edit and add more.
I outlined them as checkboxes so we could easily check what we have agreed upon.

### Consumer/Scope
- [x] consumer / workspace = "workspace"
- [ ] scope / model / store = "store"
- [ ] scope name / collection name (in regards to the BitId.scope property) = "remote". (if this is about bit.dev specifically, then "collection" is fine).

### Require/Import statement
There is a confusion between `module path` and `absolute path`, it's important to distinguish between the two.

- [x]  **absolute path** - absolute path in the file system, e.g. `require('/var/user/project/something')`.
- [x]  **module path** - requiring a module, e.g. `require('lodash')` or `require('@bit/utils.is.string')`.
- [x]  **relative path** - relative to the workspacfe, e.g. `require('./utils/is-string')`;

### Config

- [x]  **bit config** - global config added by running `bit config` command.
- [x]  **workspace config** - (also knows as "consumer bit.json"), `bit.json` file in the root of the workspace or `bit` property inside the workspace `package.json` file.
- [x]  **component config** - (also knows as "component bit.json"), `bit.json` file in the root of the component or `bit` property inside the component `package.json` file.

### Link / Link files
This term is broadly used for different things. For example:
- [x]  generated link files between a component and its dependencies = "dependency links"
- [ ]  generated symlinks in node_modules pointing to the component directory = "module links" ?
- [ ]  `index.js` files that don't do anything only import and export from other files. The dependency-resolution knows to ignore these files and find the original required file. It's important to find a good name for these files. maybe "proxy files"?
- [x]  `index.js` files generated to point to the main file. Mostly replaced by `package.json` with `main` attribute. The suggested name is "entry-point files".

**Comment by itaymendel** [comment]
I think that Bit should not refer to the underline implementation of the entities, but to their function.

I'll try and share my thoughts about some of the unchecked terms:

* Local Scope - for me that's the local store for Bit's objects. The fact that it is implemented as a `scope` (Bit is distributed, so that's how it works...) is not relevant for the end user, as from their perspective it functions as a **local store**.
* Remote Scope / Collection - While underline tech behind a [bit.dev](https://bit.dev) collection is a *bit scope* it is a different product than what you use when you set up a bare Bit server. I think that the most general name that Bit can refer to ANY remote Bit scope is simply **remote**.
* I think that generally, we refer to the symlinks between components as **component symlinks**. Perhaps we can refer to them as **dependency symlinks**.
* `index.js` files that only `import` and `export` are usually **link files**, as they are used to link between different files and components.

**Comment by qballer** [comment]
Allow me to interject her :)
>* [ ]  scope / model / store = store?"

I like local scope by itay, but local collection even better.

>* [ ]  scope name / collection name (in regards to the BitId.scope property) = ?

collection name

> * [ ]   generated link files between a component and its dependencies

dependency link 

> * [ ]   generated symlinks in node_modules pointing to the component directory

module link

> * [ ]   `index.js` files that don't do anything only import and export from other files. The dependency-resolution knows to ignore these files and find the original required file. It's important to find a good name for these files. maybe "proxy files"?

module-index because it really is just an index for other modules and it is a module by it's self.

**Comment by davidfirst** [comment]
Thanks guys, so I'm summing up.

**scope / model / store = store**

scope - is the technical name, better not to use it to not confuse anyone.
Better to use 'store' when referring to the physical place where the objects are saved.
I'm thinking also to rename our two classes Consumer and Scope to Workspace and Store.
@qballer , I see where you going with "local collection", technically, a collection is a bare-scope, so it is correct, however, it doesn't convey the main purpose, which is storing objects. (it's basically the counterpart of `.git`.)

**scope name / collection name (in regards to the BitId.scope property) = remote**

When referring to the bit-id parts, it's different between bit.dev and local bare scope. So, the word `remote` helps to describe both.
Practically, on bit.dev it's the `<owner>.<collection>`, locally it's `<bare-scope>`.

**generated link files between a component and its dependencies = dependency link files**

@itaymendel , you mentioned `component symlinks`, but I'm unsure if you were referring to this section or the next one (symlinks from node_modules to components dir).
This one is about the real files, not symlinks, Bit generates on the components directory that imports and exports the dependency.
An example of a content of such a file:
```
/* THIS IS A BIT-AUTO-GENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY. */
module.exports = require('@bit/david.shared-dir.utils.is-string');
```
I think @qballer  suggestion can work `dependency link files`

It's true that in some rare cases we do generate symlinks instead of links. That happens when for example the dependency is a binary file (.png for instance), so we can't write link file to import/export it. In these cases, we can go with @itaymendel suggestion of `dependency symlinks`.


**generated symlinks in node_modules pointing to the component directory = ? (no conclusion yet)**

@itaymendel  the problem with `dependency symlinks` is that it's not about dependencies. It's about a symlink between node_modules directory and the component directory.
@qballer , `module link` is interesting. Maybe `module symlinks`?

**index.js files that only import and export = ? no conclusion yet.**
@itaymendel , the problem I have with 'link files' is that it becomes confusing with other link files such as 'dependency link files`. 
@qballer , not sure about "module-index". There are index.js files that do some logic in addition to the import/export. It's important to distinguish between the two. For the dependency-resolution Bit skips that file only if it doesn't do anything else only import and export. 

I'm wondering if there is a name for this kind of file in the industry so we don't need to come up with our own.

@imsnif , feel free to chime in.

**Comment by qballer** [comment]
the point of my naming is to give names which don't convey implementation. Instead convey the interface. Does the "local collection" encapsulate the object store and provides a collection mechanism? If it does so, I think my name has merit. It does it by implementing a .git like object store. 

module symlink is nice, but once again you are giving out implementation - What does the thing do !? Links module to a component, how does it do it? with a symlink - the thing is a "module link" in my mind. 

module-index was awkward for me too, the problem is that in JS land index is so overloaded. Maybe a "module reference file"? When I was thinking of it, it reminded me a DB index which is just used to point to other records. Replace records with modules and you get my suggesting.

**Comment by imsnif** [comment]
Hey, thanks for the tag - I'm happy we're talking about these things. :)
The most important thing to me here is the term "scope" itself. I feel it's a bit of a problematic term in the space in which we live, since npm uses it for something completely different: https://docs.npmjs.com/misc/scope
This becomes especially confusing when maintaining the bit registry.

I like the suggested term "store" instead, and would vote for removing the term "scope" from all of our code-base unless it refers to the same thing npm refers to. What do you all think?

**Comment by davidfirst** [comment]
Thanks guys.

> I like the suggested term "store" instead, and would vote for removing the term "scope" from all of our code-base unless it refers to the same thing npm refers to. What do you all think?

Yes. The plan is to gradually get rid of `scope` and `consumer` in the code base. 
(Although we'll probably need to leave it for the `BitId.scope` property, otherwise, it'll need a massive migration for all components.)

**Comment by itaymendel** [comment]
I disagree with removing ‘scopes’ from Bit’s codebase.

Bit is a distributed system. In a distributed system every node is both a server and a client. We can’t have different names for them.

I think you misunderstood my comment on ‘scope’.

My take on it is that from a bit-user perspective remote-scopes are simply remotes (and local-scope is a local store).
For me the difference is to abstract the complexity of understanding Bit’s internals (especially that fact that Bit is distributed, as its much easier, when using Bit as a client, to refer to it as a simple client. Instead of a node in a distributed system).

Other types of users (for example an extension-maintainer, or an engineer that manage a deployment of bit-servers) will need to be fully aware to the fact that bit is distributed. This should not be abstracted away from them.

Why we chose scopes to begin with:
Components represents functionality. We can group functions by their scope. For example- here are all the functions that deal with UI, or here are all the functions that my project uses.
These are scopes.

**Comment by itaymendel** [comment]
I think you misunderstood my comment.
I did not mean that the term `scope` should be changed. I only referred to how I think we should explain it to novice Bit users.

**Comment by Tallyb** [comment]
>  absolute path - absolute path in the file system, e.g. require('/var/user/project/something').

full path

 > module path - requiring a module, e.g. require('lodash') or require('@bit/utils.is.string').

> non-relative path

- [x] relative path - relative to the workspacfe, e.g. require('./utils/is-string');

**Comment by GiladShoham** [comment]
@davidfirst Before any actual change in the codebase, we need to make sure each term is approved.
