### ISSUE TITLE
wrong dependency resolution

### ISSUE THREAD

**Issue by GiladShoham** [teambit/bit#1698]
## Expected Behavior
The bit.envs/internal/typescript-base-compiler dependency of react-typescript and typescript should be 3.5.0 and not 1.0.0

## Actual Behavior
The dependency is shown as 1.0.0

## Steps to Reproduce the Problem

  1. clone `https://github.com/teambit/bit.envs`
  1. move to a37022d105e6ac94836ca00ee99d678f9a4eed0f hash
  1. install everything needed
  1. run `bit show compilers/typescript`
  1. see the internal/typescript-base-compiler dependency version

I have no idea where version 1.0.0 is coming from. This version has never existed. It's a new component I've just tagged in v3.5.0 and export.
After tagging both react-typescript and typescript, they are still modified, now show the dependency with the correct version

## Specifications

bit version   : 14.1.2-dev.6
  node version  : v8.10.0
  npm version   : 6.8.0
  yarn version  : 1.9.4
  platform      : darwin

**Comment by davidfirst** [comment]
This happens when an imported component requires an authored component and the dist directory is set to be outside of the components dir.
The link-generator used to generate incorrect symlinks from the workspace root to the imported component. As a result, the dependency-version-resolution used the package.json of the workspace to conclude the version of the authored component.

This has been fixed to not generate such symlinks as they are not needed.
