### ISSUE TITLE
failed adding a symlink into DataToPersist, src is empty

### ISSUE THREAD

**Issue by GiladShoham** [teambit/bit#1702]
## Expected Behavior
bit link should work 

## Actual Behavior
I got an error - failed adding a symlink into DataToPersist, src is empty

## Steps to Reproduce the Problem

  1. git clone https://github.com/teambit/bit.envs.git
  1. (rename the folder to something else to prevent conflict on the local scope name)
  1. bit import (takes a long time)
  1. bit link

## Specifications

bit version   : 14.1.2
  node version  : v8.15.1
  npm version   : 6.4.1
  yarn version  : 1.13.0
  platform      : darwin
  user details  : Gilad Shoham<shoham.gilad@gmail.com>

**Comment by davidfirst** [comment]
This issue happens when an imported component requires an authored component. 
The link generator was trying to generate a symlink from the authored component rootDir to the node_modules of the imported component. Since the rootDir of authored components is the workspace rootDir, it got an error.

The fix was to avoid generating the symlink in this case. Because it's an authored component, the root node_modules already have this component, so no need to link it to other components.

While fixing this issue, I have noticed another issue with the package.json generated for the author in node_modules, which was pointing to the dist file. 
It has been fixed to always point to the generated link file inside node_modules regardless of the dist status because the generated link file already takes care of the dist and knows to point to the correct file.
