### ISSUE TITLE
can't find component on import

### ISSUE THREAD

**Issue by qballer** [teambit/bit#1711]
## Expected Behavior
bit import after cloning a project should work.

## Actual Behavior
can't find components

## Steps to Reproduce the Problem

  1. clone https://github.com/teambit/bit.envs
  2. run bit import

## Specifications

  - Bit version: 14.2.1
  - Node version: 12.3.1
  - npm / yarn version: 6.9.0
  - Platform: Linux
  - Bit compiler (include version): N/A
  - Bit tester (include version): N/A

The work around for that is to go into the .git/bit folder and change the scope name to something different. I would also expect bit doctor to detect this issue (scope name is the same as containing folder name).

**Comment by GiladShoham** [comment]
I've added a section about running this project
https://github.com/teambit/bit.envs/blob/master/README.md#running-this-project
which doesn't work yet..
1. I got an error during `bit link` or `bit build` (when running them before the `bit import --merge` which tells me to run `bit import --merge` (there is no reason I'll have to run it after clean clone + `bit import`
2. when I do run `bit import --merge` I also got an error:
 `error An unexpected error occurred: "EEXIST: file already exists, mkdir '/private/tmp/bit.envs/node_modules/@bit/bit.envs.testers.karma-mocha-react/node_modules'".`
3. even after running `bit import --merge` and `bit link` I still have missing binding files which cause me errors 
```
     > compilers/babel ...  issues found
       non-existing dependency files (please make sure all files exists on your workspace):
          compilers/babel/index.js -> ../../internal/babelBaseCompiler

     > compilers/flow ...  issues found
       non-existing dependency files (please make sure all files exists on your workspace):
          compilers/flow/index.js -> ../../internal/babelBaseCompiler

     > compilers/preact ...  issues found
       non-existing dependency files (please make sure all files exists on your workspace):
          compilers/preact/index.js -> ../../internal/babelBaseCompiler

     > compilers/react ...  issues found
       non-existing dependency files (please make sure all files exists on your workspace):
          compilers/react/index.js -> ../../internal/babelBaseCompiler

     > internal/babel-base-compiler ...  issues found
       non-existing dependency files (please make sure all files exists on your workspace):
          babelBaseCompiler/index.js -> ../getBabelOptions
```
(On my old workspace I have binding files in those locations)
4. As @qballer mentioned, we should identify a case when the local scope and the remote scope are identical and do something about it

**Comment by davidfirst** [comment]
First, I'll describe the main issue here.
When running `bit link` with `dist` outside of the components dir, Bit generates symlinks from the workspace node_modules/@bit to the dist directory. 
For example: `dist/components/compilers/babel` (existing dir) => `node_modules/@bit/bit.envs.compilers.babel` (generated symlink)
Now, if the `dist` directory doesn't exist (e.g. when cloning the project), the symlink will fail. 
Currently, the error message suggests to `bit import --merge`.

Our options to fix it (by fixing it I mean to re-build the `dist` directory) are as follows:

1. use `bit build`. Obviously, that's the natural candidate for the job. However, two issues I see here. A) when importing dependencies as components (and not as packages), the dist of these nested dependencies will be missing. Currently, `bit build` only runs on Authored and Imported, not Nested. B) performance. If the components are modified, it'll have to download their compilers.
2. use `bit import --merge`. Import merge writes the components to the filesystem includes the dists. Problem is that when the dist is missing, some components are marked as modified, and then depends on the merging strategy it won't write the dists. The fix should be to identify when links are missing and then write the dists.

Another issue we have here is with Yarn. See the symlinks I described above pointing to the dists. Yarn doesn't like these symlinks. When the `dist` is inside the components dir, the symlink is to the source, which Yarn doesn't have any problem with. However, in this case, Yarn throws an error.
As a result, if the user was running `bit build` or `bit link` which created these symlinks, and then was running `yarn`, an error is thrown.

Our options to fix it are as follows:
1. change `bit install` to delete `node_modules/@bit` before running the package manager installation. This way, even though Yarn throws errors, we instruct users to only run `bit install`. (It makes sense because regardless of this issue they must rebuild the links after running `yarn`).
2. do not add the imported components with file path into the root package.json. I don't remember why they are added, must be a good reason. 
3. do not symlink to the `dist` only to the source. Not sure it's a good idea. We need to think about it.

**Comment by davidfirst** [comment]
Discussed with @itaymendel  about rebuilding the dist directory, the conclusion was to add a new flag for the `build` command to allow building also nested dependencies.

**Comment by GiladShoham** [comment]
@davidfirst Can you open a new issue about it?

**Comment by alizangiabadicode** [comment]
hi guys. i think i found the solution. importing components link this import dummy from '~/component/dummy.vue' will not work
because of '~'. we should use .. notation instead

**Comment by itaymendel** [comment]
irrelevant for v15

We'll start rolling out v15 of Bit this week, please reach out to me privately on the [public slack community](https://join.slack.com/t/bit-dev-community/shared_invite/zt-9egg85xv-trr_QBkWr1XcVgtrgCvtfQ) for a sneak peek and getting early access to it.
