### ISSUE TITLE
Project structure for component isolated environment

### ISSUE THREAD

**Issue by itaymendel** [teambit/bit#1758]
The component isolated environment (capsule) should be modeled like any node project. This simplifies the user experience for developers that want to explore and work with it.

### Description

When a component is isolated, Bit should create a basic project structure for it with the context of the isolated components. This means that it should look and feel like working on an isolated project that was created for the specific component.

### Describe the solution you'd like

Below the desired directory structure:

```sh
.
├── node_modules
│   └── @bit
├── package.json
├── .dependencies
└── [component-root]
```

1. A single `node_module` dir in the root folder.
1. `.dependencies` directory for component dependencies
1. A `package.json` file.
    - Should use [local path](https://docs.npmjs.com/files/package.json#local-paths) for component dependencies (should be installed to the `node_modules/@bit` directory).
    - Contains the `bit` configuration object of the component.
1. The component's root directory, containing all relevant files and directories.

**Comment by qballer** [comment]
Some more details for angular capsule. 
[angular-capsule2.tar.gz](https://github.com/teambit/bit/files/3325403/angular-capsule2.tar.gz)

This example was created by isolating manually the accordion component from primeng repository. 

What we can see in this file is the following: 
1. We create a public_api.ts file which leads to the component mainFile. This is only requires if we don't have that main file in the root of the capsule (this is true for typescript and angular - rootDir issue).
2. the `shared` dependency was compiled before the `accordion`. inside node_modules we have the compiled version of shared (created manually). blockableui wasn't compiled but it's only the interface, not an ng construct.
3. inside `node_modules/@bit/shared` package.json I've added the following manually:
```
  "module": "dist/fesm5/bit-shared.js",
  "es2015": "dist/fesm2015/bit-shared.js",
  "esm5": "dist/esm5/bit-shared.js",
  "esm2015": "dist/esm2015/bit-shared.js",
  "fesm5": "dist/fesm5/bit-shared.js",
  "fesm2015": "dist/fesm2015/bit-shared.js",
  "typings": "dist/bit-shared.d.ts",
  "metadata": "dist/bit-shared.metadata.json"
```
This information is required the angular package format. 
4. There is no need for main file in the package.json of accordion
5. ng-packagr entryFile should lead to the entry of the component created in (1). This is related to angular compiler. 
6. .deps folder was created so bit will have a location to place components. the node_modules should lead it to using a symlink.
7. its important to note that bit doesn't share some of the dependencies of the component in the compiler API. they appear in the package.json but not in the `componentObject` passed to the compiler.

**Comment by itaymendel** [comment]
Few notes after reading @qballer 's comments -

The notes that regard the directory structure of each capsule are the same as notes in the first description of the desired output. All other notes require opening different tasks and handling them individually. These are new tasks to create:

1. Create the `public_api.ts` file only when no such file found in the component, and its content should be - `export * from '<main_file>';`
1. Bit should compile components in order.
1. Compilers should have API to add keys to the component's `package.json`.
1. There's a missing dependency when using the `componentObject` API - https://github.com/teambit/bit/issues/1759

All other notes refer to specific things that a specific compiler does. And are unrelated to Bit.

**Comment by qballer** [comment]
a note about 2 - the order should be a toposort of the dependents tree

**Comment by qballer** [comment]
I've been testing the current capsule using https://github.com/primefaces/primeng and trying to build ```accordion```. Several Issues are detected: 
1. I see there are link files to `@bit/shared` when @bit folder is empty.
2. some dependencies which are mentioned in package.json aren't installed.
3. order of compilation  needs some real time discussion. 
 
I think we need to have a session on come back with better understanding of the problem.

**Comment by itaymendel** [comment]
@qballer , the discussion about compilation order is in this issue you have opened https://github.com/teambit/bit/issues/1663 
Have you had a chance to read through @davidfirst last comment?

**Comment by davidfirst** [comment]
@qballer , according to the 4 issues described above.
> 1. I see there are link files to @bit/shared when @bit folder is empty. (primeng/accordion)

See my comment here: https://github.com/teambit/bit/issues/1771#issuecomment-507414647 # 1. It explains why the content of @bit disappeared.
(In general, I believe it'll help you to create a capsule regardless of your compiler so you could compare and see whether the issue comes from the bit-bin or from the compiler.
It's super easy, just run `bit isolate your-component --use-capsule -d your-directory`.)

A few ideas on how to handle it:
- expose an option to add packages into the main package.json BEFORE the capsule is running "npm install". This will fix also the next issue ( # 2, see below).
- expose an option in the capsule to run "bit link". (?) not sure how easy would it be.
- with the changes done in this PR https://github.com/teambit/bit/pull/1726 it might be fixed already because the NPM itself generates the symlinks.

> 2. some dependencies which are mentioned in package.json aren't installed. (primeng/accordion- rxjs and zone.js)

This is also happening as an outcome of # 1, I tried generating only the capsule using the command above and got all packages, including `zone.js` and `rx` as expected. Once I ran `npm i tslib`, these packages got deleted. I'm unsure why NPM reacts this way, but I don't think it has something to do with Bit. I made sure that the package.json does have these packages, so no good reason to remove them. 

> 3. link files are generated with .ts extension which needs to be removed. (ngx-bootstrap/accordion - node_modules/ngx-bootstrap/collapse/index.ts) -#1771

This has been fixed and merged into master.

**Comment by davidfirst** [comment]
All work related to this task had been completed and merged into master.
