### ISSUE TITLE
capsule.exec should reject the promise

### ISSUE THREAD

**Issue by qballer** [teambit/bit#1772]
### Describe the bug

When running capsule.exec the returned promise isn't rejected if the process fails 
For a matter of fact I'm not sure if it even returns a promise because there is no completions or information on the API (#1753) (description on isolate that it is a function - what is the returned interface?).

### Steps to Reproduce
  1. run capsule.exec on a failing command
  2. promise should be rejected

### Specifications
bit version   : 14.1.4-dev.5
node version  : v12.3.1
npm version   : 6.9.0
yarn version  : 1.16.0
platform      : linux

### Additional context

**Comment by davidfirst** [comment]
@qballer , the fs-container implements the `capsule.exec` according to the API.
The result you get after resolving the promise is a ChildProcess, which has the `stdout` and `stderr`. So, in case of a failure, check the `stderr`. The promise won't be rejected.
As a reference, you can see the API of the capsule and the [unit-tests of the fs-container](https://github.com/teambit/bit/blob/master/components/container/fs-container/container.spec.ts#L59).


Because it's not trivial, and you would expect it to work similar to `execa`, meaning, returning a promise with resolve/reject according to success/failure, I exposed a new function to the compiler named `capsuleExec`, which works exactly like this.
You won't need it though, because I exposed another function `installPackages`, for your `npm install` commands. See https://github.com/teambit/bit/issues/1856 for more details.

**Comment by GiladShoham** [comment]
@davidfirst Awesome!
Keep in mind that we might change the capsule.exec API a bit soon.
So once we will merge to the recent version of the capsule API we will have to do some changes here.
