### ISSUE TITLE
TS link files are being created in node_modules

### ISSUE THREAD

**Issue by ranm8** [teambit/bit#1810]
### Describe the bug

When one TS component is dependent on other TS component using an alias, the generated node_module link is generated as a Typescript. It should generate a .js file instead with the same contents.

### Steps to Reproduce

1. clone ngx-bootstrap.
2. track components `src/alert` and `src/utils`
3. use the ng-packgr compiler (@0.0.19) 
4. export these components
5. install the component into an existing project
6. you will notice that under the node_modules directory of @bit/user.ngx-bootstrap.alert, a wrong link to the `utils` component now exists (e.g. index.ts).

### Expected Behavior

the `utils` component link in the `alert` node_modules directory should be renamed from index.ts to index.js

### Specifications

- Bit version: 14.1.4-dev.9
- Node version: v10.16.0
- npm version: 6.9.0
- Platform: MacOS 10.14.5
- Bit compiler (include version): ng-packgr@0.0.19
- Bit tester (include version): N/A

**Comment by davidfirst** [comment]
The reason for generating a link with `.ts` extension is related to the fact that this compiler generates dists with different paths than the source.
It has been fixed by the commit above to disregard the dists files and generate links with `.js` extension even when the current extension is `.ts`, `.tsx` or `.jsx`.
