### ISSUE TITLE
Make `src/imports` the default location for imported components

### ISSUE THREAD

**Issue by Tallyb** [teambit/bit#1830]
#1797 # Description
Currently, new components are imported by default into `components/{name}`. This folder is not under the source code of the other components. Imported components should be part of the source of the components. 

### Describe the solution you'd like
Make the default location for imported components when bit initialize the workspace to be: `src/imports/{name}`

**Comment by itaymendel** [comment]
I'm not sure that `imports` is the right name here.
What do you think about `bit-components`?

**Comment by davidfirst** [comment]
The question is whether in most cases the compiler and tester of the imported components are the same as the author?
Because if not (and I believe it's not) then users will need to exclude this directory from their compiler and tester configuration and will end up with more configuration changes to make.

**Comment by itaymendel** [comment]
default location changed to fit component location in v15

We'll start rolling out v15 of Bit this week, please reach out to me privately on the [public slack community](https://join.slack.com/t/bit-dev-community/shared_invite/zt-9egg85xv-trr_QBkWr1XcVgtrgCvtfQ) for a sneak peek and getting early access to it.
