### ISSUE TITLE
Haste module naming collision: react-animated

### ISSUE THREAD

**Issue by jpmazza** [teambit/bit#1842]
### Description

A few days ago, I uploaded my first react-native component to Bit. https://bit.dev/effectus/form/input/~code#index.js

So I've created a new project using `react-native init`, I've also installed my component (yarn add @bit/effectus.form.input) import and use my component.

When I build the project the following appears:

Haste module naming collision: react-animated

  The following files share their name; please adjust your hasteImpl:

    * <rootDir>/node_modules/react-native/Libraries/Animated/release/package.json

    * <rootDir>/node_modules/@bit/tomasotano25.reactnative.spinners.spinner/node_modules/react-native/Libraries/Animated/release/package.json

### Context and additional information

"react": "16.8.6",
"react-native": "0.60.4"

**Comment by GiladShoham** [comment]
Hi @jpmazza 
That looks like in issue with duplicate instances of react / react-native.
The easiest way to solve it is to make sure the react and react-native dependencies of your component are peer dependencies rather than regular dependencies.
You can do it by moving the react / react-native into peer-dependencies in the package.json of the original project.
Or import the component into some temp dir and change it there then tag and re-export.
(You can make sure the change worked by using `bit show [component-id]` before tagging a new version)
