### ISSUE TITLE
 new Extension API: Design issues

### ISSUE THREAD

**Issue by qballer** [teambit/bit#1935]
### Describe the bug

Right now the new Extension API requires that you expose an object with the implementation of the extension API.  This is a nice start but may cause issues with isolation as the extension may hold state between function execution. Meaning that I might want a different instance of the compiler for each component. I suggest that the API should receive a constructor/factory method so Bit can create the instance of the extension on each compilation.  

Order of execution doesn't make sense.  Also bit runs the following functions twice in the run of the first component: `getDynamicPackageDependencies`, `getDynamicConfig` and `init` - in this order. The order (in my mind) should be init -> config -> dependencies. 

### Steps to Reproduce
run an empty compiler which just prints which functions are running

**Comment by davidfirst** [comment]
Ignore the above reference to the PR https://github.com/teambit/bit/pull/1936.
By mistake, I connected it to this issue, but it's really related to #1934.

**Comment by davidfirst** [comment]
@qballer , can you show where the same instance of the compiler is used for multiple components? I did a quick test, I added a property to some objects the compiler passes and observed how these properties do not appear on other components.

It does run the steps described above twice. The second time is to check whether the component compiler has some config files that need to be written and if so, it writes them before trying to compile. We can optimize it for sure. @GiladShoham , let's discuss this.

The order of calls in intentional. First, Bit parses the custom config/packages configuration, does some manipulations, once it has the configuration in the proper format, it passes them all into the `init` method to initiate the compiler.

**Comment by qballer** [comment]
I did the same test and it showed med the one instance. This also makes sense because I need to expose a single object with the proper function on it already. This can't be any other instance as far as I understand it.

**Comment by qballer** [comment]
This was my test file:
```typescript
import { Compiler, InitAPI, CompilerContext, Logger } from "./compiler";
import { compile } from './compile'

const CONFIG_NAME = 'tsconfig'

export class TypescriptCompiler implements Compiler {
    private _logger: Logger | undefined

    init(ctx: { api: InitAPI }) {
        print('init')
        this._logger = ctx.api.getLogger()
        return {
            write: true
        }
    }
    getDynamicConfig(ctx:CompilerContext) {
        print('getDynamicConfig')
        return {}
    }

    getDynamicPackageDependencies(ctx: CompilerContext, name?: string) {
        print('getDynamicPackageDependencies')
        return {}
    }

    async action(ctx: CompilerContext) {
        print('action')
        const compileResult = await compile(ctx, ctx.context.rootDistDir, ctx.context)
        return compileResult
    }

    get logger(): Logger | undefined {
        return this._logger
    }
}


function print(name: string) {
    console.log(`\n${name} is fired`)
}
```

this is the console:
```
getDynamicPackageDependencies is fired
getDynamicConfig is fired
init is fired
getDynamicPackageDependencies is fired
getDynamicConfig is fired
init is fired
action is fired
```
I've run `bit build ninja`

**Comment by itaymendel** [comment]
irrelevant with v15

closing this issue
