### ISSUE TITLE
Link generation file to scss component folder is not working

### ISSUE THREAD

**Issue by JoshK2** [teambit/bit#1965]
### Describe the bug

I tried to export this project https://github.com/HealthCatalyst/Fabric.Cashmere/tree/dev, and have a bug with sass component.
The link generation is to the folder of the component in the node modules, like this:
`@import '~@bit/sass._colors';`
and this is not working, but if I change the link in the capsule to this:
`@import '~@bit/sass._colors/index.scss';`
this will work.

### Steps to Reproduce

1. clone the project https://github.com/HealthCatalyst/Fabric.Cashmere/tree/dev
2. run `npm install`
3. run `bit init`
4. run this bit add commands:
```
bit add projects/cashmere/src/lib/button -t 'projects/cashmere/src/lib/button/*.spec.ts'
bit add projects/cashmere/src/lib/sass/* -n sass
bit add projects/cashmere/src/lib/util.ts -t 'projects/cashmere/src/lib/util.spec.ts'
bit add projects/cashmere/src/lib/pop
```
5. run `bit status`, should be ok.
6. import the angular compiler: `bit import bit.envs/compilers/angular -c`
7. add this overrides to bit object:
```json
"overrides": {
            "sass/*": {
                "env": {
                    "compiler": "-"
                }
            }
        }
```
8. run the build command to see the capsule link:`NG_DEBUG=true bit build pop`

### Specifications

- Bit version: 14.2.6-dev.2
- Node version: v10.16.0
- npm version: 6.9.0
- Platform: macOS
- Bit compiler (include version): 0.2.0

**Comment by davidfirst** [comment]
It was a tricky bug, it worked differently with different machines and different node versions. Eventually, the mystery solved by looking at how `ng-packagr` resolves sass:
node_modules/ng-packagr/lib/ng-v5/entry-point/resources/stylesheet-processor.js
```
let sassComplier;
try {
    sassComplier = require('node-sass'); // Check if node-sass is explicitly included.
}
catch (_a) {
    sassComplier = require('sass');
}
```
So, according to the specific configuration (directory/node-version etc), it is able or unable to require `node-sass`.
If the resolver is node-sass, it doesn't know to resolve a directory and it must be a file. (See an open issue https://github.com/sass/sass/issues/690 on their repo).
Otherwise, when the resolve is `sass`, it knows how to resolve a directory and it works fine.

The fix (/workaround) in the commit above makes sure to always point to the main file when the extension is `.sass` or `.sass`.
