### ISSUE TITLE
Npm not being able to find a file while importing a collection

### ISSUE THREAD

**Issue by DeyLak** [teambit/bit#2003]
### Describe the bug

I have a collection and I try to import it into a new workspace by running
`bit import pik-pro.mobile-apps/*` This results in error:
```bash
failed running npm install at /Users/deylak/bit-test/components/auth/auth   
npm ERR! code ENOENT
npm ERR! syscall rename
npm ERR! path /Users/deylak/bit-test/components/auth/auth/node_modules/.staging/classnames-f521094c
npm ERR! dest /Users/deylak/bit-test/components/components/loading-indicator/node_modules/classnames
npm ERR! errno -2
npm ERR! enoent ENOENT: no such file or directory, rename '/Users/deylak/bit-test/components/auth/auth/node_modules/.staging/classnames-f521094c' -> '/Users/deylak/bit-test/components/components/loading-indicator/node_modules/classnames'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 
npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/deylak/.npm/_logs/2019-09-17T08_00_27_167Z-debug.log
```

The `components/` folder contains all the components, but `node_modules` are failed to install and `.bitmap` file is empty.

### Steps to Reproduce

1. Create an empty Bit workspace
1. Run `bit import pik-pro.mobile-apps/*` (It is a private collection, but I already added itay@bit.dev to it)

### Expected Behavior

Components are correctly imported.

### Screenshots, exceptions and logs
Here is the log of running import process:
[2019-09-17T07_56_58_262Z-debug.log](https://github.com/teambit/bit/files/3621247/2019-09-17T07_56_58_262Z-debug.log)

### Specifications

- Bit version: 14.3.0
- Node version: v10.16.0
- npm version: 6.11.2
- Platform: MacOS Mojave 10.14.5 
- Bit compiler (include version): -
- Bit tester (include version): -

### Additional context

We discussed this problem if gitter chat with itay@bit.dev. Changing the package manager to yarn fixes the problem. So this is probably problem with npm itself.

**Comment by davidfirst** [comment]
Thanks @DeyLak for providing me access to the collection. 
I was able to reproduce the bug with a small subset of 3 components and without using Bit.
It's an NPM bug. I opened a ticket on their site, you can see all the details there.
https://npm.community/t/enoent-error-when-the-same-package-appears-in-local-dependencies/10099

For future visitors of this ticket, it happens in the following scenario:
Three components were created: comp-a, comp-b and comp-c. comp-a requires comp-b and comp-c, comp-b require comp-c. All components has the same package-dependency, say, `lodash`. 
Once a user imports these three components and NPM is running on the root-dir of comp-a, it tries to install `lodash` for all three components (because in the package.json of comp-a there is a relative-path for comp-b and comp-c) and fails.
