### ISSUE TITLE
Ask for approval before export a component to another scope (fork)

### ISSUE THREAD

**Issue by itaymendel** [teambit/bit#2004]
### Description

Forking components in Bit is a very simple workflow. However, if done no-correctly it might have severe consequences. Additionally, Bit has a set of flags to better control the fork behavior, and have a stable flow.

### Describe the solution you'd like

When an export command is about to add an existing component from one collection to another (fork), Bit should trigger a message asking for confirmation for the action (yes/no).
Additionally, it should tell the user about the flags to control the behavior.

I suggest this message:

```
bit is about to fork the components [<component ID>...] and export them to <destination scope>.
there are additional flags for the 'export' command to specifically handle forking components:
1. '--include-dependencies' exports all dependencies to the destination alongside the component.
2. '--set-current-scope' sets your workspace to use the destination scope as the main remote for the component.
3. '--codemod' changes all dependencies to point to the new destination.

would you like to proceed with forking the components? (yes/no)
```

**Comment by davidfirst** [comment]
Looks like a good precaution. 
I'd suggest minor editing to the message above. Since the components list to export might be a long one, I'd change the first line to something like the following:
```
bit is about to fork the following components and export them to <destination scope>.
comp 1.
comp 2.
...
```

Also, I suggest adding a new flag (maybe `--silent` or re-use the `--force`) to skip the prompt.

**Comment by itaymendel** [comment]
👍 
`--force` should silence it, that's for sure.
but I'm unsure if `--silent` is correct here. we're not silencing anything, it requests for confirmation. I'd go with `--yes` flag (if anything).

**Comment by davidfirst** [comment]
Thanks Itay. So, for now, I'll just reuse the `force` flag to not show the prompt. We'll probably need to change the description of this flag to indicate this.

**Comment by davidfirst** [comment]
@itaymendel , I'm thinking maybe we should also convey in this message the new behavior of leaving the components as staged unless `--set-current-scope` is used.
For @KutnerUri  it was an unexpected result.

**Comment by GiladShoham** [comment]
I agree with @davidfirst about writing something about keeping the component as staged.. let's add it to the message.

**Comment by KutnerUri** [comment]
hey sorry for coming late, but here are my thoughts:

We should avoid user input as much as possible.
1) They make a worse experience, because the User needs to process and decide on them every single time.
2) They make the flow less deterministic.
3) They can stop automated scripts.

So, I'm suggesting this syntax:
```bit export <target> <component[]>```
* should always remove the component from staging (ie. component require no additional actions)
* should show warning, when exporting to a new collection:
```
> bit export kutner.normal fs/cd fs/ls fs/cat
exported 2 components to [kutner.normal]
new in this collection:
(cmp)       (from)
fs/ls       local workspace / NEW
fs/cat      kutner.experimental

(use bit `export kutner.experimental fs/cat` to export the component back to its original collection)
```
* should allow export of un-modified components.
```
> bit add ./write-random.js --id fs/writeRandom
added...
> bit tag -a
...
> export kutner.experimental fs/writeRandom
exported 1 component to [kutner.experimental]
> export kutner.normal fs/writeRandom
exported 1 component to [kutner.normal]
```
* I believe our syntax should resemble as sentence, making it more readable.
```
> bit export fs/jitter fs/dog --to kutner.normal kutner.experimental
exported 2 components to 2 collections:
kutner.normal/fs/jitter
kutner.normal/fs/dog
kutner.experimental/fs/jitter
kutner.experimental/fs/dog
```

### set-current-scope
I don't understand this. I thought it was supposed to set the remote Collection for the component, so I could just run ```bit export fs/cat``` without specifying target, but it doesn't seem to work.

* Does it apply for specific components, or for the whole workspace?
* Can't we do it after export?
