### ISSUE TITLE
TS Types of dependency are not being updated, when building dependant

### ISSUE THREAD

**Issue by DeyLak** [teambit/bit#2041]
### Describe the bug

I'm trying to add new prop to my component, which is dependency of another (both are imported into workspace)

### Steps to Reproduce

1. Create comp-a and comp-b depending on comp-a and rendering it with some prop. Import them into workspace
1. Add some new prop to comp-a
1. Try to use it in comp-b and get type error from typescript. Not matter, if you built comp-a, or not. `build --no-cache` also doesn't help
1. Tag and eject comp-a to get correct types in comp-b

### Expected Behavior

Types are being updated. 

### Specifications

- Bit version: 14.4.0
- Node version: v10.16.0
- yarn version: 1.10.1
- Platform: macOS
- Bit compiler (include version): typescript 
- Bit tester (include version): -

**Comment by DeyLak** [comment]
Sorry, I think, this is still the duplicate of https://github.com/teambit/bit/issues/2024
May be it was too much of coding for me...

**Comment by DeyLak** [comment]
Hmmm... That's a very strange issue, I can't understand the behaviour of Bit. 
Here I have 2 components, which I managed to tag and export without any ts errors, though they should present, if I'm not mistaken:
https://bit.dev/deylak/test/comp-a/~code
https://bit.dev/deylak/test/comp-b/~code

Here is a copy of my workspace, I used to export the components:
[bit-test.zip](https://github.com/teambit/bit/files/3667572/bit-test.zip)

**Comment by davidfirst** [comment]
@DeyLak , not sure I understand the issue. I downloaded the attached zip and as you said, it builds with no errors. Is it because it's imported and the issue you found was only for the author?

If you could upload the files in the state where you got the errors and you wouldn't expect them, I'll take a look to see what's going on.

**Comment by itaymendel** [comment]
TS workflow updated in v15, this issue is resolved

We'll start rolling out v15 of Bit this week, please reach out to me privately on the [public slack community](https://join.slack.com/t/bit-dev-community/shared_invite/zt-9egg85xv-trr_QBkWr1XcVgtrgCvtfQ) for a sneak peek and getting early access to it.
