### ISSUE TITLE
Feature request: Adding namespace to existing Bit component

### ISSUE THREAD

**Issue by jimmi-joensson** [teambit/bit#2071]
Hello, I have only been able to find information about adding a namespace to a new Bit component, however it would be awesome to be able to add/edit the namespace of an existing component as well.
Example: paragraph@1.0.0 --> components/paragraph@1.0.0

**Comment by GiladShoham** [comment]
@jimmi-joensson Thanks for reporting this.
You are correct, there is no easy way now to do so.
The reason is that adding a namespace is like changing a component name which has a lot of Implications. (like changing dependencies, changing require statements etc').
Anyway, we are working on this at the moment, but it will take some time. 
I don't have an exact ETA now, but I'll update this issue once it's ready.

**Comment by jimmi-joensson** [comment]
@GiladShoham Thanks for the answer. Sounds good that it is already part of the road map, because it is an essential feature for me at least.

**Comment by GiladShoham** [comment]
I'll update you on the progress here.

**Comment by StillUpgrade** [comment]
Hi, any news about this ?

**Comment by itaymendel** [comment]
hi,

this requires duplicating the components and adding a namespace for the duplicated component. it will be a part of the updated `bit mv` specification.

closing this ticket.

**Comment by h3nk42** [comment]
@itaymendel 
Hi, 
so if i want to change the namespace of a component i would have to duplicate the files and track them as a new component under a new namespace ? How do I update the dependents of my old component that i duplicated ?  -> i guess i have to push their versions and tag them with the new dependency pointing to the duplicated component under new namespace ?

-> so all versions of the dependent before pushing the version will break, why cant I deprecate those specific version but only the whole component ?
