### ISSUE TITLE
Styled Components props

### ISSUE THREAD

**Issue by dastasoft** [teambit/bit#2087]
The props of the styled components are not display on the props table.

I have a base component with the logic:
```
BaseFancyButton.propTypes = {
  className: PropTypes.string
};

BaseFancyButton.defaultProps = {
  className: ""
};
```

And styled version of the base component:
```
StyledFancyButton.propTypes = {
  mode: PropTypes.string
};

StyledFancyButton.defaultProps = {
  mode: "primary"
};
```

On prop tables I see only the base props:
![imagen](https://user-images.githubusercontent.com/45243062/67505958-804e9a00-f68c-11e9-989b-c2d15531628d.png)

**Comment by GiladShoham** [comment]
@KoshiroKun 
That indeed looks like a bug.
I'll look into it soon.
If you can provide a full dummy component to make it easier to reproduce it will be great.

**Comment by KoshiroKun** [comment]
Sure, you can check this component: https://bit.dev/ancert/my-test-collection/fancy-button

**Comment by GiladShoham** [comment]
Thanks, I was able to reproduce it.
Looks like react-docgen we use internally are not supporting styled-components out of the box.
see:
https://github.com/reactjs/react-docgen/issues/187
https://github.com/doczjs/docz/issues/156

We will have to dig a bit deeper and see if we can add a strategy for styled-components.
It shouldn't be too hard to add one more strategy since we already have few.
If you want to help us with this by providing a PR, it will be great (let me know and I'll help you set a dev env for this, and point you to the exact place it should be).

**Comment by KoshiroKun** [comment]
Sure, if you can help me I can try to solve it.

**Comment by GiladShoham** [comment]
Great!
First, you should set up a dev environment, it's pretty easy.
Just follow this doc: https://github.com/teambit/bit/blob/master/CONTRIBUTING.md
After finishing, you should have bit-dev or whatever name you called your dev binary.
Make sure you see bit help when running the dev command.
Then you should run `npm run watch` to monitor changes in the dev env.
The relevant workflow start in the `src/jsdoc/parser.ts` under the `parse` function.
You can add some `console.log` there, then run `bit show [component-id]` and make sure it's written to the console.
This piece of code is not very organized (I just started a better way with the Vue parser, but the react parser should be moved to its own file as well).
Feel free to make small refactoring as needed.

Let me know if you need any help.

Thanks a lot!
