### ISSUE TITLE
Suggest using 'bit graph' when facing a toposort build error

### ISSUE THREAD

**Issue by itaymendel** [teambit/bit#2125]
### Description

Sometimes people face the dreaded toposort build issue error:

```
bit failed to build <component> with the following exception:
unable to topological sort dependencies of <component>. Original error: topologicalSortComponentDependencies, <component> is missing
```

The only way of solving it is by deeply understanding the component's dependency graph and change the code. It's kindda hard task :/.

### Describe the solution you'd like

Bit has an awesome command called `bit graph`. We should update the error message to suggest running this command on the component to create an image of the dependency graph and fix the issue.

**Comment by davidfirst** [comment]
@itaymendel , turned out we have two different errors when running the toposort.
1. Cyclic dependencies. 
the error is in fact pretty descriptive: `unable to topological sort dependencies of ${componentId}, it has the following cyclic dependencies\n${circle}`
As you can see, it does print the cycle.

2. Any other error.
`unable to topological sort dependencies of ${componentId}. Original error: ${err.message}`
This is the one you posted, and it doesn't happen due to cycle dependencies. This specific error should not happen, and I'm keeping it open to dig into it later.

**Comment by GiladShoham** [comment]
It might be a bug in the topo code itself.
We should make sure this kind of error (the second one) is sent to sentry.

**Comment by itaymendel** [comment]
irrelevant with v15
