### ISSUE TITLE
importing compiler missing dependencies 

### ISSUE THREAD

**Issue by GiladShoham** [teambit/bit#2132]
### Describe the bug

Using the master to import babel compiler result missing dependencies

### Steps to Reproduce

1. `bit import bit.envs/compilers/babel -c`
1. open `.bit/components/compilers/babel/bit.envs/7.0.3/package.json`
1. there are missing dependencies

master (b663d5bf83ffaedc64b70a42809953d1b6573898) deps:
```
"dependencies": {
    "@babel/plugin-proposal-class-properties": "7.3.4",
    "@babel/plugin-proposal-export-default-from": "^7.2.0",
    "@babel/plugin-proposal-export-namespace-from": "^7.2.0",
    "@babel/preset-env": "^7.3.4"
  },
```
production 
```
"dependencies": {
    "@babel/core": "^7.7.2",
    "@babel/plugin-proposal-class-properties": "7.3.4",
    "@babel/plugin-proposal-export-default-from": "^7.2.0",
    "@babel/plugin-proposal-export-namespace-from": "^7.2.0",
    "@babel/preset-env": "^7.3.4"
  },
```

also, component dependencies like:
`@bit/bit.envs.internal.babel-base-compiler`
aren't exists in the master

### Expected Behavior

Have all the dependencies

### Specifications

- Bit version: master (b663d5bf83ffaedc64b70a42809953d1b6573898)
- Node version: v10.16.0 
- npm / yarn version: 6.11.3
- Platform: darwin
- Bit compiler (include version):  bit.envs/compilers/babel@7.0.3
- Bit tester (include version): none

**Comment by davidfirst** [comment]
The `@babel/core` was missing due to a recent change that disabled the installation of peer-dependencies. This has been fixed in the commit above.

The reason why the Bit dependency is not there is that when installing environments, Bit install the dependencies as components and not as packages. So, the components are saved in `.dependencies` dir and the links are generated to node_modules.
