### ISSUE TITLE
Bit import with path flag is not working well, and with override flag is not working.

### ISSUE THREAD

**Issue by JoshK2** [teambit/bit#2197]
### Describe the bug

I tried to import a component to a specific folder with path flag, like this:
`bit import bit.envs/internal/babel-base-compiler -p packages`
the `packages` folder is not empty, and I expect from Bit to put the folder of the imported component under the `packages` folder. This is the error I get:
![image](https://user-images.githubusercontent.com/35892475/70895122-06d18900-1ff7-11ea-9ca1-b2c1bfd8d005.png)
It will work if I import like this: `bit import bit.envs/internal/babel-base-compiler -p packages/babel-base-compiler`
but I think that is not clear.

So now I tried to import with the path and override flags:
`bit import bit.envs/internal/babel-base-compiler -p packages -o`
this is what I get:
![image](https://user-images.githubusercontent.com/35892475/70895447-a68f1700-1ff7-11ea-9b1b-f37911d2a0f1.png)
but nothing was added to the packages folder and in the .bitmap file.
How to reproduce this bug:

### Steps to Reproduce

1. `mkdir test-bit-import`
2. `cd test-bit-import`
3. `npm init -y`
4. `mkdir packages`
5. `touch packages/index.js`
6. `bit init`
7. `bit import bit.envs/internal/babel-base-compiler -p packages -o`

### Specifications

- Bit version: 14.7.1
- Node version: 8.16.2
- Platform: macOS

**Comment by davidfirst** [comment]
@JoshK2 , I know it's confusing as I did the same mistake in the past :) 
There are two flags: `--objects` with the shortcut `-o` and `--overrides` with the shortcut `-O`, notice that this is an uppercase O.
You entered the lowercase `o`, so it only fetched the objects without writing to the filesystem.

@GiladShoham , @itaymendel , @Tallyb , what do you guys think about this confusion? 
To me, it makes sense to remove the shortcut from one of them or both. Let me know.

Also, what do you think about the first point Josh mentioned. I can see how users would expect the same. Meaning, when using the `--path` flag, they might expect to have a directory with the same name as the component inside the path they entered. (which is not the current behavior. Currently, we create the files on the directory the user entered, which is more flexible, but maybe less intuitive).

**Comment by GiladShoham** [comment]
@davidfirst the -o and -O are indeed confusing. but I'm not sure it's a good enough reason to remove one of them. it's pretty common in CLI tools to have the same latter one lower and one upper for completely different purposes.
Regarding the --path, I talked about this with @JoshK2, and I understand the confusion. I think we should just support {name} in the path. this is actually what we have in the bit.json and it what creates the internal structure. I think users do want the flexibility of defining the exact target dir. we just need to support the {name} (we might already support it), and better document it (maybe even in the bit help for the flag itself.

**Comment by GiladShoham** [comment]
@itaymendel said that since overrides is more common we should switch the aliases between the 2. so the `--overrides` will be `-o` and the `--objects` will be `-O`

**Comment by Tallyb** [comment]
I would not switch for backward sake. 
We should not use capital switches and instead use 2 letters (as in tag --mi --ma).  
Option 1 (backward compatible): --overrides => -r
Option 2 (backward compatible): --overrides => -ov
Option 3 (breaking change): --objects => --fetch / -f, -- overrides => -o

**Comment by davidfirst** [comment]
@GiladShoham , yes, I know it's common and that's why I added them in the first place. However, in this case, it's hard to figure out what happened. Mostly because users are not that familiar with the `--object` flag, so it won't occur to them that they used the wrong flag.

Switching between the flags is dangerous because you can't practically deprecate them, you use them both. Users who don't know about this switch will get `--override` instead of `--objects`, which can delete their files/dirs unintentionally. So, I'd recommend against it.

I'm good with Tally's approach of having 2 letters (we'll need to make sure it works with Commander) or renaming to `fetch`, or simply removing the alias(es), we do it often with flags.

About the `--path`, I agree that this flexibility is important. The suggestion of supporting `{name}` is a good idea and could work. It'll be best to add it to the error message when the directory exists.

**Comment by GiladShoham** [comment]
Commander doesn't support 2 letters aliases, and it's actually not a commander issue but bash issue.
because when using aliases you can chain them for example:
-orb it's the same as -o -r -b. but if you have something that aliased "or"
you don't know what the user meant.
so it's not an option (we can create a new flag with 2 letters that do the same, but it will be a different flag, it will have its own line in help, and it's own var in the code).

I'm fine with changing the alias to something else like -r it doesn't really matter. I'm also fine with removing the `--objects` alias.

@itaymendel your opinion?
