### ISSUE TITLE
'required' prop-types are not recognized by bit when also using jsDoc

### ISSUE THREAD

**Issue by odedre** [teambit/bit#2202]
I have a react component that uses `prop-types`.
the `isRequired` param on a prop doesnt show in bit.

I have this following code:
```
Button.propTypes = {
  /**
   * @property {[propTypes.string]} text - Button text.
   */
  text: PropTypes.string.isRequired,
  /**
   * @property {propTypes.string} buttonHoverColor - Button color to be shown on hover.
   */
  buttonHoverColor: PropTypes.string.isRequired,
  /**
   * @property {propTypes.string} buttonColor- Button default background color.
   */
  buttonColor: PropTypes.string
}
```
when I run `bit show`, bit shows the prop as `required: false`

![Screen Shot 2019-12-15 at 5 36 51 PM](https://user-images.githubusercontent.com/15064762/71008680-affcaa00-20f1-11ea-8272-a8b3fdb1c90b.png)

- Bit version: 14.7.1
- Node version: v10.15.3
- yarn version: 1.13.0
- Platform: macos

**Comment by davidfirst** [comment]
@odedre , I remember having a similar issue opened in the past and it turned out that if you have defaultValue set, it can't be required. It seems to be the same here. You have a default value on `text` and `buttonHoverColor`, so there is no meaning for the `required` here.

Please re-open if you think it's a bug.
