### ISSUE TITLE
After bit build, bit link points to source code instead of the dist

### ISSUE THREAD

**Issue by odedre** [teambit/bit#2205]
### Describe the bug

I created a component and ran `bit add` and `bit build`.
after I changed the import link to point to the `@bit` component in the `node_modules`, it was pointing to the source code instead of the `dist`.

- Bit version: 14.7.1
- Node version: v10.15.3
- yarn version: 1.13.0
- Platform: macos
- Bit compiler (include version): bit.envs/compilers/react-typescript@3.1.23

**Comment by davidfirst** [comment]
After some research, here is what happens:
When author builds a component, Bit generates files in node_modules that link to the dists. For example: for a file `bar/foo.js`, Bit generates a file `node_modules/bar/foo.js` that requires `dist/bar/foo.js`.
The idea is that a user could use module path (`require(@bit/my-component)`) rather than relative path (`require('../foo')`).
The way how these links are generated is that Bit searches the dists files for the same files of the source (e.g. for "bar/foo.js" Bit searches "dist/bar/foo.js" ). 
The problem with the typescript compiler is that it doesn't preserve the source structure when creating the dists. Instead of having `dist/bar/foo.js`, it has `dist/foo.js`. (which obviously has other issues, such as overriding by other files with the same name).
I remember discussing this in the past, not sure what was the conclusion. 
@giladshoham, @qballer.

**Comment by GiladShoham** [comment]
The conclusion was that in order to support it correctly for compilers that change the structure, we should get a mapping from the compiler that maps src file to dist file.
So it requires changes both in bit and the ts compiler.

**Comment by itaymendel** [comment]
fixed for v15
