### ISSUE TITLE
Support Platform-specific extensions in ReactNative

### ISSUE THREAD

**Issue by JoshK2** [teambit/bit#2215]
### Description

I working on a few ReactNative projects, and I see that Bit is not supporting [platform specific code](https://facebook.github.io/react-native/docs/platform-specific-code#platform-specific-extensions).

### Steps to Reproduce
1. `git clone git@github.com:shoutem/ui.git`
1. `git checkout tags/v1.0.1`
1. `yarn`
1.  Run bit commands to tag all the components:
```
bit init
bit add components/*
bit add assets/images/transparent.png -n assets/images
bit add helpers/device-selector.js -n helpers
bit add const.js
 ```
1. Now you can run `bit status` and see the `non-existing dependency files` error.

### Additional context

![image](https://user-images.githubusercontent.com/35892475/71416122-d37ea200-2667-11ea-94ab-bfa03abae075.png)
![image](https://user-images.githubusercontent.com/35892475/71416384-cada9b80-2668-11ea-97e2-8dba4e1ff87a.png)

### Specifications

Bit version: 14.7.1
Node version: 8.16.2
Platform: macOS

**Comment by GiladShoham** [comment]
This is not a simple case, we should know when running the detectors that it's a react-native workspace.
That requires:
1. having a react-native detector that knows to handle such requires.
2. detect that this is a react native workspace by bit.
3. pass the detection by bit to the detectors down the chain.

it's not easy but probably required in order to really support this.

**Comment by oxyii** [comment]
`react-native` [Metro bundler](https://github.com/facebook/metro) does not require any building at all. We can work well with JSX node_modules. As [I said](https://github.com/teambit/envs/issues/69#issuecomment-569627168) the only we need is including **all** matched extensions. And it can be not only `ios` and `android`... Additional cases is [react-native-web](https://github.com/necolas/react-native-web) or [react-native-desktop](https://github.com/status-im/react-native-desktop) or Microsoft [react-native-windows](https://github.com/microsoft/react-native-windows). I can't say **all** possible extensions but it can be `*.web.js`, `*.desktop.js`, `*.native.js` and more and more and more... I think it can be useful for configuring extensions... somehow...
P.S. Sorry for my english

**Comment by oxyii** [comment]
@GiladShoham sorry, I forgot to explain something: Metro bundler (after optional JSX transformation) begins to resolve all `import` and `require` **for platform** (ios or android). It mean that `*.android.js` files will **never** be included into ios bundle. Each optional case works with its own bundler. Eg `react-native-web` works with Webpack instead of Metro (transform back react-native app to pure React app). And he will never include ios or android specific files.
```
index.js <- export { default } from './Component'
Component.android.js <- used by Metro for android only
Component.native.js <- used by Metro for ios because no *.ios.js file
Component.web.js <- used by Webpack for RNWeb build
Component.js <- all others app supported platforms, eg RNDesktop
```
That is why we need all files.

**Comment by GiladShoham** [comment]
@oxyii Thanks for the info.
In order to solve this issue we need bit to reconginze such requires, and warn you if they are not part of the component (as opposed to the current state, that bit warn you even if they are added since he deosn't recgnoize it)
then we might need to build a metro compiler, but it's a different task (the metro task should be handled in the [envs](https://github.com/teambit/envs) repo), and should probably be depended on this task of bit support.

**Comment by oxyii** [comment]
@GiladShoham I'm not sure that Metro bundler is required for bit... Just JSX transform for all platform specific files. Bundling - is not a bit business. In my RN components I'm using Babel only for building. https://github.com/oxyii/react-native-web-swiper/blob/master/babel.config.js

**Comment by GiladShoham** [comment]
@oxyii Thanks for the clarification. 
@davidfirst Can you write your opinion about it?

**Comment by davidfirst** [comment]
So, without digging into this world of platform-specific. Just to make sure I understand. We're talking about dependencies that are not recognized because there are no import/require of them explicitly in the code. Correct? 
If that's the case, for now, as a workaround, they can be added using the `overrides` feature of files. 
@GiladShoham , am I right?

**Comment by oxyii** [comment]
@davidfirst we must import all files matching each "import"
```jsx
import Component from './Component'
```
must import **all** files: and `Component.js` and `Component.ios.js` and all of the above. I'm not sure that `override` can do it. As I understand `override` can change one file with another **one**. I'm right?

**Comment by davidfirst** [comment]
@oxyii , sorry I was confused before. The file protocol of `overrides` only allows removing file dependencies but not adding.
A question, is this should be a feature of `bit add`? meaning, if you add your `component.js`, you want also `component.ios.js` to be added to the same component? or do you want it to be a dependency?

**Comment by oxyii** [comment]
@davidfirst One `import` directive must include all matched files. Look:
1. I create a component called `View`. This component is the same for all platforms but not for ios. Result: my component maked twice: `View.js` for all platforms and `View.ios.js` for ios.
2. I publish this component, somehow trying to use it. He write `import View from './View'`
3. App developer trying to make bundles for android and for ios, This step doing twice - per platform.
4. Facebook's Metro bundler will take `View.js` for android and `View.ios.js` for ios.

**Comment by oxyii** [comment]
@davidfirst I make a little example for you: https://snack.expo.io/@oxyii/bit.dev:-platform-specific-code See `Link` component.

**Comment by davidfirst** [comment]
@oxyii , thanks for the example. 
So, here is the first challenge here: in your example, you have this line in "components/List/index.js":
`export default from './Link';`
javascript compiler has no idea what is it this `./Link`. There is no file `Link.js` or `Link/index.js` inside `components/List/`. That's why when you run `bit status` Bit complains about missing dependencies.
In order to solve it, Bit needs to parse the file with this react-native compiler. 
That's basically what Gilad explained before. Do you agree with it, or you see another option to solve it?

**Comment by oxyii** [comment]
@davidfirst Okay, it (may be) can solve `*.ios.js`, `*.android.js` and `*.native.js` but not `*.web.js`, `*.windows.js`, `*.desktop.js` and others.. Metro Bundler (compiler) used for android and ios only.
I did not look at the bit sources and I don't know how bit resolves imports and requires. So I have no idea how to solve it. At the moment I just hope that you at least understand the problem in full )))

**Comment by oxyii** [comment]
@davidfirst Hmmm.... Can we skip require checks at all for react-native env? Let's do JSX transforms only for all `*.js` in folder! I know that this is very bad way but it really can helps...

**Comment by davidfirst** [comment]
@oxyii , oh I see what you're saying. so, react-native alone won't help to cover all cases. 

The way how Bit finds dependencies is very similar to how [Madge](https://github.com/pahen/madge) does it. 
You can basically tag with `--ignore-missing-dependencies`, but then you miss the dependencies resolution for other files. 
We'll probably need to dig into react-native and the Metro Bundler you mentioned to understand how they resolve the files.

**Comment by oxyii** [comment]
anyway, for component we must include **all** possible files in react-native env. If you still planning to use Metro somehow.... I'm not sure that it will helps. Because Metro can resolve only one file relative to **app build config** (platform). It cannot be done before app building (bundling for platform). Many RN component providers use this behavior... For example - react-native him-self. Just checkbox: https://github.com/facebook/react-native/tree/master/Libraries/Components/CheckBox

**Comment by oxyii** [comment]
Let's start from beginning again: I am component developer. I wrote component called `Link` and I trying to publish component into bit. Anybody (let's call him Mike) is app developer and he trying to use my `Link` in app. His app is cross-platform, so he write single code for all platforms then he build app for each platform.
1. **web** `react-scripts build` will work fine for web-platform. React built-in Webpack config [already supported](https://github.com/facebook/create-react-app/blob/4bf14fa665e748af7de41addb008e0eee39905da/packages/react-scripts/config/webpack.config.js#L311) RNWeb. Here `Link.web.js` will be included.
2. **iOS** `react-native run-ios` Here `Link.ios.js` will be included
3. **Android** `react-native run-android` - Here `Link.android.js` will be included

But this is already Mike's **app build**. My component already packed, published and included into app. So in my component must be all platform-specific files. And not only! See [my comment](https://github.com/teambit/bit/issues/2215#issuecomment-569820319)

**Comment by GiladShoham** [comment]
@oxyii You can already as the component writer can add all the required files. and they will be available to your consumer.
@davidfirst The issues are:
1. in case you have `import Component from './Component'`
and the files:
```
Component.android.js <- used by Metro for android only
Component.native.js <- used by Metro for ios because of no *.ios.js file
Component.web.js <- used by Webpack for RNWeb build
```
(no `Component.js` files)
Bit will say you have a missing required file, which is not true since it's a valid use case as I understand. @oxyii correct me if I'm wrong here).
2. in the case above bit should know to create link files for all the platform-specific files. 
3. The compiler might need to know how to compile the different files (maybe he should just ignore them and leave them as is) anyway, this is a compiler responsibility and we will get there once bit will have the required support.
4. we might need to show a warning in case you tracked one of the platform files, but not the others, that warn you that you might be missing required files (we can't really distinct if you want to share them all or not, so we can't block in such case).

**Comment by oxyii** [comment]
> You can already as the component writer can add all the required files. and they will be available to your consumer.

and how can i do this? As I understand, bit ignores files that not `import`ed and not `require`d. Or I'm wrong?

**Comment by davidfirst** [comment]
> and how can i do this? As I understand, bit ignores files that not imported and not required. Or I'm wrong?

@oxyii , what Gilad is saying is that when you add the component, you can add more files to the component. In your example above, if you add the directory `Link`, it also adds all the files, include *.web.js and *.ios.js.

**Comment by itaymendel** [comment]
this is no longer relevant for bit v15.

We'll start rolling out v15 of Bit this week, please reach out to me privately on the [public slack community](https://join.slack.com/t/bit-dev-community/shared_invite/zt-9egg85xv-trr_QBkWr1XcVgtrgCvtfQ) for a sneak peek and getting early access to it.
