### ISSUE TITLE
cant add a component which files are already tracked by another component

### ISSUE THREAD

**Issue by odedre** [teambit/bit#2241]
### Description

I added component A, with all its files and then added another component (component B) that was actually included in component A, bit gives an error:

```
warning: files already used by component: [component A]
could not track component [component B]: no files to track
```

### Describe the solution you'd like

bit should make B into a component and replace the relevant files in A with a dependency on component B.

### Describe alternatives you've considered

what I did to resolve this is to untrack A, then add B and then add A again.

**Comment by Tallyb** [comment]
@odedre  - I do not think Bit should automatically track components. Your resolution is the correct one.

**Comment by GiladShoham** [comment]
@Tallyb It's not automatically, it's manual.
@odedre describes a case when he has a big component (a) and wants to move some of its files to a dedicated component (b). instead of untrack a, track b and track a left overs, he want bit to do the sugar when he track b. 
I think bit should suggest and confirm that you want to split them, but let you do this.
it's just sugar for the untrack, track b and track a.

**Comment by itaymendel** [comment]
irrelevant, as we move to a more rigid structure where a component is a dir
