### ISSUE TITLE
bit cant resolve a relative import to a css file although it added it as a dependency of the component

### ISSUE THREAD

**Issue by odedre** [teambit/bit#2252]
### Describe the bug

I have a css theme imported in a js file like so:

```js
import avatarColors from '../../theme/avatar-colors.module.scss';
```
bit recognized the file as a dependency but couldn't resolve the relative import in the code.

see the component here:
https://bit.dev/bit/web/components/avatar

### Expected Behavior

bit should resolve the import statement and point it to the component dependency.

### Specifications

- Bit version: 14.7.2
- Node version: v10.15.3
- yarn version: 1.13.0
- Platform: macos
- Bit compiler (include version): bit.web/compilers/react-flow@0.0.5

**Comment by davidfirst** [comment]
@odedre , I'm trying to debug the issue, and I guess I'll need your help here.
According to the component-object, this dependency `themes/avatar-colors` was required in `components/avatar` component by the following import path:
`~theme/avatar-colors.module.scss`
However, when I check the code now, I see a different path: `../../theme/avatar-colors.module.scss`. Do you remember if you changed the path at some point? 

By the way, if you change it now to be with the Tilad, it does recognize it correctly. that's because the links Bit generated were according to the custom-module-path with the Tilda.

**Comment by odedre** [comment]
I worked around it. you can look at a previous version of the component. see here:
https://bit.dev/bit/web/components/avatar/~code?version=0.0.8#components/Avatar/default-avatar.js

I think a part of the problem is that we have an import from the .scss file (with ~), and an import from the .js file (using a relative path). see here:

https://bit.dev/bit/web/components/avatar/~code?version=0.0.8#components/Avatar/styles.module.scss
https://bit.dev/bit/web/components/avatar/~code?version=0.0.8#components/Avatar/default-avatar.js

**Comment by davidfirst** [comment]
@odedre , thanks, that can explain the issue!
I'll take a look into this later this week.

**Comment by itaymendel** [comment]
moving away from relative imports.
