### ISSUE TITLE
Components are not linked correctly

### ISSUE THREAD

**Issue by Tallyb** [teambit/bit#2264]
### Describe the bug
When creating the components above. The utils are not being linked to the compiler component and building the vue-compiler component fails 
```
utilsindex.ts:16:8 - error TS2307: Cannot find module './utils'.

16 } from './utils';
          ~~~~~~~~~
```

### Steps to Reproduce

1. clone the repo https://github.com/Tallyb/vue-compiler/tree/bit-bug (tag is bit-bug). 
1. Build the components

### Expected Behavior
Build should succeed.

### Specifications

- Bit version:  14.7.2
- Node version: 12.14.1
- npm / yarn version: 6.13.6
- Platform: MACOS Catlina
- Bit compiler (include version): bit.envs/compilers/typescript@3.1.36
- Bit tester (include version): N/A

**Comment by davidfirst** [comment]
@Tallyb , which component caused the error?
I see two directories. Tried both.
**workspace** => got a different error `Error: the file /tmp/vue-compiler/compiler/dist/index.js not found`
**compiler** => got a different error `Cannot read property 'split' of undefined`.

**Comment by Tallyb** [comment]
@davidfirst  - building the compiler itself (in the compiler directory).

**Comment by davidfirst** [comment]
Fixed.

A quick explanation of what was the issue.
When Bit generates link files, it first makes sure to not override existing files. Here, Bit incorrectly assumed that the link file, is `index.ts` instead of `utils/index.ts` (`file.relative` was used instead of `file.path`), because the file `index.ts` already exists, it ignores it and didn't create the link file.
