### ISSUE TITLE
bit doesnt recognize a css dependency when required via aliases

### ISSUE THREAD

**Issue by odedre** [teambit/bit#2307]
### Describe the bug

I have a [component](https://bit.dev/bit/web/components/comment-carousel) that imports a css module defined and imported using webpack aliases. The aliases are defined in the `package.json` of the author env like so:
```
// package.json
"bit": {
    "resolveModules": {
      "aliases": {
        "~theme": "src/theme",
        ...
        }

```
when I install the component in a different project I get the following error:
```
./node_modules/@bit/bit.web.components.comment-carousel/dist/src/components/comment-carousel/carousel.module.scss (./node_modules/css-loader/dist/cjs.js??ref--6-oneOf-6-1!./node_modules/postcss-loader/src??postcss!./node_modules/resolve-url-loader??ref--6-oneOf-6-3!./node_modules/sass-loader/dist/cjs.js??ref--6-oneOf-6-4!./node_modules/@bit/bit.web.components.comment-carousel/dist/src/components/comment-carousel/carousel.module.scss)
SassError: File to import not found or unreadable: ~theme/sizes.module.scss.
        on line 1 of /Users/oded/code/base-components/node_modules/@bit/bit.web.components.comment-carousel/dist/src/components/comment-carousel/carousel.module.scss
>> @import '~theme/sizes.module.scss';
```
I can see the `theme/sizes.module.scss` file in the dist folder of the installed component and the `package.json` has the following bit object:
```
"bit": {
    "env": {
      "compiler": "bit.web/compilers/react-flow@0.0.5"
    },
    "resolveAliases": {
      "~theme/sizes.module.scss": "@bit/bit.web.themes.sizes/sizes.module.scss"
    }
  },
```

### Expected Behavior

bit should link the dependency to the component 

### Specifications

- Bit version: 14.7.2
- Node version: v10.15.3
- yarn version: 1.13.0
- Platform: macos
- Bit compiler (include version):
    - the consuming env: bit.envs/compilers/react-typescript@3.1.43
    - the components author env: bit.web/compilers/react-flow@0.0.5

**Comment by odedre** [comment]
the way I resolved the issue is to replace the problematic scss import `@import '~theme/sizes.module.scss'` with the import to the bit component (along with the `~`) : `@import '~@bit/bit.web.themes.sizes'`.
I then exported the component from the author env and  installed the update in the consuming env.

Is there a better way to resolve this issue?

**Comment by GiladShoham** [comment]
@odedre Thanks for this.
This indeed a bug, happens probably because you have an alias with `~` and the created link should be created with a `~` as well. probably there is some conflict there in the link generation.

Just a few more notes:
1. In case the dependency is not yet exported, you have to make sure to [add default scope](https://docs.bit.dev/docs/conf-bit-json.html#defaultscope) prior to the `bit link` command, to make sure you will have a link in the node_modules.
(you can even add it on the overrides section if you want a specific scope for the styling components)
2. We really encourage users to move to the `@bit` way for creating modules paths instead of using the aliases feature (we consider dropping support for aliased later) it's much safer and stable. 
Therefore we might not fix this issue soon.

**Comment by itaymendel** [comment]
removed aliases from v15

We'll start rolling out v15 of Bit this week, please reach out to me privately on the [public slack community](https://join.slack.com/t/bit-dev-community/shared_invite/zt-9egg85xv-trr_QBkWr1XcVgtrgCvtfQ) for a sneak peek and getting early access to it.
