### ISSUE TITLE
Module has no exported member on dependency

### ISSUE THREAD

**Issue by johanrg** [teambit/bit#2381]
This seems similar to #1947. Though it's obviously of a different character since the fix doesn't help here.

The components is built on an Angular 9 project that we started a few weeks ago.
The repo has been made public and is located here: https://github.com/JobMatchTalent/components

### Describe the bug

The project has 15 components and all of them except one builds just fine. The one that doesn't work is called datepicker. It fails on several dependencies with the "has no exported member" error. I early on suspected the scss in the project since it was a bit messy and we had started experimenting with the new @use for importing, it built just fine with ng cli but would break if we used it on the components when building with bit. This is the current state of the repo on the main branch.

So the first step I tried here was just to clean up the scss in the project and reverting back to @import for now, @use might be too soon to use anyway. But this did not help either in the end. I did a new branch out of this called "investigation".

Since the error messages when building is lacking to put it mildy I started experimenting with different scenarios, nothing worked, including typescript path aliases with mixed results but in the end still failed. Then I started cutting code trying to get it to build and finally succeeded, after removing a bunch of css and a dependency to a component we call svg-icon on the button component. This is in the branch "buildsAll".

### Steps to Reproduce
1.
```
bit init --reset-hard
```
2.
```
bit add src/app/components/button --main src/app/components/button/button.module.ts --exclude "src/app/components/button/*.spec.ts"
bit add src/app/components/core --id core
bit add src/app/components/datepicker --main src/app/components/datepicker/datepicker.module.ts --exclude "src/app/components/datepicker/*.spec.ts"
bit add src/app/components/dialog --main src/app/components/dialog/dialog.module.ts --exclude "src/app/components/dialog/*.spec.ts"
bit add src/app/components/form-field --main src/app/components/form-field/form-field.module.ts --exclude "src/app/components/form-field/*.spec.ts"
bit add src/app/components/input --main src/app/components/input/input.module.ts --exclude "src/app/components/input/*.spec.ts"
bit add src/app/components/svg-icon --main src/app/components/svg-icon/svg-icon.module.ts --exclude "src/app/components/svg-icon/*.spec.ts"
```
3. bit status gives all ok

4. bit tag --all

This gives the error:
```
Command failed: node /Users/johan/projects/components/.git/bit/components/compilers/angular/bit.envs/0.2.0/node_modules/ng-packagr/cli/main.js -p ng-package.json -c tsconfig.json
ERROR: button/index.ts(1,10): error TS2305: Module '"../../../../T/bit/capsule-23197/node_modules/@bit/button/dist/button/bit-button"' has no exported member 'JmButtonComponent'.
dialog/index.ts(3,10): error TS2305: Module '"../../../../T/bit/capsule-23197/node_modules/@bit/dialog/dist/dialog/bit-dialog"' has no exported member 'JmDialog'.
dialog/index.ts(5,10): error TS2305: Module '"../../../../T/bit/capsule-23197/node_modules/@bit/dialog/dist/dialog/bit-dialog"' has no exported member 'JmDialogRef'.


Building Angular Package

------------------------------------------------------------------------------
Building entry point '@bit/datepicker'
------------------------------------------------------------------------------
Compiling TypeScript sources through ngc
```

Doing the same steps on the buildsAll branch succeeds because of the cut code, by why this is the case I have not been able to solve.

### Specifications

- Bit version: 12.7.4
- Node version: 12.16.1
- npm / yarn version: npm 6.13.4
- Platform: MacOs
- Bit compiler (include version): Angular 0.2.0
- Bit tester (include version): -

Thankful for any help solving this problem.

**Comment by itaymendel** [comment]
It's a shot in the dark, as my experience with Angualr is rather limited, but from the looks of it there seems to be a mixup of the exported module and component.

All components can `tag` properly, the issues are only with the `datepicker` component.
In one example, I found that you import `JmButtonComponent`, while the ngModule exports `JmButtonModule`. When I fixed it, the first issue was resolved.

It's important to understand that due to the strcuture of Angular, you must use the ngModule, not ngComponent, even when tracking components. From the looks of it there's a little more modificaitons to do to fix the import issues of `JmDialog` and `JmDialogRef`.

[There's more on it in the docs](https://docs.bit.dev/docs/angular-guidelines#export-bit-components-as-ngmodules).

**Comment by johanrg** [comment]
The JmButtonComponent is declared and exported in the JmButtonModule and the datepicker is importing that module. In the case of the import of the JmButtonComponent directly, the datepicker-toggle keeps track of this button in it's template through @ViewChild and need to import the actual component to get it's type. How did you solve this problem without just removing the @ViewChild? The datepicker need access to the component directly somehow. Is this not possible at all?

Thank you for the response.

**Comment by itaymendel** [comment]
After spending much more time on the issue, it seems that the problem is with the Angular compiler.

We have done little testing for Angular 9 with the current compiler. Internally we use ng-packagr, and it seems that there are some Ivy-related changes that are needed to get it to work. I also take back my previous comment, as it seems that none of the components is built correctly.

Sadly understanding the internals of Angular and figure how to fit it to the isolated component environment in Bit requires fiddling around with the internals of how ng-package (and now Ivy) do things, so it might take time to get it to work.
Right now our focus is finishing up the work in #2281 to improve the development experience of integrating tools to Bit and solve these kinds of issues from the root.

**Comment by johanrg** [comment]
Thank you for investigating the problem. I thought I was going crazy over here with the random errors I was seeing.

This is a damn shame, we have wasted a lot of time on this and I'm not blaming you guys for it. The Angular team has a nasty habit of introducing breaking changes. A good tip might be to just use Angulars now built in library support instead of using ng-packagr directly. But that's just a thought.

In the mean time we'll have to figure out how we are going to solve this problem internally. None the less, thank you for your support.

**Comment by itaymendel** [comment]
I'm terribly sorry about it. I will make sure we update our docs with the note about Angular 9 support.
