### ISSUE TITLE
`export ns from...` fails

### ISSUE THREAD

**Issue by seed-of-apricot** [teambit/bit#2481]
### Description

The compiler cannot handle the direct export of a namespace as a named export.

```ts
export * as namespace from './namespace';
```

```node
> folder1/folder2 ...  issues found
  error found while parsing the file (please edit the file and fix the parsing error): 
     src/folder1/folder2/index.ts -> 'from' expected.
```

### Specifications

- Bit version: 14.7.6
- Node version: 13.7.0
- npm / yarn version: 6.13.6
- Platform: Windows
- Bit compiler (include version): typescript@3.1.40
- Bit tester (include version): none

### Context and additional information

Is this by design?

**Comment by JoshK2** [comment]
Hi @seed-of-apricot 
It seems to be a problem with the TS version we use in bit, the export syntax you use is supported in TS version 3.8 and higher:
https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-8.html

And we use TypeScript version 3.7.* 
@GiladShoham

**Comment by seed-of-apricot** [comment]
@JoshK2 Understood. Then I will make them import and export for now. Is the update coming soon?

**Comment by rgamm** [comment]
Hi, I've also bumped up against this issue using 3.8 syntax `export type {..}`. I'm using a custom compiler with TS v3.8 however, and running bit build <component> works with no issues.

I saw in another issue (https://github.com/teambit/bit/issues/2344) that `--force` flag on tagging is not possible because build would fail... but in my case it wouldn't! This feels like a bit of a bug to be tied down to `bit`s typescript version, is there any way around this?

**Comment by davidfirst** [comment]
The PR of updating typescript to 3.8 was merged a few days ago.
@GiladShoham , any idea when it'll be released?

**Comment by GiladShoham** [comment]
I don't know yet, I'll try to make it soon

**Comment by GiladShoham** [comment]
Already solved on master. should be fine after the next release (14.7.7 and above)

**Comment by seed-of-apricot** [comment]
Great! Thank you for your cooperation.
