### ISSUE TITLE
IDE error file is not a module 

### ISSUE THREAD

**Issue by Tallyb** [teambit/bit#2514]
### Describe the bug

Getting Error in the IDE that a file is not a module
File '/tools/node_modules/@bit/bit.envs-dev.compilers.utils/src/utils/index.ts' is not a module.ts(2306)

The utils component was exported, but trying to reference it from other components/directories shows this error. 

### Steps to Reproduce

1. clone the repo https://github.com/teambit/tools/tree/not-a-module (tag: not a module)
1. npm install
1. `bit import` and `bit link`
1. Open the vile in src/vue/index.ts - you will get the error of file is not a module

### Expected Behavior

The module should be identified

### Specifications

- Bit version: 14.7.6
- Node version: v12.16.1
- npm / yarn version: 6.14.4
- Platform: MacOS Catalina
- Bit compiler (include version): bit.envs/compilers/typescript@3.1.40
- Bit tester (include version):

**Comment by krislao** [comment]
@Tallyb encountering this issue also. im using react-typescript project setup. is there a resolution for this?
i noticed that the `index.ts` file is in `module.exports` format. maybe that's why TS is not detecting it as a module? it's also weird that `index.ts` file has this format. other files are in ES6 export format.
