### ISSUE TITLE
option to ignore dependencies

### ISSUE THREAD

**Issue by KutnerUri** [teambit/bit#2534]
When tracking a component, users may want to ignore certain imports.
For example, in css files, we may support `url-loader`:

```css
background-image: url('/public/assets/emptyOwnerIllustration.png');
```

Depending on the project, this could be a different component, or an actual relative link to be interpreted by the browser.
Users will probably want Bit to handle this, but not always.

We should give them an option to opt out of dep detection, in all file types.

I think TS has a pretty nice syntax for this:

(skips next line)

```
//@bit-ignore
```

(ignores entire file)

```
//@bit-no-check
```

**Comment by davidfirst** [comment]
Currently, you can achieve a similar experience using the `overrides` with `file` protocol.
From the docs:
```
"overrides": {
    "comp1": {
        "dependencies": {
            "file://utils/*": "-"
        }
    }
}
```

However, this syntax is going to be deprecated in Harmony. Mostly because the plus sign doesn't play nice with the share-dir. If this is a popular use-case we should consider not deprecating the file protocol if used with minus.

**Comment by KutnerUri** [comment]
OK.
Ran suggested this could be a nice feature, and wanted me to open a feature request for it. :)

**Comment by davidfirst** [comment]
Implemented in the PR above.
