### ISSUE TITLE
Harmony: ink, raw mode and command output

### ISSUE THREAD

**Issue by ranm8** [teambit/bit#2544]
First, I think this is a very important discussion we are making and I would like to thank @qballer and @imsnif who both contribute a lot amazing insights to the discussion.

It seems that different commands might have different UX needs and while some of them can highly benefit from interactivity but might result in a major UX issues for others. 

We will add this up to the list of important things to consider when designing a new CLI command.

Few examples I had in mind regarding our near term roadmap:
- **install**. As @imsnif pointed out, seems like we would be able to achieve the right UX without using raw mode.
- **new** @itaymendel wrote [`new` spec](https://github.com/teambit/bit/issues/2509) here. New will have all modes implemented to provide a UX for creating your workspace. Including interactive choices between frameworks, compilers, testers, linters, etc. 
- **flows** @qballer flows might be better off without interactive mode. I believe @imsnif reporter might be easier to implement and will provide a better UX for the flows command for now.
- **watch** will have all three implantations.
- **start**  will have all three implantations.
- **export** @itaymendel added an [interactive flow for export here](https://github.com/teambit/bit/issues/2507). `export` will support all three implantations as well.
- most existing commands will preserve the same logic and we might add optional interactive flows to 
some of them in the future. 

## API
After having a discussion with both @qballer and @imsnif I came up with the following API for commands registered to the `CLI` extension:

```ts
@Extension()
export class BaseCompiler {
  @subscribe(CLI, 'commands')
  command() {
    return {
      synopsis: 'compile <id>',

      report: (reporter) => {
        return 'Hello world!';
      }
      
      render: (reporter) => {
        return <Text>Hello world!</Text>;
      }
      
      json: (reporter) {
        return {text: "Hello world!" };
      }
    };
  }
}
```

### Logger extension
Logger extension will standardize the API for reporting progress, errors, info and other needs we would have. @GiladShoham @imsnif  can we connect the legacy logger to this as well? I think we should create a reference another issue to decide on the Logger API and integration to the legacy one and finalize its API accordingly.

### Reporter
Separate presentation and API layers. Each interactive command would also get a reporter instance and decide how to display it. More complex outputs from APIs can be achieved through API from the specific extension.

Things to think about looking on the reporter design:
- How can I control which extensions are allowed to be printed to console in my command? @imsnif we need to think of a design for this. 
- How to override the default reporter? (e.g. loader)
- How to decide whether to show a progress bar or not?

@imsnif has pointed out that it might be a bad idea to allow users to replace the entire reporter and I tend to agree.
We must not get to the point in which `Scope` extension is somehow responsible for log indentations and formatting.

### JSON reporter
We will implement a default JSON reporter which will apply on all commands by default, user would be able to override this reporter with his own JSON reporter. 

### Defaults
We should trigger interactive by default for local environments if exists and report by default for automated environments e.g. (e.g. CI)
I believe when `process.stdout.isTTY` equals true we are showing interactive by default. Otherwise, we will invoke the report method. Let me know if you think this rule is sufficient and covers all cases. 

Feedbacks are welcome. @qballer @imsnif I think we should standardize and align our APIs accordingly early next week as we are moving more focus towards outputs in flows, compile and possibly watch/start.

**Comment by imsnif** [comment]
Great summary!
So, just briefly responding to a couple of points:

The `process.stdout.isTTY` solution sounds great for differentiating the modes.

In commands that support interactive mode, it's important not to leave lines on the screen whose overflow/scrolling is not "controlled" by the terminal. Otherwise they will not reflow if the user expands their terminal window, and it would look bad. So (for example) if we're talking about `bit new` being interactive, it's important to delete all the interactive lines before exiting back to the shell and maybe print a more terminal-friendly report of what has been done. IMO it would be better and simpler to have a non-raw-mode interactive experience for this particular command, but if that is not desired, I think we should at least handle it properly.

**Comment by qballer** [comment]
>* flows @qballer flows might be better off without interactive mode. I believe @imsnif reporter might be easier to implement and will provide a better UX for the flows command for now.
watch will have all three implantations.

I agree with this, rawMode breaks user expectation in commands, @imsnif actually came up with a proper rule of thumb. If the command is more app like  -> watch,start it can be interactive. if it starts and ends it should be more inclined to work well with terminal composition (compile,test, run status...)

**Comment by GiladShoham** [comment]
notes:
1. we should define the relationship between report to the terminal and report to the log files.
2. we should define how a user that runs a command set the mode command will run (json / render / report) and how we determine the default
3. we should distinguish between interactive printing (raw mode) and interactive questions that accept a user feedback along the process and define its relationship as well.
4. I see in the example above that we get a reporter in any function, what is this reporter API
5. we should define a way for the user to set the log level he wants
6. It will be really nice to have the ability to define different log level for different extensions

**Comment by imsnif** [comment]
After discussing this issue at length with @qballer and @ranm8, we came up with the following plan (@qballer, please correct me if I'm wrong or missed anything):

All extensions that want to log in real time will get an instance of the Logger extension. The Logger will be used to send messages to the Reporter extension, which will be in charge of displaying them on screen.

The Logger will keep track of the extension name, as well as the component ID to which the log belongs to. The former in order to allow querying what has been completed and what hasn't, and the latter in order to assign outputs to their right place (the Reporter for example uses the latter in order to color-code messages).

The Reporter instance will be given to each CLI command using the API demonstrated in the issue description. It will be the command's responsibility to subscribe to messages on the logger and send them to the reporter. The Reporter will also be in charge of the status line (with the loader and phase description). It will have an API for adjusting the status line, displaying more information in it and removing certain parts of it as needed.

**Comment by qballer** [comment]
Current task list for this issue after discussion with @imsnif 

- [ ] extend logger to hold a store of logs supporting - Phase, Extension, Component.
- [ ] consume logger in debug.log
- [ ] extend bit CLI to hold new interface. 
- [ ] Create configurable reporter. 
- [ ] Reporter should query the log and present to screen.
- [ ] implement default json mode in cli.
- [ ] implement install output.
- [ ] implement flows output.

**Comment by davidfirst** [comment]
@qballer , can you please describe briefly about the status of this task? should we close it?

**Comment by davidfirst** [comment]
@ranm8 , @GiladShoham , I have read all comments here and went through the code of both: logger and reporter, and there is still a missing piece in the design. 
In order for the reporter to show log messages, it needs to register to the logger with the extension-id. However, in many cases, it doesn't know about them.
Here is a practical example: Builder extension wants to show in the terminal logs from typescript/jest. The builder is not aware (and should not be aware) of typescript/jest extensions, so it couldn't register. 

I wasn't part of most of the discussions about logger/reporter. I took the simplest approach as you can see [here](https://github.com/teambit/bit/compare/harmony/builder-report?expand=1). (I didn't create a PR yet). Every extension registred to the logger is saved in the logger class (`logger.subscribers: string[]`). The logger class exposes a new method: `subscribeAll()` so then, the reporter can register to all extensions and get log from all of them.

In Builder, that's all I need. I expose `verbose` flag. If it's enabled, I show all log messages, from everywhere, including from the package-manager. 
Are you ok with this approach?
Also, it wasn't implemented yet, but we still want the `reporter` to be passed to all commands, right?
