### ISSUE TITLE
Suggested way to combine bit components

### ISSUE THREAD

**Issue by makeupsomething** [teambit/bit#2625]
### Description

I want to combine several of my components from my project into one new component.
Example to take a Card, Icon and Text component and combine it into a specific kind of card to be used in our App.

I have tried to do this 2 ways so far
- Directly linking to the file eg `../Icons/MyIcon.tsx`
- Importing as a dependency eg `@bit/someting.icons.my-icon`

Both ways work and I can build and test locally. But Tests always fail in the clould with the error
`Error: Invalid hook call. Hooks can only be called inside of the body of a function component.`

I understand why this is happening but not sure how to get around it. I confirmed all the components have the same peerDependencies using `bit show`.

Again this error only appears when testing in the cloud. Testing locally the tests all pass.

### Specifications

- Bit version: 14.7.6
- Node version: v12.13.1
- yarn version: 1.19.2
- Platform: darwin
- Bit compiler (include version): bit.envs/compilers/react-typescript@3.1.44
- Bit tester (include version): bit.envs/testers/jest@22.4.3

**Comment by itaymendel** [comment]
Hi, we do a lot of these compositions in our component. In fact, we found that with the more compositions we implement, the faster the team can deliver features and pages.

You can see an example of it [here](https://bit.dev/bit/evangelist/marketing/twitter-card/~code#marketing/twitter-card/twitter-card.tsx). It imports several components and exports a new component.

Can you share a repo or a way to reproduce the issue you are facing?

**Comment by makeupsomething** [comment]
@itaymendel 
Thank you for getting back to me. 
We are combining components much the same way as you are. And it does make things much faster which is great.

The only difference between what you have and our components is that you do not seem to have a test file. And we are getting the error when the tests run after exporting to Bit. 

I don't have a repo i can share right now as it is private but I can try to reproduce it in a new repo later today or tomorrow.

**Comment by itaymendel** [comment]
Do you track the test files as with the `--tests` option?
I'm trying to understand how to reproduce the issue you experience, so we can work to resolve it.

**Comment by makeupsomething** [comment]
@itaymendel 
Sorry for the delay, I was able to recreate the problem in this repo, https://github.com/makeupsomething/bit-test-app
You can see the error output on bit here https://bit.dev/makeupsomething/test/card/~console

The steps were
- Create the button component
- Add to project `bit add src/components/Button/* --tests src/components/Button/Button.spec.tsx --id button`
- Tag and export to bit

- Create the card component
- Use button inside card component (directly linking to it inside project '../Button/Button')
- Add to project `bit add src/components/Card/* --tests src/components/Card/Card.spec.tsx --id card`
- Tag and export

Then when processing the tests fail. But they pass locally.

**Comment by itaymendel** [comment]
Oh, I see.
Well, there is an issue with some of the testers where they can work in the component's original project, but unable to operate properly where they are imported to (or exported to, in this case). This is because of some differences in how Bit creates the isolated component environment in both these cases.

Usually, this is not an issue, but some testers are not as stable as we'd like because of it. We already [started to untangle the underline issues](https://github.com/teambit/bit/tree/harmony/main/src/extensions/isolator) and plan on releasing a version that solved component isolation using [Capsule](https://www.npmjs.com/package/@teambit/capsule).

What I suggest for now is still tracking the test files as part of the component, but omitting the tester configuration. This way when you maintain your components from your design-system repo, you keep updating the tests as well and run them as part of that repo test suite, and in a few weeks, when the updated version is released, you can add the tester configuration.

In any case, looking in the repo you shared, I think you should configure the component's dependency graph to set them better for reuse in other projects. We got some guidelines to React [here](https://docs.bit.dev/docs/react-guidelines). But generally speaking, you might want to do something similar to this setup:

```js
  "overrides" : {
      "*": {    // use any glob pattern that will "catch" the React components, otherwise it'll use these rules for all components (*)
        "dependencies": {
          "react": "-",
          "styled-components": "-",
          "@types/react": "-"
        },
        "devDependencies": {
          "react": "-"
        },
        "peerDependencies": {
          "react": "^16.12.0",
          "react-dom": "^16.12.0",
          "styled-components": "^5.0.1"
        }
      }
    }
```

**Comment by makeupsomething** [comment]
Cool, thank you for the explanation!

So for now we decided to just have the tests as part of our normal test suite like you suggested.

Thank you for the suggestion about the dependency graph too. We are still figuring all this out 👍
