### ISSUE TITLE
bit build adds whitespace to scss files

### ISSUE THREAD

**Issue by azheng003** [teambit/bit#2766]
### Describe the bug

Running bit build adds whitespace to .scss files (among other ones, like .md files)

### Steps to Reproduce

1. Add .scss file(s) as a bit component
2. Run bit build

### Expected Behavior

Compile .scss files without adding whitespace.

### Screenshots, exceptions and logs

![image](https://user-images.githubusercontent.com/49768461/85439432-dccac780-b541-11ea-8ed8-fc4d04f12f03.png)

### Specifications

- Bit version: 14.7.6
- Node version: v12.18.1
- npm / yarn version: npm 6.14.5
- Platform: Windows10
- Bit compiler (include version): bit.envs/compilers/react@1.0.14
- Bit tester (include version): None

### Additional context

I tried react@1.0.18 compiler but there was no difference. A co-worker of mine runs bit build and doesn't seem to run into this issue. It also adds whitespace to markdown files. Only JS files compile alright.

**Comment by benjgil** [comment]
Hi @azheng003 , thanks for logging your issue and apologies for the long delay in responding.

Did you find the source of this in the end? If not, have you checked more recently with updated versions of Bit and the compiler (we've done some optimising and bugfixes along the way, so it's very possible this has been fixed if it was a compiler issue).

Lastly, is it possible you have a VS code extension which is doing this? (which could be why your colleague hasn't been experiencing the same issue).

If you did find the issue, it would be great if you could comment here so that other Bit (and possibly VS code) users will know what could cause this.

Thanks!
