### ISSUE TITLE
error: component "webnovel.read-ui/button" was not found

### ISSUE THREAD

**Issue by ziven27** [teambit/bit#3118]
### Description

```bash
bit import

error: component "webnovel.read-ui/button@0.0.15" was not found
```

I have already remove this component form remote, but when I `bit import` it show this error.
Then I do every  thing it reminds me  
`your workspace has outdated objects. please use "bit import" to pull the latest objects from the remote scope.`

I do not known what to do

### Specifications

- Bit version:14.8.8
- Node version:v12.16.3
- npm / yarn version:1.17.0
- Platform:mac os
- Bit compiler (include version): react@1.0.20
- Bit tester (include version):

**Comment by benjgil** [comment]
hi @ziven27 - thanks for logging your issue, and apologies for the delay in responding.

Without knowing the full contents of your workspace, it does sound like that component is still being tracked by bit, and so it tries to import it when you run the Bit import command.

The fix is most likely to untrack the component by running `bit untrack webnovel.read-ui/button@0.0.15` (or however it's named in your namespace) and then see if the Bit import statement works as expected.
