### ISSUE TITLE
Cannot read property 'join' of undefined on bit build

### ISSUE THREAD

**Issue by pablorsk** [teambit/bit#3175]
### Describe the bug

Following [Angular Tutorial](https://docs.bit.dev/docs/tutorials/bit-angular-tutorial) and touch example compoment, is not posible build again the example component.

### Steps to Reproduce

```bash
git clone https://github.com/teambit/bit-angular-tutorial
cd bit-angular-tutorial/
yarn
bit init
bit import bit.envs/compilers/angular --compiler
bit import bit.angular-tutorial/product-list # official repo
bit build # all is ok to here
```
Then you change a simple string on component html, like `<h2>Products</h2>` to `<h2>List</h2>`  and rebuild.

```bash
bit build --verbose # this fails
successfully installed the bit.envs-dev/ng-packagr@0.0.1 compiler
Cannot read property 'join' of undefined
```

### Specifications

-  bit version   : 14.8.8
-  node version  : v10.19.0 (12.18.4 too)
-  npm version   : 6.14.4
-  yarn version  : 1.17.3
-  platform      : linux

`bit doctor` all passed

I also  tried on a docker machine, but I have the get a same result (`docker run -it --volume=`pwd`/:/localRepo --workdir="/localRepo" --memory=4g --memory-swap=4g --memory-swappiness=0 --entrypoint=/bin/bash  node:12.18.4`)

**Comment by JoshK2** [comment]
Hi, thanks for opening the issue.
The error was because the component was built with an incorrect compiler, as you can see in this version:
https://bit.dev/bit/angular-tutorial/product-list/~code?version=0.0.2

I exported a new version with the correct compiler:
https://bit.dev/bit/angular-tutorial/product-list/~code?version=0.0.3

you can now try again to import, modify, and build, and it should work as excepted.
