### ISSUE TITLE
Bit is not using the version of `peerDependencies` from `workspace.jsonc`.

### ISSUE THREAD

**Issue by Mikilll94** [teambit/bit#3972]
### Describe the bug

Bit is not using the right version of `peerDependencies` which were specified in `workspace.jsonc`.

### Steps to Reproduce

1. Open this project in VSCode
[bit-harmony-repro.zip](https://github.com/teambit/bit/files/6178473/bit-harmony-repro.zip)
2. Go to `workspace.jsonc` and look at `peerDependencies`. As you can see, React v17 is specified.
2. Run `bbit show base-button`
3. As you can see React v16 is listed

![Screenshot 2021-03-21 at 23 11 13](https://user-images.githubusercontent.com/17653648/111922546-bcad4200-8a9a-11eb-9868-f6da48d622c5.png)

### Expected Behavior

Bit should use the version of React which is specified in `workspace.jsonc`.

### Specifications

- Bit version: 0.0.327
- Node version: v14.15.5
- yarn version: 1.22.10
- Platform: MacOS 11.2.3

**Comment by benjgil** [comment]
Hi @Mikilll94 
Dependency configuration with Bit has an extra layer on top of the regular config that your used to from package.json:
1) where you define what packages are available in your project (package.json for a regular project, workspace.json's top-level dependency-resolver component with Bit)
2) the definition of which actual package is to be used in your code. When it comes to a regular component, bit will just take the version defined in your ws.json (easier than writing workspace.json 10 times) top-level dependency-resolver configuration. 
However, with Bit there's an extra layer whereby you can define overrides via your component development environment (CDE) which is what runs all the lifecycle tasks of your component (inc lint, test, compile, build, and rendering the local UI - among others) and where you can configure all of those tasks.
One feature of the CDE is this ability to restrict and override package dependencies - in this case, to ensure that components using a specific CDE arent by mistake given the wrong version of a framework, or that the framework isn't mistakenly added as a runtime dependency rather than a peer dependency.

For our base react environment this has been configured with version 16.13.1 for both react and react-dom, as peer dependencies, to ensure that no incorrect versioning is applied at the component/workspace level.

This itself can be overriden however, via an added configuration in ws.json, by applying the dependency-resolver component on the CDE itself. 

In your case, this would mean the following (from line 56 in your ws.json):
```
"teambit.react/react": { 
        "teambit.dependencies/dependency-resolver": {
          "policy": {
            "peerDependencies": {
              "react": "17.0.1",
              "react-dom": "17.0.1"
            }
          }
        }
      }
```

When you apply the dependencies like this they override the dependency-resolver config for the component it is applied on - in this case overriding the dependencies defined for the teambit.react/react environment component (like with everything in Bit, environments are also just another component :) ).

> Note: overriding here means merging - so this will only change/add the react and react-dom peer dependencies, and all other dependencies/peer dependencies configured for this environment will remain the same

I hope that clears up what's happening here. You can read more about this issue, and dependency resolving with Bit in general, in our docs (which are unfortunately still not at production level - but hey that's part of the fun of using a beta version...)
https://harmony-docs.bit.dev/dependencies/overview

**Comment by Mikilll94** [comment]
@benjgil 
Thanks for your detailed answer. Unfortunately adding your code to `wc.json` does not work.

You can check this in this project:
[bit-harmony-repro.zip](https://github.com/teambit/bit/files/6181040/bit-harmony-repro.zip)

Just execute
```
bbit compile base-button
bbit show base-button
```
and you will that it still displays React v16

**Comment by GiladShoham** [comment]
@Mikilll94 
Let me try to better explain the dependency resolution process:
First, you can read more about it [in the docs](https://harmony-docs.bit.dev/dependencies/dependency-resolution) or if you want even more detailed explanation, you can read about it in the [dependence-resolver aspect docs](https://bit.dev/teambit/dependencies/dependency-resolver).

I will only add here a small subset of the relevant info.
The dependency resolver hierarchy is as the following:

The hierarchy in a descending order:

1. Policies set by Variants (@teambit/variants) and the component.json files of "ejected" components (these two sources are merged by Variants).
1. Policies set by various extensions/aspects (using registerDependencyPolicy)
1.  Policies set by the environment (using getDependencies)
1.  Bit’s automated dependency detections, and policies set by the Dependency Resolver at the workspace configuration root-level.

Since the root dep resolver policy is only used as part of the the *automated dependency detections* (number 4), and react and react-dom are also configured via an env, the env configuration is stronger.

In order to solve this, you have 2 options:
1. [Creating your own env](https://harmony-docs.bit.dev/environments/create-environment) that set the react and react-dom to different versions using the [dependencies service](https://harmony-docs.bit.dev/environments/environment-services#dependencies)
2. Override the deps by variant (number 1) which is the strongest one.

Usually it's better to go with option 1 in that case, but for purpose of learning, trying, you can go with option 2.

Attaching you the `variants` entry in the workspace.jsonc (according to your repro project)
```js
"teambit.workspace/variants": {
    /**
     * "*" is a special rule which applied on all components in the workspace.
     **/
    "*": {
      /**
       * uncomment to apply the react environment on all components.
       **/
      "teambit.react/react": {}
    },
    "src/components": {
      "teambit.dependencies/dependency-resolver": {
        "policy": {
          "peerDependencies": {
            "react": "17.0.1",
            "react-dom": "17.0.1"
          }
        }
      }
    }
  }
```
What I did here is to say that every component under the folder src/components should have react and react-dom with v17.

few more notes:
1. when setting peer dependencies it is usually better to have more relaxed semver rule, for exmple - `~17.0.1` instead of just `17.0.1`.
2. I'm already in progress of upgrading the default react and react-dom to v17 (see https://github.com/teambit/bit/pull/3767)
