### ISSUE TITLE
generator should have same DX for all components

### ISSUE THREAD

**Issue by debs-obrien** [teambit/bit#4017]
### Description

```bit create react-example-button ui/button``` works as expected

<img width="529" alt="CleanShot 2021-03-29 at 17 13 31@2x" src="https://user-images.githubusercontent.com/13063165/112859147-db22c700-90b2-11eb-91a3-66492a76c2e0.png">

```bit create react-component ui/scope-card``` places the index file outside of the ui folder

<img width="547" alt="CleanShot 2021-03-29 at 17 13 41@2x" src="https://user-images.githubusercontent.com/13063165/112859109-d100c880-90b2-11eb-8dd1-1449bf602e8a.png">

using ```--namespace ui``` works but is a different experience to the button example where namespace is not needed. 

<img width="609" alt="CleanShot 2021-03-29 at 17 13 53@2x" src="https://user-images.githubusercontent.com/13063165/112859085-c9412400-90b2-11eb-9407-f830f0d46469.png">

using ```--namespace ui/base``` throws an error. what happens if you want them a few levels deep

<img width="757" alt="CleanShot 2021-03-29 at 17 26 20@2x" src="https://user-images.githubusercontent.com/13063165/112860193-e4f8fa00-90b3-11eb-92b1-eaf2873f5af6.png">

### Describe the solution you'd like

make it same experience for both example component and generic component where you have to give a component name

**Comment by davidfirst** [comment]
@itaymendel , you suggested to support adding namespace as part of the name, such as `bit create ui/button` instead of `bit create button --namespace ui`. As a reminder, the problem is with the scope-name that we don't have a good way to know whether a string have the scope-name in it or it's just a long namespace.
Until we make a decision, I suggest to throw an error saying the name can't contain a slash and to add a namespace you should use the `--namespace` flag.

**Comment by debs-obrien** [comment]
for me whatever solution is possible is good but both should have the same experience. that is key

**Comment by davidfirst** [comment]
Discussed with @itaymendel , for now, we'll assume that the entered name can only contain namespace, not scope.

**Comment by davidfirst** [comment]
Implemented.
Regarding the last screenshot with the error of "unable to add..", this is because the previous command already created a component with a directory, which is a parent of this directory.  (the previous command created a component at my-scope/ui/scope-card and this command tries to create a component inside this dir).
