### ISSUE TITLE
Wrong package name when setting defaultScope after tagging a component

### ISSUE THREAD

**Issue by Mikilll94** [teambit/bit#4049]
### Describe the bug
The package name is wrong if you first tag the component, then set the `defaultScope` and then export it.

![Screenshot 2021-04-02 at 14 21 31](https://user-images.githubusercontent.com/17653648/113415151-e5003f00-93be-11eb-934f-0c3e505c9f42.png)

### Steps to Reproduce
1. Init a Bit workspace. (`bit init --harmony`)
1. Add a component (`bit add`)
1. Tag this component (`big tag`)
1. Set the `defaultScope` in `workspace.jsonc` to your scope in Bit Cloud.
1. Export the component (`bit export`)
1. Go to the Bit Cloud and check the package name of your component. The package name is wrong. It contains the name "my-scope".

### Expected Behavior
The package name in Bit Cloud should be correct.

### Screenshots, exceptions and logs
If applicable, add screenshots, exceptions, and logs to help explain your problem.

### Specifications
* Bit version: 0.0.342
* Node version: v14.15.5
* npm / yarn version: 1.22.10
* Platform: MacOS 11.2.3

### Additional context
Here is the evidence that this bug exists:
https://bit.dev/miwasnie-org/test-collection/my-comp

**Comment by davidfirst** [comment]
I'll leave this issue open because we need a better way to avoid this confusion. (@GiladShoham , @itaymendel - maybe we should throw an error upon `bit tag` when the defaultScope was not changed?).

@Mikilll94 , although it's confusing, it's not a bug. The package-name is determined during `bit tag`, it saves all the metadata  (such as, dependency graph, dist files, package tar file, tag log etc.) of the component in the local scope. Upon export, it just sends these objects to bit.dev. It doesn't change them, so the package-name remained `my-scope`.

All you need to do is to set up the `defaultScope` as soon as you create a new workspace.

**Comment by Mikilll94** [comment]
@davidfirst 
Thanks for you answer. I will just add the info, that if you break the package name like I did, you cannot revert this. All subsequent exports will not change the package name. If you want to have a nice package name, you need to remove the component from the Bit Cloud and create it again.

Maybe when doing `bit export` you can check if the organisation name and collection is correct?

**Comment by itaymendel** [comment]
we can now use `bit rename` to fix these issues.
it will render the previous component as deprecated.
