### ISSUE TITLE
 missing packages or links from node_modules to the source

### ISSUE THREAD

**Issue by fazer1929** [teambit/bit#4406]
### Describe the bug
```js
missing packages or links from node_modules to the source (run "bit install" to fix both issues. if it's an external package, make sure it's added as a package dependency):
          Header.module.scss -> ~@my-scope/global-styles/ui
```
This error occurs when I try to run `bit tag`. The component runs normally in my localhost
I am importing a scss file of a component(that just has scss files) in another component.
I've also tried `bit install` but it doesn't fix it.

### Steps to Reproduce

1. Make a component containing only scss files. Ex- If there's a folder **global-styles** containing a file name _ui.scss. Use command `bit add global-styles --main _ui.scss`
1. Import the file in another component's scss as `@import "~my-scope/global-styles/ui"
1. Try tagging the second component.

### Expected Behavior
For the component to get tagged correctly for export

### Screenshots, exceptions and logs
```
PS E:\Projects\SawoLabs\SawoLabsBit> bit tag ui/header --message "First Version"
error: issues found with the following component dependencies

ui/header
       
       missing packages or links from node_modules to the source (run "bit install" to fix both issues. if it's an external package, make sure it's added as a package dependency):
          Header.module.scss -> ~@sawo/global-styles/ui
```

---
P.S. 
Here's a similar question on stackoverflow, it also has links to some components for which this thing is working.
[StackOverflow Question](https://stackoverflow.com/questions/62207414/how-to-use-with-bit-dev-with-global-scss-files-that-my-components-use)
### Specifications

- Bit version: 0.0.413
- Workspace type: harmony
- Node version:  v14.16.1
- npm / yarn version: 6.14.12
- Platform: Windows 10

**Comment by itaymendel** [comment]
hi!

there are some differences when you are building a module from css, ie - you need a js file to export it.

in your component, create an `index.js` file and build it as follows:

```js title="index.js"
import styles from 'mycss.module.scss';
export default styles.
```

this file needs to be the main file of the component as well.

For a node `import` statement to work, and having other components importing that css, node needs to have an index file as an entry point. So in order to import your css as a node module (i.e. import styles from `css_module`) you need an index file for node to access.
(An advantage of this is that you can also combine multiple css files into a single package which is accessed in your javascript via that single ‘styles’ object that you imported.)

if you are importing this from a css file later you will need to import the css directly, as node does not resolve for css file (ie `@import '~@sawo/global-styles/ui/colors.module.scss';`





9:38
i'm going to answer with this note, but should think about adding this to docs + template in the new html env, i guess

**Comment by fazer1929** [comment]
Hi thanks for the message.
can you please suggest an alternative to how I can achieve the functionality of having all my mixins, variables and breakpoints at one place and have various component's css use them?

**Comment by itaymendel** [comment]
you can create a component for your mixins, just keep an `index.js` file there to export all css. this is for the component to be compatible with node and be rsolveable by the node module resolution algorithm.

when you import these mixins from a css file you need to add the full path `@import '~@sawo/global-styles/ui/colors.module.scss';`.

keep the same process you done so far, it's just about thinking on your mixins as a module rather than a file.

**Comment by fazer1929** [comment]
Tried doing it but it still gives the same error
`missing packages or links from node_modules to the source (run "bit install" to fix both issues. if it's an external package, make sure it's added as a package dependency)`

can you tell me how can I add it as a package dependency, it might fix the problem?
