### ISSUE TITLE
Support anchor linking in documentation

### ISSUE THREAD

**Issue by rmetcalf-saatva** [teambit/bit#4682]
### Description
Because the documentation for components is contained within an iframe, using anchor links to link to other parts of documentation on the same page does not work and is not supported.

### Describe the solution you'd like
I'd like to be able to link to other parts of a documentation page, such as with a table of contents, to make documentation cleaner and more user friendly 

(This could be accomplished with something like postMessage, as discussed in this [thread from slack](https://bit-dev-community.slack.com/archives/CCDHG0TPY/p1627583852179600))

### Describe alternatives you've considered
Alternatives right now is to collapse major parts off documentation into an expandable div so it is easier to scroll to the heading that you need

**Comment by KutnerUri** [comment]
We wanted to support local links, but it's a little complicated, because the docs are isolated in a separate iframe.
So, we don't plan to support it right now, but I will try to document the feature:

```
+----------------------------------------+
| bit.dv                                 |
|        +-------------------------------+
|        | scope iframe                  |
|        |              +----------------+
|        |              |   docs iframe  |
+----------------------------------------+
````

### upward:
We can use postMessage to update the scope iframe with new urls. we already pass click events and other stuff at `preview.preview.ts`. We'd have to make sure it won't interfere with a routing library in the preview, like react-router.
The scope iframe should already update bit.dev (which updates the browser).

### downwards:
We already have a lot of parameters on the docs iframe, I'm not sure we can just add a `#anchor` on it. We could send the anchor with postMessage, but then we'd have to implement it ourselves (using `.scrollIntoView()`, etc), which I less like.

example docs url:
https://hu9y25l.scopes.bit.dev/api/teambit.base-ui/input/button@1.0.1/~aspect/preview/#teambit.base-ui/input/button@1.0.1?preview=overview

Using the hash allows us to swap between compositions without reloading (especially in local workspace), but I guess we don't really need all this information in the hash.
We also use the hash to pass parameters like turning on the highlighter, but the experience is not amazing this way, so we might also want to move it to postMessage.
