### ISSUE TITLE
Functionality for adding custom Jest config

### ISSUE THREAD

**Issue by dspacejs** [teambit/bit#4685]
### Description
I'd like to be able to add a custom Jest config. Right now `bit test` ignores any `jest.config.js` files in the root of the project, instead of using it.

### Describe the solution you'd like
Bit should automatically pick up and use the `jest.config.js` file, without the developer having to do anything.

### Describe alternatives you've considered
I can just not use a setup file, but this means I have to move a lot of my setup to each individual test (which is repetitive and verbose).

**Comment by GiladShoham** [comment]
Bit couldn't pickup and use the jest.config because of 2 reasons:
1. the same workspace might have multiple components which use different jest.config.
2. A bit component is imported to another workspace/machine which has different jest.config in the workspace which results in failing tests.

The way to achieve it is to create a [custom environment](https://harmony-docs.bit.dev/building-with-bit/environments#customizing-environments) which uses the `overrideJestConfig` API to provide custom jest config.
