### ISSUE TITLE
Add decorators to compositions

### ISSUE THREAD

**Issue by codylindley** [teambit/bit#4692]
### Description
Bit should offer an analogous solution like the one found with storybook decorators. i.e. https://storybook.js.org/docs/react/writing-stories/decorators

Bit composition should have an easy way to wrap a "decorator" around three levels of a composition:

1. At the preview level i.e. global (e.g. https://storybook.js.org/docs/react/writing-stories/decorators#global-decorators)
1. At the compositions module level (all compositions within the compositions module e.g. https://storybook.js.org/docs/react/writing-stories/decorators#component-decorators)
1. Individually for each, composition. (e.g. https://storybook.js.org/docs/react/writing-stories/decorators#story-decorators)

**Comment by codylindley** [comment]
@itaymendel @GiladShoham I was speaking with @KutnerUri about the functionality around storybook decorators. He suggested starting an issue to discuss the topic. Here is that issue.

**Comment by codylindley** [comment]
From my perspective, I am not requesting a specific implementation. This does not have to literally be decorators, but it should be trivial for a user to wrap compositions in the three levels suggested. We should have a trivial solution to common question around bit.

**Comment by KutnerUri** [comment]
The current solution we have is setting `providers` via the env. This is working, but has some pitfalls:

- It's not granular enough. I can't apply a provider to a specific composition (e.g. I want to show just one composition with dark-mod), and I have to apply the provider to all components in the env, or duplicate my env just for that component.
  This makes us write too many envs, and each of them with too many providers.
- Providers apply to the docs as well, because we can embed components inside the MDX. This is useful, so we shouldn't give up on it, but it sometimes make weird bugs. (see #4668)
- It forces me to update the env a lot. If I update the icon font, I have to update the env, tagging all components using it, or depending envs.
- It hides implicit dependencies. e.g. if the component relies on a gql provider, but it is applied by an env from another workspace, I won't understand it is even there, or how to make it work for another component. I will also not show up as peer dep on gql provider, even though it's implicitly needed.

This is why I find the decorators solution very elegant. It will also improve our interoperability with their format.
Env `providers` are useful tools by their own right, and should still be supported.

It will be easy to support it, we already have something similar called `.cavas`, which effects the styles of the composition card.
For the global level, I think we can use variants, like so:
```jsonc
"teambit.workspace/variants": {
  "ui/**": {
    "teambit.preview/preview": {
      "composition": {
        "decorators": [
          "@teambit/design.decorators.theme-selector",
          ["@teambit/documenter.decorators.centering", "^1.0.1"], // with version
        ]
      }
    }
  }
}
```

For reference, the syntax for the local version would be:
```tsx
export default {
  decorators: [themeDecorator];
}

export const Preview = () => <button>click me </button>
export const Dark = () => <button>click me</button>
Dark.decorators = [darkThemeDecorator]
```
