### ISSUE TITLE
BUG: Cannot find module errors and failed installation/start/scaffolding of new Bit React project

### ISSUE THREAD

**Issue by arizonatribe** [teambit/bit#4849]
### Describe the bug
Scaffolding out my first project using Bit (for a React project) the scaffolding fails with an unhandled promise rejection error (don't see that searching Github issues). Attempting to then correct it by `bvm install` (from the new project directory) repeats the error. Adding the `--log` flag just seems to indicate many missing dependencies that are attempting to be require'd, but nothing else really looked like a logged error.

```
Error: Cannot find module '~/Projects/bit-poc-three/node_modules/@company/scope.envs.my-react/dist/index.js'. Please verify that the package.json has a valid "main" entry
```

And as expected, `bvm start` also logged many of those errors (even though the component browser was launched). Attempting to bring up specific components in the UI results errors like these:

```
Module not found: Error: Can't resolve '@teambit/design.ui.external-link' in '~/Projects/bit-poc/node_modules/@company/scope.ui.card/dist'
```

Also tried to do `bit init --harmony` instead of `bit install` and the same result in incomplete installation and missing modules.

### Steps to Reproduce
Start on a Mac without Bit/Bvm installed

1.  npm i -g teambit/bvm
1. bvm install
1. modify `~/.bashrc` to contain `export PATH=$HOME/bin:$PATH`
1. bvm new react bit-poc

### Expected Behavior
New React project is ready to run.

### Screenshots, exceptions and logs
```
bit install
  Resolving component dependencies for workspace: 'bit-poc'
✔ importing components
  installing dependencies in workspace using teambit.dependencies/pnpm
✖ error: unable to load the extension "company.scope/envs/my-react", please use the '--log' flag for the full error.
✔ running pre install subscribers
✔ deduping dependencies for installation
Progress: resolved 14, reused 0, downloaded 0, added 0
** unhandled rejection found, please make sure the promise is resolved/rejected correctly! **
```

### Specifications
* Bit version: 0.0.26
* Workspace type: harmony
* Node version: 14.0.0
* npm / yarn version: 6.14.4
* Platform: Mac OSX 11.4

_for harmony workspace_

* relevant env: react

**Comment by davidfirst** [comment]
@arizonatribe , I'm unable to reproduce it, it's possible that at the time you tried to run it, one of the packages failed to install. (this unhandled rejection coming from `pnpm` indicates this. sadly we can't easily handle that error, it's an internal pnpm stuff). 

Can you give it another try?

(by the way, the version you mentioned is probably bvm version. to get Bit version, run `bit -v` ).

**Comment by arizonatribe** [comment]
Okay trying now. Looks like bit's version is 0.0.501. As an aside, is there a reason Bit isn't at a non-zero major or minor version yet?. I remember bringing up Bit at work three years ago and am surprised to see there isn't a major release yet.

**Comment by arizonatribe** [comment]
```
$ npm remove --global @teambit/bvm
$ rm -rf ~/bin/bit
$ bvm install
$ bvm version

current (used) bvm version: 0.0.26
latest available bvm version: 0.0.26

current (used) bit version: 0.0.502
latest installed bit version: 0.0.502
latest available bit version: 0.0.502
```

And next

```
$ bvn new react poc-component-library
```

But no output. Closed shell and re-opened a new one and reattempted, but same result.

And shows nothing scaffolded:

```
$ ls . | grep poc-component-library
```

The `bvm new react ...` just exited silently but didn't create anything.

**Comment by davidfirst** [comment]
Seems like you're trying to run `bit` commands with `bvm`.
Keep in mind that `bvm` is just a tool to install Bit. Once bvm is installed, just run `bvm upgrade` to get the latest version of Bit. 
From that point, forget about bvm. Run all commands with `bit`.

As to the versions, the legacy version is now 14.8.8. Harmony version starts with zero because it's still in beta.

**Comment by arizonatribe** [comment]
Yeah I got mixed up there when I tried it again from scratch. Originally I used `bit new react my-project` instead of `bvm`

So I'm still receiving the original "promise rejection" error that I reported, when I scaffold out from scratch.

To simplify, I tried the whole process from scratch on a different machine (Fedora 29, Intel NUC) and encountered the exact same problems I detailed here on my work Mac laptop (minus the `bvm` mixup I replied about)

---

From sratch:

```
(dave)localhost:~
# npm install -g @teambit/bvm
/home/dave/.nvm/versions/node/v14.0.0/bin/bvm -> /home/dave/.nvm/versions/node/v14.0.0/lib/node_modules/@teambit/bvm/dist/app.js

... omitted some output (just the annoying guy at CoreJs asking for someone to give him a job)

...some peer dependency warnings on react-dom, @teambit/legacy, etc.

+ @teambit/bvm@0.0.26
added 134 packages from 103 contributors in 17.862s
(dave)localhost:~
# bvm install
✔ downloading version 0.0.502 in 34.14 seconds
✔ extracting version 0.0.502 in 19.898 seconds
✔ removing /home/dave/.bvm/temp/0.0.502 in 55 milliseconds
✔ moving from temp folder to final location in 2 milliseconds
global Bit install location was not found in your PATH global variable.
please add the following to your bash/zsh profile then re-open the terminal:
export PATH=$HOME/bin:$PATH
for more information read here - https://harmony-docs.bit.dev/introduction/installation

version 0.0.502 installed on /home/dave/.bvm/versions/0.0.502 in 55.558 seconds
```

Then added the `export` for the `$HOME/bin` folder:
```
(dave)localhost:~/projects
# vim ~/.bashrc
(dave)localhost:~/projects
# source ~/.bashrc
```

Then attempted to scaffold the new project:
```
(dave)localhost:~/projects
# bit new react poc-component-library
# bit new react poc-component-library
help us prioritize new features and bug fixes ....? [yes(y)/no(n)]:  (yes) y
✖ error: unable to load the extension "company.scope/envs/my-react", please use the '--log' flag for the full error.
  installing dependencies in workspace using teambit.dependencies/pnpm
✔ running pre install subscribers
✔ deduping dependencies for installation
Progress: resolved 14, reused 0, downloaded 0, added 0
** unhandled rejection found, please make sure the promise is resolved/rejected correctly! **
```

Reattempted with the `--log` flag, and here's the error throw (several times in the output):
```
user gets the following error: Premature close
Premature close
** unhandled rejection found, please make sure the promise is resolved/rejected correctly! **
got an error from command new: Error [ERR_STREAM_PREMATURE_CLOSE]: Premature close
Error [ERR_STREAM_PREMATURE_CLOSE]: Premature close
    at Source.onclose (internal/streams/end-of-stream.js:105:38)
    at Source.emit (events.js:315:20)
    at Extract.destroy (/home/dave/.bvm/versions/0.0.502/bit-0.0.502/node_modules/tar-stream/extract.js:197:34)
    at Source.destroy (/home/dave/.bvm/versions/0.0.502/bit-0.0.502/node_modules/tar-stream/extract.js:38:16)
    at Object.destroyer (internal/streams/destroy.js:166:59)
    at internal/streams/pipeline.js:58:19
    at internal/util.js:392:14
    at Source.<anonymous> (internal/streams/pipeline.js:84:7)
    at Source.<anonymous> (internal/util.js:392:14)
    at Source.onend (internal/streams/end-of-stream.js:95:49)
    at Source.emit (events.js:327:22)
    at endReadableNT (/home/dave/.bvm/versions/0.0.502/bit-0.0.502/node_modules/tar-stream/node_modules/readable-stream/lib/_stream_readable.js:1094:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
could not clone error
    Error [ERR_STREAM_PREMATURE_CLOSE]: Premature close
        at Source.onclose (internal/streams/end-of-stream.js:105:38)
        at Source.emit (events.js:315:20)
        at Extract.destroy (/home/dave/.bvm/versions/0.0.502/bit-0.0.502/node_modules/tar-stream/extract.js:197:34)
        at Source.destroy (/home/dave/.bvm/versions/0.0.502/bit-0.0.502/node_modules/tar-stream/extract.js:38:16)
        at Object.destroyer (internal/streams/destroy.js:166:59)
        at internal/streams/pipeline.js:58:19
        at internal/util.js:392:14
        at Source.<anonymous> (internal/streams/pipeline.js:84:7)
        at Source.<anonymous> (internal/util.js:392:14)
        at Source.onend (internal/streams/end-of-stream.js:95:49)
        at Source.emit (events.js:327:22)
        at endReadableNT (/home/dave/.bvm/versions/0.0.502/bit-0.0.502/node_modules/tar-stream/node_modules/readable-stream/lib/_stream_readable.js:1094:12)
        at processTicksAndRejections (internal/process/task_queues.js:84:21)
```

**Comment by davidfirst** [comment]
@arizonatribe , interesting. I have never seen this error of `ERR_STREAM_PREMATURE_CLOSE` before when running `bit new`. 
The fact that you get the same error on your mac and a different Linux machine is even more surprised. 
Do you have a slow internet connection by any chance? 
Is the node version in the Linux machine is also v14.0.0? 
I'm trying to think how can I reproduce it.

**Comment by arizonatribe** [comment]
Yes it's Node v14.0.0 on both machines.

Internet speed is fine: 154.7 Mbps (download) 35.5 Mbps (upload)

**Comment by arizonatribe** [comment]
Also I tried to create an Alpine-Node-14 docker image to run all these steps together, but ran into an issue with that because the `bit new ...` script is interactive and it didn't seem I can just feed in `-y` to agree to the "send usage report to bit..." option. Do you know if there's a way to make that script non-interactive (have it agree to all defaults)? Then I could dockerize it and more easily try several things

**Comment by davidfirst** [comment]
@arizonatribe , sure. It's actually not `bit new`, it's just the first command that you're running. 
What you can do is before running any other `bit` command, run the configuration setup you want, for example:
```
bit config set analytics_reporting true
bit config set error_reporting true
bit config set user.name tester
bit config set user.email ci@bit.dev
```

**Comment by arizonatribe** [comment]
Ah okay. I'll give that a shot and see whether the behavior is different in a docker container than on these two machines natively

**Comment by arizonatribe** [comment]
Okay I'm able to get this to run fine in a docker container. I'm not sure what issue is causing the problem on my Mac and Linux machine, but looks like the answer is somewhere on my end, since this runs in a docker container without problems.

```
FROM node:14-alpine
RUN apk update && apk add --no-cache curl git bash

ENV WORK_DIR=/usr/local
WORKDIR $WORK_DIR
RUN chown -R node:node $WORK_DIR
USER node

RUN echo $PATH
ENV PATH=/home/node/bin:$PATH
RUN echo $PATH

RUN cd $WORK_DIR \
  && npm install --global @teambit/bvm \
  && bvm install \
  && bit config set analytics_reporting true \
  && bit config set error_reporting true

CMD bit new react my-app
```

Feel free to close this out, and if I figure out what was causing the problem, I'll add a reply to the thread here.

**Comment by davidfirst** [comment]
@arizonatribe , sounds good. I'm really curious what could it be. Maybe it's something to do with the network configuration / firewall. 
Please update us if you find anything.

**Comment by gibbon** [comment]
weirdly Im getting this too:

 ~/projects/bvm  npm install --global @teambit/bvm
npm WARN deprecated acorn-export-ns-from@0.2.0: acorn>=7.2 supports export-ns-from
npm WARN deprecated acorn-import-meta@1.1.0: acorn>=7.2 supports import-meta
npm WARN deprecated acorn-bigint@1.0.0: acorn>=6.2 supports bigint
npm WARN deprecated acorn-logical-assignment@0.1.4: acorn>=7.4 supports logical assignments
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated smartwrap@1.2.5: Backported compatibility to node > 6
npm WARN deprecated acorn-numeric-separator@0.3.6: acorn>=7.4 supports numeric separators
npm WARN deprecated core-js@2.6.12: core-js@<3.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfille.

added 874 packages, and audited 875 packages in 57s

75 packages are looking for funding
  run `npm fund` for details

22 vulnerabilities (17 low, 5 high)

To address issues that do not require attention, run:
  npm audit fix

To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details.
 ~/projects/bvm  bvm install
✔ downloading version 0.0.507 in 1 minute, 59.409 seconds
✔ extracting version 0.0.507 in 25.633 seconds
✔ removing /Users/tday/.bvm/temp/0.0.507 in 79 milliseconds
✔ moving from temp folder to final location in 12 milliseconds
version 0.0.507 installed on /Users/tday/.bvm/versions/0.0.507 in 2 minutes, 26.208 seconds
 ~/projects/bvm  bit new react testapp
✖ error: unable to load the extension "company.scope/envs/my-react", please use the '--log' flag for the full error.
  installing dependencies in workspace using teambit.dependencies/pnpm
✔ running pre install subscribers
✔ deduping dependencies for installation
Progress: resolved 17, reused 0, downloaded 0, added 0
** unhandled rejection found, please make sure the promise is resolved/rejected correctly! **
Premature close
** unhandled rejection found, please make sure the promise is resolved/rejected correctly! **
Premature close
** unhandled rejection found, please make sure the promise is resolved/rejected correctly! **
Premature close
** unhandled rejection found, please make sure the promise is resolved/rejected correctly! **
Premature close
** unhandled rejection found, please make sure the promise is resolved/rejected correctly! **
Premature close
** unhandled rejection found, please make sure the promise is resolved/rejected correctly! **
Progress: resolved 18, reused 0, downloaded 0, added 0

**Comment by gibbon** [comment]
ah my local env was set to node 13, I just switched to node 16 and everything works now

**Comment by davidfirst** [comment]
@gibbon , thanks for the update. Good to know.
