### ISSUE TITLE
Instructions in guide messed up my user path env var on windows 10

### ISSUE THREAD

**Issue by rbabayoff** [teambit/bit#4892]
Hey there,

The following command from [this page](https://harmony-docs.bit.dev/getting-started/installing-bit) in the docs basically overwrites the user's path env var on windows and forced me to waste a lot of time to restore the path so I can run vs code.exe, npm commands, etc.

`setx path "%path%;%LocalAppData%\.bvm"`

You guys need to fix the docs.

**Comment by Mikilll94** [comment]
@rbabayoff 
This command does not overwrite PATH env. Instead you have probably encountered this problem: https://github.com/teambit/bvm/issues/11

**Comment by khalibloo** [comment]
It doesn't seem like a matter of hitting the limit. I don't think that's a powershell syntax. It overwrites the Path variable with that gibberish rather than appending. I believe the `%path%` syntax is a cmd thing (which, why?). This is dangerous to have in the docs. In my case, I had no restore point to go back to. Lots of apps and commands broke over this.

**Comment by akshaycj** [comment]
Same here. wasted a lot of time because of this. is there a way to restore the original paths? @khalibloo 
I lost all the paths that was originally there and nothing on CLI works now.
You guys need to fix your docs! it's breaking everyone's machine and your reputation.

**Comment by giteden** [comment]
@rbabayoff  the 'path' section was removed from the docs
thanks for letting us know!

**Comment by khalibloo** [comment]
> Same here. wasted a lot of time because of this. is there a way to restore the original paths? @khalibloo I lost all the paths that was originally there and nothing on CLI works now. You guys need to fix your docs! it's breaking everyone's machine and your reputation.

@akshaycj  I think Windows Restore might be able to do the trick if you're lucky enough to have a recent restore point. Otherwise, you may just have to reinstall your apps. Those are at least the only practical methods I'm aware of. In my case, I was able to remember most of the paths and manually add them back. The ones I couldn't remember, I had to reinstall whenever I stumbled upon a failing command.
