### ISSUE TITLE
`bit remove --force` should "archive" a component

### ISSUE THREAD

**Issue by itaymendel** [teambit/bit#4899]
Bit cares deeply about the dependency graph. So much so that it does not allow deleting a component when another component depend on that component.

However, at times components do need to be deleted, especially when they get renamed. What developers try to do right now is to `remove --force` a component. This is a very dangerous action that has breaking results. Instead I suggest changing how `bit remove --force` operate, and behind the scenes, instead of deleting the objects, marking the component as archived.

### In Scope UI
* Not visible in the gallery
* Not visible in the component-tree
* Not visible in the `cmd+K` search
* Be "greyed-out" on the dependency graph, and annotated as "archived".
* When opening a direct link to an archived component, prompt a notification saying this is an archived component.
* When opening a direct link to an archived component, show an alert on the top of the component overview saying component is archived.

### In Workspace UI
* visible in the gallery, but marked as archived
* visible in the component-tree, but marked as archived
* visible in the `cmd+K` search, but marked as archived
* Be "greyed-out" on the dependency graph, and annotated as "archived".
* When opening a direct link to an archived component, prompt a notification saying this is an archived component.
* When opening a direct link to an archived component, show an alert on the top of the component overview saying component is archived.

## Other commands:
* `bit install` should allow to install archived components, but prompt a warning
* `bit import` should allow to import archived components, but prompt a warning
* `bit status` should prompt a warning of depending on archived component.
* `bit status` should prompt a warning if an archived component is modified.
* `bit build` should prompt a warning we are building an archived component.
* `bit tag` should prompt a warning (including `--soft`) we are about to version an archived component.
* `bit list` should not show archived components by default (similar to deprecated).
* `bit list` should have a flag to add archived components.
* `bit list` should mark archived components.

**Comment by davidfirst** [comment]
After implementing part of it, discussed it with @ranm8  and @GiladShoham , and the decision was made to go with a different route.

The idea of marking a component as "archive" is kind of a bandaid that is needed because many things are broken as a result of the remove. Instead of marking as archive, we want to be more tolerate and not break when dependencies are missing.
In fact, a big part of this task was already implement. For the most part, users should be able to import components with missing dependencies and Bit should warn them and show in bit-status a warning that the dependencies are missing (I will double check and make sure that it works). 
The important thing here is that users should be able to remove the dependencies from the code and tag the component with no errors.

If this component has dependents in other scopes, when those dependencies are installed, users will get errors about missing package. We plan to fix it later, but for now, we should warn them about it and suggest users to deprecate the components instead (see below for more details).

About `deprecate` vs `archive`. They are very similar, and the only difference we might want is for archive to not be shown in the UI while deprecate might be shown. But other than that they're the same. We can configure the deprecate to be shown or hidden. The duplication we'll have between the two doesn't justify it for now. So we'll have only deprecate, and all the features described in this Github issues, should be applied to `deprecate`. e.g, the warnings on bit import/install/status  and the UI changes. 

Back to remove-components, once a user removes components that have dependents, we can suggest two options:
1. re-run with `--force`, and it will remove the dependents completely. 
2. run `bit deprecate <ids>`, and we should list the ids for the user to deprecate. 

@itaymendel , FYI. (Ran will discuss this with you as well).

**Comment by GiladShoham** [comment]
@davidfirst one small correction. About option 1. The force will remove what you asked. Not the dependents. The dependents will now get the error about missing dependencies as described above

**Comment by davidfirst** [comment]
Correct. I meant it will remove the components that have dependents. I'll edit my comment above to clarify this.

**Comment by itaymendel** [comment]
closing. resolved remove issues.
