### ISSUE TITLE
Bit-server by docker is not working with volume option 

### ISSUE THREAD

**Issue by pgangwani** [teambit/bit#4965]
### Describe the bug
Hello Bit team , I am finding real basic difficulties with bit in my POC. I am using docker to deploy remote server in self hosted mode. I have been following [doc](https://github.com/teambit/bit/tree/master/scripts/docker-teambit-bit#combining-scope-volume-with-scope-namelocation) to run docker with volume but not able to do because of below error which results in 
![](https://user-images.githubusercontent.com/14316332/137508667-15537c21-47fb-4c1c-aa4e-703a42bd57f7.png)

### Steps to Reproduce
1. Make sure docker is installed in your machine
1. Follow [doc](https://github.com/teambit/bit/tree/master/scripts/docker-teambit-bit#using-volume-to-make-sure-data-is-persisted) to run 

```
docker run -it -v ~/bitvolume/one:/root/remote-scope -p 8200:3000 bitcli/bit-server:latest
```

3. Observe the error

```
- running command "start"...
** unhandled rejection found, please make sure the promise is resolved/rejected correctly! **
Unknown UI root: "". Available ui roots are: []
```

### Expected Behavior
Expected result should be getting docker up and running wihtout any error / exception

### Screenshots, exceptions and logs
![](https://user-images.githubusercontent.com/14316332/137509908-01405fd6-f994-492b-bcbb-31efa74dc338.png)

### Specifications
* Bit version: 0.0.526
* Workspace type: (harmony/legacy): NA (using docker which uses bit init --bare )
* Node version: v12.22.6
* npm / yarn version: 6.14.15 / 1.22.4
* Platform: 

_for harmony workspace_

* relevant env
* relevant aspects

_for leagacy_

* Bit compiler (include version):
* Bit tester (include version):

### Additional context
I chatted with Bit member on slack.

**Comment by bobum** [comment]
For our container - in Azure - once we set up the volume, we just had to attach it to the mount point we had setup in the dockerfile for the WORKDIR
For our installation - once those two matched - it just worked.  We got it working in ACI as well as K8s in Azure (mostly - more on that later) - HTH

**Comment by 77629296** [comment]
create ~/bitvolume/one/scope.json
solved this problem

scope.json like this

{
    "name": "one",
    "remotes": {},
    "version": "1.0.154",
    "lanes": {
        "current": "main",
        "tracking": []
    }
}

**Comment by lukassos** [comment]
I must agree with @pgangwani  here, you should be able to run empty server with custom scope without presetting the volume. 

Thanks @77629296 . The only solution without editing docker file is only to populate your volume folder beforehand with base structure of scope. 

IMHO There should be ENV variable used instead of ARG in the docker file then we might be able to change it before runtime. 
See the latest dockerfile version as of now: [bit-server/latest](https://hub.docker.com/layers/bitcli/bit-server/latest/images/sha256-71088e62003f83efda9a50bfc9a48aca59f10ae16aa6cb07190ff7e358427230?context=explore)

**Comment by KutnerUri** [comment]
I'm not familiar with setting up docker, @GiladShoham might be able to help.

Why are you creating the scope manually, and not using `bit init --bare`? 🤔

**Comment by robwdux** [comment]
Ran into this issue when attempting to deploy on AWS Fargate with EFS for persistence.

I'm working around the issue like so. bind mounts obscure the underlying filesystem.
- override the entrypoint script that ships with the node image this is based off as to not interfere with running necessary commands to override / initialize at runtime
- pass commands to evaluate if initialized and do so if not, solves the bind mount issue and custom scope path

the maintainers may address this, also consider using the existing node user with gid/uid 1000 rather than running as root

```
mkdir -m 0750 -p /tmp/bit-server
docker run \
  --rm --tty --interactive \
  --volume /tmp/bit-server:/root/remote-scope \
  --entrypoint /bin/bash \
  --publish 3000:3000 \
  bitcli/bit-server:latest \
  -xc "test -f scope.json || bit init --bare; bit start"
 ```

**Comment by mingfang** [comment]
when mounting an empty volume to `/boot/remote-scope`, the original `scope.json` file will be missing and `bit start` will fail.
@robwdux has the right solution and should be added to the default Dockerfile.
The current Dockerfile and instructions are wrong and will effect every one.
I wasted a day fixing this problem.

**Comment by KutnerUri** [comment]
@mingfang - can you link us to the problematic instructions / dockerfile?

**Comment by mingfang** [comment]
There are multiple places in the doc but here is one
https://github.com/teambit/bit/blob/master/scripts/docker-teambit-bit/README.md?plain=1#L57

Running using this instruction results in this error
```
 docker run -it -v /tmp/remote-scope:/root/remote-scope -p 3000:3000 bitcli/bit-server:latest
Warning: running bit as root might cause permission issues later
bit start can only be run inside a bit workspace or a bit scope - please ensure you are running the command in the correct directory
```

The reason is my host directory `/tmp/remote-scope` is empty and does not have `scope.json`.

**Comment by KutnerUri** [comment]
I think it is implied that the `{scope-path-on-host}:/root/remote-scope` folder should have a scope.

@GiladShoham - it's your file. Maybe we need to explain how to init a bare scope in a docker container?

also @mingfang - I'm guessing you need to use `Dockerfile-bit-server` which seems to pre-include a running bare scope, no? what image are you using?

**Comment by mingfang** [comment]
> I think it is implied that the `{scope-path-on-host}:/root/remote-scope` folder should have a scope.
> 
> @GiladShoham - it's your file. Maybe we need to explain how to init a bare scope in a docker container?
> 
> also @mingfang - I'm guessing you need to use `Dockerfile-bit-server` which seems to pre-include a running bare scope, no? what image are you using?

I'm using the standard image `bitcli/bit-server:latest`
You can't assume the mounted volume already has a bare scope, especially in a Kubernetes cluster when newly provisioned volumes are empty.

Please look at my bit-server Terraform module to see how I handle the situation
https://github.com/mingfang/terraform-k8s-modules/blob/master/modules/bit-server/main.tf#L27

**Comment by GiladShoham** [comment]
@mingfang If you want to submit a pr to improve it I'll be happy to review it.
Thanks!

**Comment by angelorbastos** [comment]
I was trying to self-host Bit on a k8s cluster yesterday and came across this issue with the volume. To be honest, I had a lot of trouble getting the app to run without any warnings or errors, so here are a few things that could be enhanced:

- The provided Docker images use a root user, which throws a warning/error at runtime
- The Node version specified on the [example `Dockerfile` ](
`Dockerfile`)(12.22.0) throws errors when running exactly the code that's in the docs
- Then there's the problem this issue refers to: if you're using a volume, `bit init --bare` must be run on the `CMD` instruction instead of on a `RUN` instruction

This is the final `Dockerfile` I ended up using, perhaps it can help someone:

```
FROM node:16.19.1

USER node

ENV USER_HOME=/home/node

ENV BVM_GLOBALS_DIR=$USER_HOME/bvm
ENV NPM_GLOBALS_DIR=$USER_HOME/.npm-global
ENV BIT_SCOPE_DIR=$USER_HOME/otus-remote-scope

ENV NPM_CONFIG_PREFIX=$NPM_GLOBALS_DIR
ENV NODE_OPTIONS=--max_old_space_size=4096

ENV PATH=$PATH:$USER_HOME/bin:$BVM_GLOBALS_DIR/bin:$NPM_GLOBALS_DIR/bin

RUN mkdir -p $NPM_GLOBALS_DIR $BVM_GLOBALS_DIR $BIT_SCOPE_DIR

RUN npm i -g @teambit/bvm

RUN bvm upgrade
RUN bvm config set DEFAULT_LINK $NPM_GLOBALS_DIR/bin/bit

RUN bit config set analytics_reporting false
RUN bit config set no_warnings false
RUN bit config set interactive false
RUN bit config set error_reporting true

WORKDIR ${BIT_SCOPE_DIR}

CMD bit init --bare && bit start
```
To explain it a bit, I had to:

- Use the `node` user, provided by Node's Docker image, so I could operate as a non-root user
- Create a new directory for `npm` global packages (this might not be necessary)
- Then setup all `bvm` and `bit` settings at build-time
- Use both `bit init --bare` and `bit start` with `CMD`
  - `bit init --bare` will ensure the files are created at the volume, although here I'm counting on the command not overwriting volume files and I'm not sure wether it will or not, so it's probably safer to do a check for scope files before running `bit init`
