### ISSUE TITLE
Post install for bit build fails for custom typescript modules

### ISSUE THREAD

**Issue by moodys-onkar** [teambit/bit#5161]
### Description
We have some unit tests that use jest and also the jest-matcher-specific-error libraries for our bit components and functions.
when running bit build i get this error
jest-matcher-specific-error is where toMatchError comes from

`The following errors were found while running the build pipeline
Failed task 1: "teambit.compilation/compiler:TSCompiler" of env "teambit.react/react"
component: path-to/component
/path-to-test-file/testfile.test.ts:10:29 - error TS2339: Property 'toMatchError' does not exist on type 'JestMatchers<any>'.

10       expect(any).toMatchError(`

We've done the jest recommended additions by creating a global.d.ts file  that imports the jest-matcher-specific-error lib and adding global.d.ts to our tsconfig.json . If I run the jest tests normally, they pass, but the error persists when running bit build

### Specifications
* Bit version:
* Node version:
* npm / yarn version:
* Platform:
* Bit compiler (include version):
* Bit tester (include version):

**Comment by benjgil** [comment]
Hi @moodys-onkar 
I think we've also been through this on slack, but for the sake of anyone else seeing this sort of issue - it's to do with overriding the env's typescript config in order to add the global.d.ts file you created in order for the jest plugin to work.

Here’s an example of adding types via the env’s tsconfig:
[This is an env](https://github.com/teambit/bit-lit/blob/34b1b093f8aff96ff33ad1e64784a223361a13a3/web-components/lit/lit-env.main.ts#L133) which uses a typescript transformer, which itself contains the [command to add types](https://github.com/teambit/bit-lit/blob/34b1b093f8aff96ff33ad1e64784a223361a13a3/web-components/lit/typescript/ts-transformers.ts#L13) to the env’s tsconfig
