### ISSUE TITLE
Bit start runs the local server but Preview is failing with the Error

### ISSUE THREAD

**Issue by chethanbr25** [teambit/bit#5183]
### Describe the bug
Bit start runs the local server but Preview sis failing with the Error

### Steps to Reproduce
This issue is happening with react 17 

### Expected Behavior
Preview and composition should work fine

### Screenshots, exceptions and logs
![image](https://user-images.githubusercontent.com/5637742/147377914-bd2d04ff-63b4-4460-acef-844721e40137.png)

### Specifications
* Bit version:
* Workspace type: (harmony/legacy)
* Node version:
* npm / yarn version:
* Platform:

_for harmony workspace_

* relevant env
* relevant aspects

_for leagacy_

* Bit compiler (include version):
* Bit tester (include version):

**Comment by KutnerUri** [comment]
@chethanbr25 - uppercase React, ie. `import React from 'react'`.

This is because of the JSX babel transform:
<img width="795" alt="Screen Shot 2022-01-10 at 17 16 07" src="https://user-images.githubusercontent.com/5400361/148790004-15278b8b-54e6-467a-9475-3ac001389996.png">

Future JSX transform will improve this type of errors.
