### ISSUE TITLE
can't tag or export remote scope after first time exporting to custom remote, following getting started guide with custom remote

### ISSUE THREAD

**Issue by brandoncollins7** [teambit/bit#5274]
### Describe the bug
Following all the instructions on getting started, I created a react project with demo code, added a custom control.

I then tagged the components using 'bit tag --all --message "first version"'

I added my custom remote: 'bit remote add http://localhost:3005' and updated my defaultScope to 'remote-scope'

Ran bit export and it successfully exported to my docker server.

Now it appears my project is broken.

'bit export' - says nothing to export

'bit tag --all --message "second version"'  displays the following error:

    remote-scope/pages/welcome@0.0.1
    
           missing components (use "bit import" or `bit install` to make sure all components exist):
              welcome.tsx -> ui/card@0.0.1, ui/card@0.0.1, ui/heading@0.0.1, ui/heading@0.0.1, ui/text@0.0.1, ui/text@0.0.1
    
    remote-scope/ui/card@0.0.1
    
           missing components (use "bit import" or `bit install` to make sure all components exist):
              card.tsx -> ui/heading@0.0.1, ui/heading@0.0.1, ui/text@0.0.1, ui/text@0.0.1 bit import or bit install does not resolve the issue. 

### Expected Behavior
Should be able to export or tag an updated version of my components

### Screenshots, exceptions and logs
![image](https://user-images.githubusercontent.com/36413482/149407331-49b28960-60e3-4715-9802-062c443f1050.png)

### Specifications
* Bit version: 0.0.617
* Workspace type: (harmony/legacy) harmony
* Node version: v14.16.0
* npm / yarn version: 6.14.11
* Platform: Windows

_for harmony workspace_

* relevant env: react

**Comment by itaymendel** [comment]
you are likely tagged passed versions with other scope-names, or deleted them.
if you are getting started and doing renames/changes often on setting up your project - i suggest running `bit init --reset-new` to set your workspace to a more clean state which just your components as "new".

the error you got is due to a mis-aligned `.bitmap` file. this is likely a result of a `tag` you didn't export, and them manually removing components from the file system without the `bit remove` command.
