### ISSUE TITLE
GeneratePreview error when I execute 'bit tag' command

### ISSUE THREAD

**Issue by SantoshAccion** [teambit/bit#5653]
### Description
I get the below error when I run `bit tag` command -

```
✔ installing dependencies using pnpm
✔ running post install subscribers
✔ linking components
  running build pipe for 1 environments, total 7 tasks
  generated graph for env "teambit.react/react", originalSeedersOfThisEnv: 1, graphOfThisEnv: 1, graph total: 1    
✔ executing pre-build for all tasks
✔ env "teambit.react/react", task "teambit.harmony/aspect:CoreExporter (export all core aspects via the main aspects)" has completed successfully in 7ms
✔ env "teambit.react/react", task "teambit.compilation/compiler:TSCompiler (compile components for artifact dist)" 
has completed successfully in 7s
✔ env "teambit.react/react", task "teambit.defender/tester:TestComponents" has completed successfully in 17ms      
✔ env "teambit.react/react", task "teambit.harmony/application:build_application" has completed successfully in 2ms✔ env "teambit.react/react", task "teambit.pkg/pkg:PreparePackages" has completed successfully in 10ms
✔ env "teambit.react/react", task "teambit.preview/preview:GenerateEnvTemplate" has completed successfully in 9ms  
✖ env: teambit.react/react, task "teambit.preview/preview:GeneratePreview" has failed
✔ executing post-build for all tasks
✖ teambit.pipelines/builder, running build pipe for 1 environments, total 7 tasks (completed in 41s)

The following errors were found while running the build pipeline
Failed task 1: "teambit.preview/preview:GeneratePreview" of env "teambit.react/react"
component: tru-design.components/lab/truc-single-node@0.0.4
message: Couldn't find configuration for either precaching or runtime caching. Please ensure that the various glob 
options are set to match one or more files, and/or configure the runtimeCaching option.

Found 1 errors in 1 components


✖ Total 7 tasks. 6 succeeded. 1 failed. 0 skipped. Total errors: 1.
```

### Specifications
-BVM version: 0.0.37

* Bit version: 0.0.703

### Context and additional information
I was suggested to use `--force-deploy` on the slack channel and that helped me tag the component and export it.
Post this I'm unable to see the preview in my remote scope.
Previously I was on an older version of bit and I tried this again after updating it to the latest version and I still have this issue .
It would be great if you could help with this.

**Comment by EmilKidi** [comment]
Seeing the same issue with Bit version: 0.0.703

Downgrading to Bit version: 0.0.697 works

**Comment by h3nk42** [comment]
had a similiar thing on 0.0.704 that got fixed by downgrading to 0.0.698
`✔ env "aumio.genesis/extensions/custom-react-native@0.0.19", task "teambit.defender/tester:TestComponents" has completed successfully in 13ms
✔ env "aumio.genesis/extensions/custom-react-native@0.0.16", task "teambit.defender/tester:TestComponents" has completed successfully in 233μs
✔ env "aumio.genesis/extensions/custom-react-native@0.0.19", task "teambit.harmony/application:build_application" has completed successfully in 305μs
✔ env "aumio.genesis/extensions/custom-react-native@0.0.19", task "teambit.pkg/pkg:PreparePackages" has completed successfully in 5ms
✔ env "aumio.genesis/extensions/custom-react-native@0.0.19", task "teambit.preview/preview:GenerateEnvTemplate" has completed successfully in 13ms
Cannot find module 'postcss-loader'
Require stack:
- /Users/neekh/.bvm/versions/0.0.704/bit-0.0.704/node_modules/@teambit/react/dist/webpack/webpack.config.base.js
- /Users/neekh/.bvm/versions/0.0.704/bit-0.0.704/node_modules/@teambit/react/dist/react.env.js
- /Users/neekh/.bvm/versions/0.0.704/bit-0.0.704/node_modules/@teambit/react/dist/react.main.runtime.js
- /Users/neekh/.bvm/versions/0.0.704/bit-0.0.704/node_modules/@teambit/bit/dist/load-bit.js
- /Users/neekh/.bvm/versions/0.0.704/bit-0.0.704/node_modules/@teambit/bit/dist/app.js
- /Users/neekh/.bvm/versions/0.0.704/bit-0.0.704/node_modules/@teambit/bit/bin/bit`

**Comment by jurredejongh** [comment]
I have the same problem. It has something to do with the Workbox SWA Webpack plugin (https://developer.chrome.com/docs/workbox/modules/workbox-webpack-plugin/).

**Comment by justiny** [comment]
This is an issue with our team as well.

**Comment by lallmaier** [comment]
Have the same issue, but version 0.0.698 does not work as , and neither do versions 0.0.726 and 0.0.740. Please fix this.

**Comment by enesozturk** [comment]
Same here with `bit-0.0.762`

**Comment by FelixBravoBurgos** [comment]
Is there any solution already? We are experience the same issue at my company and we are seriously thinking about leaving the bit set up due to this...

**Comment by ashinga48** [comment]
This issue still exists, downgrading to 0.0.655 worked for me

**Comment by manipindi** [comment]
how to downgrade bit version

**Comment by ashinga48** [comment]
> how to downgrade bit version

`bvm use 0.0.655`

**Comment by itaymendel** [comment]
we have completely redone the react support.
please use the updated env here - https://bit.cloud/teambit/react/react-env
