### ISSUE TITLE
Tailwind CSS doesn't work on bit.cloud when it works on localhost

### ISSUE THREAD

**Issue by luckypal** [teambit/bit#5877]
### Bitdev with TailwindCSS
I have a trouble in working with tailwind on bitdev.
I found this project from github `https://github.com/teambit/react-tailwind-env`  and it works properly on here
https://bit.dev/shohamgilad/tailwind-test/

It also runs properly on my localhost as the above screenshot.

![image](https://user-images.githubusercontent.com/35539437/170737504-7037bd78-9a8e-438b-8c44-afcf2fcec2ec.png)

But after I upload to bit cloud, tailwind css doesn't work as this.

![image](https://user-images.githubusercontent.com/35539437/170737539-09153887-eee1-4b90-81e4-ad0fe2e47311.png)

https://bit.cloud/nextres/nextresv3

I updated bit v0.0.744 and tag & exported again. but it's the same.

Thanks.

**Comment by anthonyvanbeek** [comment]
Please help, any approach I try works locally but not on bit.cloud. Here's my attempt : https://bit.cloud/pixelfusion/design-system

**Comment by GiladShoham** [comment]
This has been fixed a few days ago, please see the message here 
https://bit-dev-community.slack.com/archives/CCBF6L9KJ/p1657735995308109
Copy it to here for you:

For anyone who’s had issues using Tailwind in the past few months, we have now resolved all issues and have exported new versions of our reference components so you can make the required fixes and restore your tailwind-enabled bit components to their former (or future) glory.
Please see the latest tailwind components, e.g. the updated [tailwind sample env](https://bit.cloud/learn-bit-react/ui-library-wrappers/tailwind/environments/env-with-tailwind) - and make sure to fully read the documentation for the env component so that you include the required configurations to make things run smoothly.

**Comment by GiladShoham** [comment]
i'm closing this issue, if it still relevant after following the instructions, please re-open

**Comment by Zonalds** [comment]
Yeah, using Nextjs, Tailwind and Bit.dev is hard to configure and if you manage to, you'd run into multiple problem.

Maybe you there should be more support for these stack.

**Comment by coliphant-cultos** [comment]
I just exported a set of components and tailwind is not working

**Comment by itaymendel** [comment]
please see examples here - https://bit.dev/docs/design/styling#tailwind-css
