### ISSUE TITLE
Create a Discord?

### ISSUE THREAD

**Issue by oneezy** [teambit/bit#5985]
I would be nice if you guys created a Discord server.

**Comment by evelant** [comment]
Agreed, I saw there is a slack but at this point I don't even have slack installed anymore and have not used it for over a year. Discord has filled the role of slack and is much easier for people to join and interact with than slack. @davidfirst @GiladShoham seem to be the primary maintainers here, what do you guys think?

**Comment by GiladShoham** [comment]
We do use discord internally. But moving the entire community between platforms is not easy and I don't see it happen soon

**Comment by oneezy** [comment]
@GiladShoham i wouldn't suggest moving the entire community over but adding an entirely new community. I'm in the same boat as @evelant and don't use Slack any longer. Discord is way more convenient. You guys could probably gain a lot of new users

**Comment by evelant** [comment]
Another good reason to have a Discord @GiladShoham -- slack isn't really designed for communities, it's designed for internal teams, there's a big banner `On the free version of Slack, you can only access messages and files sent in the past 90 days.`.

That means all and any useful information and answers that get posted in slack are gone forever after just 90 days. IIRC Discord never deletes messages from channels, they remain searchable and useful forever. Discord is much more accessible and has much better community management features than slack, there would probably be more people joining and contributing to bit on Discord. Not much would be lost in switching since slack has already deleted all community content older than 90 days anyway.

Just my opinion, I think the community would grow and be much more vibrant on Discord and it's trivial for people on slack to switch, they almost certainly already have Discord accounts, just a click or two away.

**Comment by GiladShoham** [comment]
> On the free version of Slack, you can only access messages and files sent in the past 90 days.

That's indeed a real issue we already face.

I'll discuss it with the team.
anyway, if we decide to go with it, it will take some time.
As required inform all users in slack, replace all links on our website, and more.
(and it's not our priority right now).

**Comment by evelant** [comment]
@itaymendel did you guys create a Discord? Or is this closed because you've decided not to do that?
