### ISSUE TITLE
Remove component specific version

### ISSUE THREAD

**Issue by danyflorez** [teambit/bit#5999]
### Description
Allow removing a component specific version

### Describe the solution you'd like
While developing a component sometimes we push the changes to the scope (bit export) so we can import and test the changes on other projects, these versions are useless (e.g: 0.0.0-test.1), so we clean them up after finishing working with the component. We'd to have a way of cleaning those test versions using `bit remove component_name --ver 1.1.0 -r`

**Comment by itaymendel** [comment]
hi, bit does not support this capability and likely will not. there is a discussion about deprecating versions, but this is also up in the air.

what you can do, instead of export for test in another project is use `bit link --target` feature, which works like `npm link` and allows you to create symlinks to components from your workpsace to any other node project. this way you can test changes.

another option is to `bit import` a component to the consuming repo, and make your changes locally in that repo.
