### ISSUE TITLE
Compositions that uses a ThemProvider aren't renderd in bit.cloud

### ISSUE THREAD

**Issue by DCosti** [teambit/bit#6064]
### Describe the bug
The compositions that are using ThemeProvider aren't working on cloud. Everything works fine on local server, the ThemeProvider receives the correct theme, but on the cloud it seems that ThemeProvider doesn't have the correct theme and uses a default theme from MUI which doesn't contains some of the properties that my theme contains.

### Steps to Reproduce
1. Go to https://bit.cloud/totalsoft_oss/rocket-ui/components/surfaces/card/~compositions

### Expected Behavior
To render all the compositions as it is on local server

### Screenshots, exceptions and logs
![image](https://user-images.githubusercontent.com/41594981/177166253-5920b7cd-218a-4fb6-938c-79d750d2f812.png)

### Specifications
* Bit version: 0.0.780
* Workspace harmony
* Node version: 16.14.2
* npm / yarn version: 8.5.0
* Platform: Windows 10

_for harmony workspace_

* relevant env: custom env https://bit.cloud/totalsoft_oss/rocket-ui/envs/my-env
* relevant aspects: I set the ThemeProvider as a context for all compositions and set my custom env for all the components where I need to use ThemeProvider

**Comment by KutnerUri** [comment]
looking into this..

**Comment by KutnerUri** [comment]
found it - two issues:
1) you are using an internal files of your peer dependency. It's not fully supported, and fails when it depends on the index.
use `styled` from `@mui/material` directly, like so:
```ts
import { Card as BaseCard, CardContent as MuiCardContent, styled } from '@mui/material'
// import { styled } from '@mui/material/styles'
```

2) you are using absolute links in the composition. This is certain to be confusing, because you can get an older version of your component or run into some circularity. It also hides the production errors you are getting in your local workspace.
Just use relative links inside a component:
```ts
import Card from './Card'
// import Card from '@totalsoft_oss/rocket-ui.components.surfaces.card'
```

@GiladShoham FYI - we should block self-absolute links inside a component, and peer nested files don't work 😕 

et viola:
![Screen Shot 2022-07-04 at 20 54 03](https://user-images.githubusercontent.com/5400361/177201503-ee270582-a121-4385-a855-b50895fd58e3.png)

**Comment by GiladShoham** [comment]
@davidfirst @zkochan 
Agree with Uri about blocking module path reference from component to itself.

**Comment by DCosti** [comment]
@KutnerUri  everything is fine now. Thanks for your help. 
I have one question: What if in a composition for my Card component I am using a different component. Should I import it from bit cloud? 
Thanks again  :)

**Comment by KutnerUri** [comment]
yes, only use absolute links between components, but, apparently, never between files of the same component.

Glad it is now working :)
