### ISSUE TITLE
How to add remote scope

### ISSUE THREAD

**Issue by MikulasLebowski** [teambit/bit#6095]
After having to reset/reinstall bit and workspace multiple times because of various issues with bit, I now need to export some components to an existing scope to update them.

The components are staged, but when doing 'bit export', bit says:
_please specify <remote> to export them, or set a "defaultScope" in your workspace config_

How can I do that? The documentation is close to non-existent and I couldn't find any examples of this anywhere. Tried:
_bit export myscope/name_, - says scope doesn't exist
_bit remote myscope/name_

* says "no configured remotes found in scope"

**Comment by irvingviveros** [comment]
I think you need to create a remote scope first.

1. Login into your bit account https://bit.cloud/ and then create a new scope
2. You will see a new default scope
![image](https://user-images.githubusercontent.com/43256092/178799853-0191db65-f841-46b0-b49b-6bab5431d423.png)
3. Go to your existing project and open the _workspace.jsonc_ file 
4. Replace _"defaultScope":_ with your default scope and then build, tag, and export the components

Otherwise, please see this section of the documentation: https://bit.dev/docs/quick-start#create-a-remote-scope

**Comment by jonatankBIT** [comment]
In your workspace.jsonc file update the `defaultScope` value

have in mind that the format needs to be:
`myCompanyOrOrganization.myScope`

For example: 
![image](https://user-images.githubusercontent.com/97826324/181181609-39425e82-13fe-4e56-9dd4-45fd42821d97.png)

Also make sure that the scope was already created in bit.cloud.

Regarding the docs, I it is specified in the quick start, somewhat around the middle.
https://bit.dev/docs/quick-start
