### ISSUE TITLE
new bit install command

### ISSUE THREAD

**Issue by GiladShoham** [teambit/bit#613]
The command won't get any args.
1. Install packages from root package.json
2. will install all the package dependencies for all the components (using yarn / npm and workspaces according to the bit.json)
3. After install it will make sure all the links to imported components are correct.

**Comment by davidfirst** [comment]
A use-case where this command will be useful.
A user imports some components, change them, doesn't want to tag and export them.
Other users who work on the same project, clone the project and discover that they can't run 'bit import' because the components were changed. Their only option is to run 'bit install' to install the packages and fix the links.
