### ISSUE TITLE
Cannot render html components in mdx

### ISSUE THREAD

**Issue by boeto** [teambit/bit#6160]
### Describe the bug
Cannot render html components in mdx

### Steps to Reproduce
1. Create new workspace & html-component

```bash
  npx @teambit/bvm install

  bit new react bit-demo-debug
  cd bit-demo-debug
  bit create html my-html-component --env teambit.html/html
```

2. In workspace.json add the following as a top-level key-value pair

```json
// workspace.jsonc

{
  ...
  "teambit.compilation/bundler": {
    "dedicatedEnvDevServers": ["teambit.html/html"]
  }
}
```

3. Bit start

```bash
bit start
```

4. Check in chrome: <http://localhost:3000/>
1. Here is the [reproduced repo](https://github.com/boeto/bit-demo-debug)

### Expected Behavior
MyHtmlComponent should render in `js live`

### Screenshots, exceptions and logs
![screenshots](https://raw.githubusercontent.com/boeto/image/main/uploads/Snipaste_2022-07-19_13-30-37.png)

### Specifications
* Bit version: 0.0.794
* Workspace type: (harmony/legacy)
* Node version: v16.15.0
* npm / yarn version: npm:8.5.5
* Platform: mac

_for harmony workspace_

* relevant env
* relevant aspects

_for leagacy_

* Bit compiler (include version):
* Bit tester (include version):

**Comment by benjgil** [comment]
Hi @boeto 
When it comes to rendering html components, the steps required to render their output vary according to what that output is - and because there's no real standardisation for what an html or vanillaJs component produces, we can't ensure that the mdx js live feature will work with any html/vanillaJs component

So in order to render your component in a js live setting, you will need to ensure that there is a process - either as part of your component, or separately in the js live code - that takes the html your component outputs and attaches it to the DOM. Once you do this your component will render fine in the mdx documentation
