### ISSUE TITLE
Locally tagged components with `bit tag` are not synced on git when not exported to bit.cloud scope

### ISSUE THREAD

**Issue by Termtime** [teambit/bit#6318]
### Describe the bug
If I tag components locally, but don't export them to the bit.cloud scope, then the changes that `bit tag` creates on `.bitmap` break the repository for everyone else if pushed, because the version does not exist on bit cloud, `bit install` fails for everyone else, but me.

Also if I have a new component from another lane that just got merged to `main`, but did not get pushed, the `bit install` will fail, even on the local machine that tagged it, because it removes the marker that tells it that the component does not exist on the `main lane`

### Steps to Reproduce
1. Create a new workspace
1. Create a component
1. Tag it
1. Export it to a bit.cloud scope
1. Push your changes to a github branch (`.bitmap` gets updated by `bit tag`)
1. Make another change to the component
1. Tag it once again
1. Version on `.bitmap` will change
1. Push your changes to the github branch, but **do not** export the locally tagged version to the bit.cloud scope
1. Now clone your GitHub repo and attempt to run `bit install` on the cloned repo
1. Install will fail, as your git repo attempts to install the version that got bumped when you ran `bit tag`, but didn't push.

### Expected Behavior
There should be a way that allows bit to keep track of locally tagged changes so that multiple repositories can keep in sync, ideally, whatever change `bit tag` does, it should allow the `.bitmap` to sync enough information for other repositories to correctly address the current state of the components (tagged but not exported). 

I think right now all of that information is being stored in `.git/bit` which is an ignored directory that will and should not push to GitHub. I assume this because when I delete `.git/bit`, the lanes break and after fixing them, the repo behaves just as the cloned one.

### Specifications
* Bit version: `0.0.819`
* Workspace type: `harmony`
* Node version: `16.13.0`
* npm / yarn version: `8.1.0`
* Platform: `macOS`

_for harmony workspace_

* relevant env 
* relevant aspects

### Context
I will be tagging davidfirst as I have noted that he has contributed a lot towards lanes, so this issue might be important to note for him.

**Comment by itaymendel** [comment]
Hi,

Bit keeps tags and different objects in a dedicated storage called `local scope` (`.git/bit`).
You need to export these objects to a remote scope so they will be available for other developers.
See the notes on CI-integration, which requires you to export and commit-back to your Git repo after the run.
https://bit.dev/docs/getting-started/collaborate/setup-ci

if you don't intend to have a semantic version available, you can use `bit snap`.
or, if these are changes you don't want to export at all, you can just commit to your repo and not run snap/tag at all, just share code changes.

the `.bitmap` file itself acts more like a state-management for which version of a component is currently located in the workspace.

**Comment by davidfirst** [comment]
Some cases of out-of-sync were handled. You can see more info here: https://github.com/teambit/bit/issues/1543
The ones you mentioned are not handled. It might make sense to handle them, but it'll hurt the performance as it'll need to make server requests to make sure it's synched. 

Regarding lanes, it'll be hard to sync Git and Lanes. If you work with lanes, I'd suggest working with one Git branch. Otherwise, things can get out of control.
A new fix pushed recently, removes the current-lane tracking from .bit and it's now only in the .bitmap file.

**Comment by Termtime** [comment]
Thanks for the clarification @itaymendel and @davidfirst!

 I ended up using `bit tag --soft` which seems the correct choice intended for CI, there is one issue though, for a new component that only exists on a different lane, using `bit merge --no-snap` (I am running `--no-snap` as I am not running `bit-export`, so I don't want to generate a snap only in the local scope) causes the following JSON properties to be removed from the new component:

```
"onLanesOnly": true,
"isAvailableOnCurrentLane": false
```

which causes further issues with other bit commands, as bit assumes the component does already exist in the lane that it was merged to, which is not true because we have not run `bit export` yet.

**Comment by davidfirst** [comment]
Interesting. So if I understand correctly, the use-case is as following:
Lane-A has a component: comp-a.
Lane-B doesn't have this component. 
You're checked out to Lane-B and you're running `bit lane merge lane-a --no-snap`.
Locally, if you run `bit status`, you see a section of unmerged components, which indicate that these components need to be snapped in order to complete the merge. 
However, because you want to export on the CI, you don't want to snap/tag locally. If you don't snap+export and you push to Git, then you loose this state of "unmerged components" because this file of unmerged exists in the local-scope (.git/bit), which is not tracked by Git. You also lose the changes on the Lane object, which added this comp-a into lane-b.
On the CI, it has the lane object from the remote, which doesn't include comp-a, but it still gets the .bitmap changes, including the removal of `"isAvailableOnCurrentLane": false`. so from the CI perspective this component is now belong to "main" and is not part of the current Lane object. 

Again, working with Lanes and Git is not easy. I would suggest completing the entire merge process (merge+snap/tag+export) in a single machine. Either locally or on the remote.

**Comment by Termtime** [comment]
You are on point with your explanation!

I understand, we will do for now with manual **merge, tag, and export**, although it would be nice if we could eventually go manually version bump (can do with `bit tag --soft`) the components and push to a `version-bump` PR but hold the deployment (`bit export`) until the merge occurs using CI
