### ISSUE TITLE
Add support for pnpm patch

### ISSUE THREAD

**Issue by bingtsingw** [teambit/bit#6613]
### Description
Add support for pnpm patch: https://pnpm.io/cli/patch

**Comment by itaymendel** [comment]
hi,

why is this needed? in bit you can just `bit import` any component dependency you may have and keep local modifications which will be compiled and tested as part of your workspace build (even `bit fork`, if you want to publish these changes).

i think it's much safer than applying side-effects on installed node-modules.

**Comment by bingtsingw** [comment]
Hi, I'm new to bit, is this pattern work for third party packages?
What I want to patch is a package lives on `npm`

**Comment by evelant** [comment]
I've got a project using pnpm workspaces and bit looks interesting so I'm also curious about this. I make pretty heavy use to pnpm's patchedDependencies feature to fix bugs in 3rd party react-native packages.

**Comment by itaymendel** [comment]
This needs some background

The bit-workspace does not have a feature to keep modifications for deps and modify them. Bit's goal is to ensure components are portable between workspaces. in this case, if you have a specific configuration or action that only happens in your workspace, this will need to get ported over to the capsule and potentially to other workspaces (via `bit import`).
Given that, and that not all components may actually depend on all patched-components, even setting all patches to all components may be flaky (for example - what happens if a component holds a patch for a dependency it does not use or have in its own `node_modules`).

What you can try to do in the meanwhile is adding this as part of your env. Your env will need to apply the patches as part of the build-pipeline and also in the workspace (perhaps by registering a command to do so, i'm not sure what would be the best way to do it on the workspace itself. there are several options...).

This way you have your env controlling the specific versions and patches to apply. envs are portable and is designed to control "standards" for dependencies. so it sets the definition of what's going on in capsules's node_modules dir, and also "forces" specific dependency management controls over the components which are configured with it. moreover, an env is also a "bit aspect", which means it can add features and behaviors directly to workspaces.

At this point i am not sure when bit will offer such native apis for this. but if we do - this will likely be a part of the "bit-env" capabilities, similar to what i outlined above.
