### ISSUE TITLE
Support for Node v19

### ISSUE THREAD

**Issue by nickythorne** [teambit/bit#6652]
### Describe the bug
We are in the process of upgrading our tooling versions, including node to as latest version as possible. In our case this would be Node 19. We have updated our base docker images to derive from `node:18-alpine`. However, we are getting errors installing the latest version of bit cli within these images, relating to unsupported node version.

### Steps to Reproduce
1. Build Docker image from `node:19-alpine3.15` and install bit 

```
FROM node:18-alpine
RUN @teambit/bvm@latest && bvm install 
```

1. Build image `docker build .`
1. Get following error

> Node version 18.12.1 is not supported, please use Node.js >=14.19.3 <17.0.0.`

### Expected Behavior
Are there plans to support Node 18 (given that Node 19 is the current version)?

### Specifications
* Bit version: 
* Workspace type: (harmony/legacy) harmony
* Node version: 18.12.1
* Platform: alpine linux

**Comment by itaymendel** [comment]
node18 is a requirement for bvm itself, and unrelated to bit.
please move the ticket to the teambit/bvm repository.

closing this topic, as this is not relevant for bit.

**Comment by sharky98** [comment]
I have the same exact error message after trying for 2 hours to install bit through bvm and corporate proxy. It is not related to bvm in any way from what I see, because the error come from those lines.

Do you plan to support Node18, which is the current LTS?

https://github.com/teambit/bit/blob/92b248a9899d3a7100b123ea4e14187e81e0a467/src/bootstrap.ts#L14

https://github.com/teambit/bit/blob/92b248a9899d3a7100b123ea4e14187e81e0a467/src/bootstrap.ts#L48-L61
