### ISSUE TITLE
Env configs wiped out after successful publish

### ISSUE THREAD

**Issue by elliottye** [teambit/bit#6659]
### Description

Component env configs in .bitmap are gone after `bit tag` successfully publishes the component in the workspace. This makes it inconvenient for other collaborators on the same project as they'd have to `bit env set` again because they would have nowhere to retrieve the env configuration data which was stored in .bitmap as the only source of truth.

Is this behavior by design or is kind of a known issue?

### Specifications

- Bit version: 0.0.859
- Node version: 16.15
- npm / yarn version: 8.5.5
- Platform: MacOS Catalina

**Comment by benjgil** [comment]
Hi @elliottye 
The configs aren't wiped out, they become part of the component's internal config once a version is produced with them.
You can fetch all these configurations by running `bit show <component_name>`, or you can specifically get all component's envs by running `bit env`.

The .bitmap file is not a source of truth for configs, it's a file that bit uses in order to fetch the current state of a component in the workspace. All configs become part of a component's version, so bitmap doesn't need to store them. It's only when a config is new and not yet versioned that bitmap contains the config in order to complete the current, modified pre-version state of a component.

I hope that clears this up.

**Comment by elliottye** [comment]
Thanks @benjgil! It's much clearer.

I did try `bit env` and `bit show` after persistent tagging and they all work perfectly. But still this begs the question: where exactly are these permanent config of components stored? Presumably not `.bit` folder as they can be deleted and rebuilt, and `package.json` doesn't have a dedicated section for Bit configs. Then I see no place in source control saves information of configs. Would be even more helpful if you could shed some light on it.

Thanks.

**Comment by benjgil** [comment]
The configs are stored in the component's data, on your local scope - i.e. yep in the .bit (or .git/bit) folder.
It can be rebuilt because when the local is deleted bit fetches this from the remote scope - so you need to be careful deleting the `.bit` folder if you have a local tag which hasn't yet been exported as then any new config data will indeed be deleted.

**Comment by elliottye** [comment]
OK. That's based on the assumption that a remote scope is already there. But what if there's no remote scope, only local scopes and yet we'd like to collaborate on it. It feels a bit problematic if a remote scope is not available since a new dev would always need the component metadata and rebuild his .bit folder which is not available as they're in someone else's machine. And worse still, every dev could have different versions of .bit folder and they have no way to sync with each other without a remote scope. What should we do under such a setting? Is a remote scope mandatory to share component metadata among team members?

**Comment by benjgil** [comment]
I'm not sure what you mean by no remote scope, only local. It's possible there's a gap here in the understanding of local and remote scopes.

The local scope in bit is analogous to git's local file store of your repo. That's where commits go when you do them locally, and git stores that information. If the commit is 'local' and you dont push it, then none of your colleagues will either know about that commit, or the code changes, the diff, that it holds. 

The same is in your case with a bit component - if you locally tag the component, bit stores that tagged component, with all its diffs (inc config diffs) locally. When you export (i.e. push) then that becomes something your colleagues can see.

I'm not really sure what sort of flow you want to achieve by locally tagging but specifically not exporting and expecting other contributors to somehow have a view of your local tag (i.e. commit)?

**Comment by elliottye** [comment]
OK, I got it. Remote scopes are necessary for collaboration. Previously we didn't have one and we held the assumption that everything is recorded by the .bitmap file and anything in .gitignore can be rebuilt from .bitmap, which is incorrect. We're setting up a remote scope now. Thanks for the clarification! Appreciate it!
