### ISSUE TITLE
How to manage Bundle Size of packages?

### ISSUE THREAD

**Issue by tjuandev** [teambit/bit#6708]
### Description

My project BIT Components is based on Chakra UI, when i install the package, it's bundle size takes the entire Chakra UI size even if i'm using a single component. Can someone suggest strategies to manage this problem?

**Comment by benjgil** [comment]
Hi @tjuandev 
This is a bit of a confusion, caused on our end, due to a) how bit currently targets component outputs (which will change very soon), and b) what the component bundle is actually telling you.

a) Bit's target strategy
Bit currently targets components to commonjs module output. This means that at the moment your components don't take advantage of the benefits of esm modules, mainly tree-shaking, so at the moment any application using your bit components will be bringing in the whole of libraries such as chakra-ui (though in general applications using your full design system will likely anyway be using large parts of chakra-ui on the whole, so this may not matter much).

b) what the bundle size in your component tells you
The bundle size provided by bit will tell you the size of the component + dependencies which are bundled when rendering your component. However the vast majority of this will be the dependencies, and this bundle size doesn't tell you which of the dependencies are almost certainly going to be used by multiple components (potentially both bit components and other packages used in your application), and so it doesnt actually tell you how much the component will in practice actually add to your application when you install it. 
In general, the larger dependencies are often used across the application (e.g. in this case chakra-ui, being used by all the design system components), and therefore it will actually only be added once to your app bundle, even though each design system component 'includes' chakra-ui as part of the bundle size.

A tool you can use, either with bit or in your application is webpack-bundle-analyzer, which is very simple to set up and provides a visualisation of all packages' size in your bundle. 
To use it with bit we've created a webpack transformer that you can add to your custom env to produce this visualisation when running `bit start`.
https://bit.cloud/bit-foundations/env-configs/webpack/bundle-analyzer

I hope that helps
Benjamin

**Comment by tjuandev** [comment]
Ok, thank you for the answer!
