### ISSUE TITLE
hide `.bitmap` file in `.bit` folder

### ISSUE THREAD

**Issue by amir-arad** [teambit/bit#697]
## Expected Behavior
keep all non-user-facing model in one place - the `.bit` folder

## Actual Behavior
there's a `.bitmap` file in the root of my project, I now need to add it to `.gitignore` separately

## Steps to Reproduce the Problem
(maybe it's not the shortest path, but this is what I did)
  1. init bit
  1. add  some component
  1. fail to export

## Specifications

  - Version: 0.12.4
  - Platform: osx

**Comment by itaymendel** [comment]
Hi,
You are right that in a sense it's not a user-facing model, but so does `yarn.lock` file, but it is still required to be tracked as part of the project, to ensure all local workspaces of the same project are in-sync.

Bit requires this file to be synced across all clones of the project (ie - ensure that each tracked component is placed in the right location, or keep track on the files added to components), so it can't be within the `.bit` directory. There are a bit more explanations about it [in the docs](https://docs.bitsrc.io/docs/initializing-bit.html).

In order to ensure there is no confusion, and to make it easier to understand that this file needs to be tracked by the SCM, I think we will revert the behavior of adding it (`.bitmap` file) only when tracking files, to be generated when the `bit init` command is being issued.

Does this make more sense?

**Comment by GiladShoham** [comment]
As part of https://github.com/teambit/bit/pull/700 we are now creating the .bitmap file during bit init
