### ISSUE TITLE
change component env from  teambit.react/react   to   learnbit.react/envs/react-esm. tag error

### ISSUE THREAD

**Issue by lcz1543812491** [teambit/bit#7229]
### Description

when i change a component. from  teambit.react/react   to   learnbit.react/envs/react-esm. 

then tag error 

![WechatIMG24](https://user-images.githubusercontent.com/31276544/229012692-38466809-d537-4d2d-a7ac-0883ddfd3d4c.jpeg)

### Specifications

- Bit version: 0.1.11
- Node version: v16.19.1
- npm / yarn version:  yarn: 1.22.19  npm: 8.19.3
- Platform:
- Bit compiler (include version):
- Bit tester (include version):

**Comment by benjgil** [comment]
Hi @lcz1543812491 
Please use our new esm-by-default envs (since they were released a few weeks ago we're not maintaining these older versions of esm envs)
`bit env set teambit.react/react-env` or create your own custom env based on them with `bit create react-env <your-env-name> --aspect teambit.react/react-env`
