### ISSUE TITLE
bit init fails because of node version 20

### ISSUE THREAD

**Issue by bazo** [teambit/bit#7368]
### Describe the bug

Node version 20.0.0 is not supported, please use Node.js >=14.19.3 <17.0.0.
If you must use legacy versions of Node.js, please use our binary installation methods. https://docs.bit.dev/docs/installation

### Steps to Reproduce

1. have a fairly recent version of node installed
2. run npx @teambit/bvm install
3. try to run bit int

### Expected Behavior

that it would work

### Screenshots, exceptions and logs

If applicable, add screenshots, exceptions, and logs to help explain your problem.

### Specifications

- Bit version:
- Workspace type: (harmony/legacy)
- Node version:
- npm / yarn version:
- Platform:

*for harmony workspace*
- relevant env
- relevant aspects

*for leagacy*
- Bit compiler (include version):
- Bit tester (include version):

**Comment by GiladShoham** [comment]
It seems that you have installed the legacy version of bit.
As bvm also bring node to be used by bit.
Can you please run bit -v?
And maybe paste the output of bvm config?

**Comment by squidCatx** [comment]
I have same problem
here is my  environment
{
  BVM_DIR: '/Users/something/.bvm',
  DEFAULT_LINK: 'bit',
  'links.bit': '0.1.62'
}

**Comment by sonukumar7258** [comment]
The issue you're encountering is due to the fact that the software does not support Node.js version `20.0.0`. They specifically mention they support versions `>=14.19.3` but `<17.0.0`.

Here's how you can resolve this issue:

1. **Install a Supported Version of Node.js**:
   
   You need to downgrade or install a supported version of Node.js. Using a tool like `nvm` (Node Version Manager) can be very helpful in this case:

   - Install `nvm` (if not already installed):

     ```bash
     curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.38.0/install.sh | bash
     # or
     wget -qO- https://raw.githubusercontent.com/nvm-sh/nvm/v0.38.0/install.sh | bash
     ```

   - After installation, you can install and use a supported version of Node.js:

     ```bash
     nvm install 16.13.0  # This is the latest version before 17.0.0 as of my last update.
     nvm use 16.13.0
     ```

2. **Retry Installing and Using Bit**:
   
   Now, with the supported version of Node active, retry the installation and execution:

   ```bash
   npx @teambit/bvm install
   bit init
   ```

**Comment by GiladShoham** [comment]
Node 20.0.0 is supported for a few months with the latest stable bit versions. 
Since v0.2.0 if I remember correctly.
