### ISSUE TITLE
[Angular] App is not loading component with "nested" component

### ISSUE THREAD

**Issue by ggros-septeo** [teambit/bit#7453]
### A clear and concise description of the issue

When consuming a component that itself consume another component in a ng app, the component is not laded properly.

### Steps to Reproduce

1. Create a new workspace `bit new angular my-workspace --aspect teambit.angular/angular`
2. Create an app `bit create ng-app my-app`
3. Create a component `bit create ng-module my-cmp`
4. Create another component `bit create ng-module my-button`
5. Run `bit use my-org.my-scope/my-app`
6. Run `bit use my-org.my-scope/my-cmp`
7. Run `bit use my-org.my-scope/my-button`
8. Edit _**my-scope/my-cmp/my-cmp.module.ts**_ with the following
```
import { NgModule } from '@angular/core';
import { MyCmpComponent } from './my-cmp.component';
import { MyButtonModule } from '@my-org/my-scope.my-button';

@NgModule({
  declarations: [
    MyCmpComponent
  ],
  imports: [
    MyButtonModule
  ],
  exports: [
    MyCmpComponent
  ]
})
export class MyCmpModule {}
```
9. Edit _**my-scope/my-cmp/my-cmp.component.ts**_ with the following
```
import { Component } from '@angular/core';

@Component({
  selector: 'my-cmp',
  template: `
    <div>
    my-cmp works!
    <my-button></my-button>
    </div>
`,
  styleUrls: ['./my-cmp.component.scss']
})
export class MyCmpComponent {
  constructor() {}
}
```
10. Edit _**my-scope/my-app/src/app/app.module.ts**_ with the following
```
import { NgModule } from '@angular/core';
import { BrowserModule } from '@angular/platform-browser';

import { AppComponent } from './app.component';
import { MyCmpModule } from '@my-org/my-scope.my-cmp';

@NgModule({
  declarations: [
    AppComponent
  ],
  imports: [
    BrowserModule,
    MyCmpModule
  ],
  providers: [],
  bootstrap: [AppComponent]
})
export class AppModule { }

```
11. Edit _**my-scope/my-app/src/app/app.component.html**_ with the following
```
<div>
  <p>MyApp</p>
  <my-cmp></my-cmp>
</div>
```
12. Run `bit install`
13. Run `bit run my-app`
14. Open a browser on http://localhost:3000

Only the element `<p>MyApp</p>` is displayed the `<cmp>` component is not properly loaded

### Expected Behavior

The component `<cmp>` should be loaded properly and displayed on the page

### Screenshots, exceptions and logs

![image](https://github.com/teambit/bit/assets/134306187/26e89177-8cf4-4b87-9d04-3e401c90cc29)

### Specifications

- Bit version: v0.1.48
- Workspace type: harmony
- Node version: v16.16.0
- npm / yarn version: v8.19.4
- Platform: win32
- OS: Windows 11

*for harmony workspace*
- relevant env : [default Angular env (teambit.angular/angular)](https://bit.cloud/teambit/angular/angular?_gl=1*hxh8k2*_ga*NjcxMDYwNDA4LjE2ODM3MDkwMTQ.*_ga_C0T2GH2G99*MTY4NTA4MTEwOS4yNS4xLjE2ODUwODMwNzYuNTYuMC4w)
- relevant aspects 

### Additional context

Same result if using the env [teambit.angular/versions/angular-v15](https://bit.cloud/teambit/angular/versions/angular-v15?_gl=1*a60img*_ga*NjcxMDYwNDA4LjE2ODM3MDkwMTQ.*_ga_C0T2GH2G99*MTY4NTA4MTEwOS4yNS4xLjE2ODUwODMwNzYuNTYuMC4w) 

When running `bit start`, the composition for the component `my-cmp` is working fine

![image](https://github.com/teambit/bit/assets/134306187/858edc97-6c9e-4903-aec0-df315441fe8d)

**Comment by ocombe** [comment]
Hello, sorry it took so long but I just fixed the angular issue, not sure about the react one though (@GiladShoham ?).
Fyi @ggros-septeo you shouldn't run `bit use` on regular bit components, only on apps or envs

**Comment by GiladShoham** [comment]
Reopen to check the react component issue

**Comment by Thomas-Boi** [comment]
Thanks for looking into this bug. Here's some picture of what I'm referring to:

**The Bug**: my `console.log` in the compiled `index.js`:
![image](https://github.com/teambit/bit/assets/43018778/567c8c86-7109-4cf8-8b42-738b8d55c0fc)

![image](https://github.com/teambit/bit/assets/43018778/4c2df39b-be4f-4b1b-ac6d-41be64199f8d)

Error is caused by accessing the `react_tooltip_1`'s Tooltip:

![image](https://github.com/teambit/bit/assets/43018778/39451d53-59ca-4221-a219-8a9d55f09165)

What original code (pre-compilation) looks like:
![image](https://github.com/teambit/bit/assets/43018778/497a4852-8e27-4d2a-887d-1cd3c30fbaac)
![image](https://github.com/teambit/bit/assets/43018778/f2b1cdc4-2fbc-4710-9ffc-8451ecfa35ee)

Extra Details on the environment:
- Project created by `create-react-app` but now use `react-app-rewired@2.2.1`
- Webpack version 5.75.0
- React version 16.14.0

What the console.log() should look like in a working project:
![image](https://github.com/teambit/bit/assets/43018778/fefe7b9b-99b6-44ad-ac6b-e0572e7744c1)

Extra details on this working project:
- React app created by `vite@4.1.4`
- React version 18.2.0

**Comment by Thomas-Boi** [comment]
@GiladShoham  This issue has been resolved. I noticed that after the update, new envs look different from the envs that I have. After creating a new env and assigning the component to it, the problem has been solved. Seems like something in the old env prevented the code from bundling properly with `react-tooltip`. 

Thank you for your time and work 👍
