### ISSUE TITLE
Allow imports of all components in one scope

### ISSUE THREAD

**Issue by msloan-updox** [teambit/bit#784]
## Expected Behavior
I would like to be able to import an entire scope in a new project vs. having to import each component within that scope separately. This would be a powerful feature when you have something like a complete component library in one scope and you want to import all components available on a project. If I break out my project into simplified components, I could have 20+ bit import statements at the top of each file.

Ideally, this would be a better workflow:

```yarn add @bit/username.scopename```

```javascript
import { Button, Header, Footer } from '@bit/username.scopename.components';
```

## Actual Behavior

Currently, you need to do this:

```
yarn add @bit/username.scopename.components.button
yarn add @bit/username.scopename.components.header
yarn add @bit/username.scopename.components.footer
...
```

```javascript
import Button from '@bit/username.scopename.components.button';
import Header from '@bit/username.scopename.components.header';
import Footer from '@bit/username.scopename.components.footer';
...
```

**Comment by GiladShoham** [comment]
Thanks for this suggestion @msloan-updox .
This is a really interesting feature.
I will add it to our backlog and keep this issue updated.

**Comment by OutThisLife** [comment]
Surprised this isn't default.

**Comment by kowsheek** [comment]
Is anyone working on this @GiladShoham? Happy to make a PR in a few weeks. I'm using bit for a project with a bunch of components per namespace, would be handy.

**Comment by msloan-updox** [comment]
@kowsheek That would be awesome if you could get this figured out! I'll help with testing it out for you, but I probably can't provide much else as far as developing the feature goes.

**Comment by GiladShoham** [comment]
This is really cool feature and no one is currently working it since it's much more complicated than it looks in both product and technical aspect, so we need to think about it much more.
I can't write a full detailed explanation right now, but I'll do it in few days.
Anyway we are very excited to see our users involved by request new features, reporting bugs and of course PRs.

Just short explanation about this feature:
1. It require changes both in the client and on the remote servers.
2. It will also require changes in our registry (to enable packing a full scope)
3. There is a SemVer issue, how to set the scope version when it contains different versions for different components.
4. What is the behavior when you install scope and then install / import one component of the scope in different version.
5. In the previous case, how to make sure the actual files being used are the correct files (the one from the scope or those from the component)

Any feedback is more than welcome.
Thanks.

**Comment by kowsheek** [comment]
Those are very good thoughts @GiladShoham, please do share your detailed thoughts when you can. I'll look at how other platforms do namespace importing in the mean time.

My initial thoughts are that we could extend the [import-components](https://github.com/teambit/bit/blob/master/src/consumer/component/import-components.js) module to handle a namespace option. It would trigger the import of components in that namespace at the latest versions available.

If a component is imported separately (afterwards), that one would have its version changed. So, I can see why that would require the changes to the registry.

I'm getting more familiar with bit, hope the thought process is on-track.

Looking forward to your response.

Thanks!

**Comment by GiladShoham** [comment]
@kowsheek Sorry for the long delay.
Here are some more thoughts regarding this issue.

It's first important to distinguish between 2 different methods of consuming components which very relevant for this feature:
1. [installing-components-using-package-managers](https://docs.bitsrc.io/docs/installing-components-using-package-managers.html)
2. [importing-components](https://docs.bitsrc.io/docs/importing-components.html)

The main (but not only) conceptual difference between them, is that when you using import (`bit import`) it source the component into your project and let you modify build and test it, then export it back to a remote scope. while using npm / yarn is mostly when you only want to use it without changing it.
Bit's make it very easy to switch between the methods in different cases, here is an example of a common flow:
1. install component (using npm) 
2. found a bug 
3. import the component (bit will make sure to [bind](https://docs.bitsrc.io/docs/importing-components.html#bindings) and [link](https://docs.bitsrc.io/docs/importing-components.html#linking-components) the necessary files, so this process doesn't require any code changes in the dependents. 
4. fix the bug 
5. export the component (optionally using --eject flag will make it back an npm module)

Now, when talking about bit import, it should be pretty easy (product wise) to import a full scope. The main concern is how to know which versions of the component to import. (as a basic implementation bring the last of all is one option, or let the user specify a version, and search for this exact version for each component)
This will require implementing a new private command to run on the remote scope to bring all component of a scope.
It should behave in a similar way of running import one by one, and maybe generate an index file to expose them all in a better way.
After it, we should implement a way of "ejecting" a component from the scope import during import it explicitly (as you described)
This import flow doesn't involve anything in the registry (since the registry is only about npm / yarn commands)

A more complicated case is when you try to install the scope using npm. 
We need to create a package follow the common.js spec.
This package should contain all the components and a version.
Generating this version number is complicated since it might contain components in different versions.
Generating this package required changes in our registry in 2 places:
1. Identify those kinds of requests to install a scope
2. Create the actual tar file of the package. (done today by a bit extension you can found here: [pack extension](https://bitsrc.io/bit/extensions/npm/pack)  

This requires introducing a new concept of "scope version" we should think about.
Another problem is what happens when you install a scope using npm, then import one component using bit. Today when you import a component after installing it using npm, we link the npm module of the component to the imported folder.
This process might also be a problem after installing a scope. (I didn't dig into this problem so it might be only a simple problem (product wise), requiring only technical work)

**Comment by CyrusZei** [comment]
any updates on this?

**Comment by GiladShoham** [comment]
@CyrusZei @msloan-updox @OutThisLife @kowsheek 
I wrote a simple script (outside from bit) that simulate importing all the components in a scope.
feel free to use it and customize it for your needs.
https://gist.github.com/GiladShoham/ae0a8aaafc627b811c3ba1d2acd99e0c

**Comment by yairEO** [comment]
Docs are confusing me.

https://docs.bit.dev/docs/installing-components.html

I do not want to add each and every component manually, since I have dozens.

    yarn add <owner>.<collection>.<component-ID>

Why can't I just run:

    yarn add <owner>.<collection>

And add the all collection automatically?

I need a way to sync a whole collection of components with an App the consumes them, without manually managing it directly in `package.json`

**Comment by itaymendel** [comment]
update - since version 14.1.2 Bit support importing of a whole collection using `bit import <collection_name>/*`.
It does not yet support destructured import statements.

**Comment by TwiggyBuffalo** [comment]
Cant seem to import an entire collection. Both return no matches found: <collection_name>/*

bit import <collection_name>/*
bit import <owner>.<collection_name>/*

bit cli version: 14.1.3

Webpack alias imports would make this a dream come true. 🥇

**Comment by GiladShoham** [comment]
@TwiggyBuffalo 
Does your collection is public? 
can you add me as a viewer so I can test it with your own collection? (gilad@bit.dev)

**Comment by TwiggyBuffalo** [comment]
@GiladShoham I deleted the collection of 150+ components yesterday as its actually part of closed source project. I will play around with it a `bit` more tomorrow for a personal project. Will add you as a viewer if I can't import the entire collection. Thanks

**Comment by itaymendel** [comment]
The ‘import <owner>.<collection>/*’ is very slow. It is possible that you thought it hanged, and killed it.
There’s an open task to fix the performance issue.

**Comment by CyrusZei** [comment]
I have done my own component library with sketchbook and npm private package and I can easy do something like

`import {Text, Card, Button} from 'my-awesome-components`

so can anybody explain why you would all of a sudden change it to

`bit import <owner>.<collection_name>/*`

that is another syntax that you need to remember.

**Comment by itaymendel** [comment]
hi @CyrusZei it's an off-topic question... In your case `my-awesome-components` is a single project that contains all components (e-la `loadsh`). However, with Bit you package each component (like importing only `lodash.merge` and `lodash.uniqby`, instead of `lodash`). So it's a different development experience.

As for the `import {text, card, button} from 'my-components'`... This is another feature we plan on tacking. The thing with the destructuring syntax for components is that each component is its own package, so what needs to be done is dynamically create a local package that imports and exports all components. The problem here is that some components may have the same 'named export'.

On a side note - the syntax you mentioned (`bit import <owner>.<collection>`) is only relevant to how you import the component's source code to your project. You can use `npm i` if you prefer.

You can read through the docs [here](https://docs.bit.dev/docs/what-is-bit.html) and get a clear understanding of the additional values of having each component in its own package.

**Comment by itaymendel** [comment]
Closing this issue. It is not a feature we'll support. You can do that by creating a component that exports any number of other components and have your consumers use that.

**Comment by benmandr** [comment]
> Closing this issue. It is not a feature we'll support. You can do that by creating a component that exports any number of other components and have your consumers use that.

Will tree-shaking work if export will be done this way ?

**Comment by piotrkulpinski** [comment]
> Cant seem to import an entire collection. Both return no matches found: `<collection_name>/*`
> 
> ```
> bit import <collection_name>/*
> bit import <owner>.<collection_name>/*
> ```
> 
> bit cli version: 14.1.3
> 
> Webpack alias imports would make this a dream come true. 🥇

You should wrap the expression in quotes, otherwise it's treated like a regex, hence `no matches found` error.

```
bit import "<collection_name>/*"
bit import "<owner>.<collection_name>/*"
```
