### ISSUE TITLE
Using files from projects in tracked components

### ISSUE THREAD

**Issue by ldipasquale** [teambit/bit#797]
## Expected Behavior
I'm looking to track some components that uses config files from the project (that aren't tracked by Bit). Is it possible?

## Actual Behavior
`bit status` give me a `missing packages dependencies`

**Comment by GiladShoham** [comment]
This issue has been discussed on [gitter](https://gitter.im/bit-src/Bit)  

Here is TL;DR according to @ranm8 suggestions:

Two things you can do regarding global config files when working with Bit.
1. Decouple the component from its config by injecting the config as an argument (instead of requiring the constants file).
2. Track the config file as a separate component that multiple other components can use (You can also use the “internal” namespace to control its scope visibility - means it won’t be listed on your scope)
