### ISSUE TITLE
Circular dependencies issues

### ISSUE THREAD

**Issue by giuliano-abinbev** [teambit/bit#8129]
### Description

I've created an env called `react-component` that extends react-env which performs additional things during build. I also have a component called `theme` which is essentially a theme provider for all other components, and uses the custom env i created (aka `react-component`).

From my custom `react-component` env, I consume theme in `/envs/react-component/preview/mounter.tsx` to wrap all compositions with the theme provider, for example:

```jsx
export function MyReactProvider({ children }: { children: React.ReactNode }) {
  return <Theme>{children}</Theme>;
}
```

Getting the following issue, which makes sense, because it would be problematic for the theme composition (preview):

```
bit insights "circular"

Found 1 cycle.

Cyclic dependency
-----------------
- beertech.hexa-react-web/theme@0.0.13
- beertech.hexa-react-web/envs/react-component@0.0.10
```

Question is, how can I consume the theme provider from the `react-component` custom env and use it for all previews?

### Specifications

- Bit version: 1.2.7
- Node version: v18.18.2
- npm / yarn version: 9.8.1 / 1.22.19
- Platform: MacOS (M1)
- Bit compiler (include version):
- Bit tester (include version):

**Comment by benjgil** [comment]
Yep this is a known circular dependency 'route', and there are two ways around it:
1) a. create a base-custom-env, which contains all your customisations from the custom env except the `preview` customisations. You assign this base-custom-env to your theme-provider. 
  b. as bit envs are just js classes, you create another custom env (e.g. custom-react-env) which just extends the base-custom-env (you'll need to copy over the contents of the env.jsonc file as for now that's not inheritable) and then adds the `preview` customisations, including the theme-provider.
  c. assign `custom-react-env` as the env to the rest of your react components
  
  2. The second way would be to just use our default teambit.react/react-env env for your theme-provider instead of your custom env. This is much simpler, but means you cant apply any tooling customisations to your theme-provider. Often that's not an issue, so this second approach can generally be used unless you have some specific tooling config customisations, e.g. typescript, that you want to be used for the theme-provider itself as well.


Hope that helps
Benjamin
