### ISSUE TITLE
Unable to preview Vuetify components

### ISSUE THREAD

**Issue by subham25997** [teambit/bit#9056]
- I created a Vue app and setup vuetify into it.

![image](https://github.com/user-attachments/assets/46e70c3c-12dd-455a-9bbe-2dfbc288acbc)

- Then, I used **v-button** into it.

![image](https://github.com/user-attachments/assets/29a622be-6fb2-452d-a8af-35a3da650f74)

- I am not seeing the effect of Vuetify in preview pane.
![image](https://github.com/user-attachments/assets/c1127867-a86f-4bf8-99d8-bcabd4186658)

Please help me how I can set up vuetify so that it'll be previewed correctly.

- Bit version: 1.7.3
- Node version: 16.17.0
- npm / yarn version: 8.15.0

**Comment by itaymendel** [comment]
to run your application, please do `bit app list`, capture the application name, and then do `bit run app-name`.

when building applications it is best to have a standalone server for it rather than use the preview/composition feature as it is very possible your preview does not load that part of the app. i recommend following what is in the `compositions` file to see what will be improted and rendered.

**Comment by itaymendel** [comment]
please do not spam with the same issue many times
