### ISSUE TITLE
In self hoisted or remote scope, when I export the components, I get the message "Processing preview" in the Overview and Preview screen

### ISSUE THREAD

**Issue by subham25997** [teambit/bit#9097]
- I created a docker image for remote scope using following Dockerfile:

![image](https://github.com/user-attachments/assets/aa4bc036-bb2b-4080-9f96-c477ae9c1d55)

- Hoisted the scope using following command:
**docker run -it -p 5001:3000 app2-scope:latest**

- Created and exported Vue components to it and got this,

![image](https://github.com/user-attachments/assets/aed78ef7-974e-41f5-8e2a-2491ab57a6dd)

**Overview of components:**

![image](https://github.com/user-attachments/assets/245631a2-d5f3-4f50-9c9e-f4e03010589f)

**No error in the console**

![image](https://github.com/user-attachments/assets/7f1e6eae-16f6-44c7-9071-cdf536f557fd)

### Specifications
(Same versions in docker image also)
- Bit version: 1.8.20
- Node version: 20.16.0
- npm version: 10.8.1

**Comment by subham25997** [comment]
Can someone look into this please?

**Comment by itaymendel** [comment]
hi, please use the search functionality of tickets, as this question was asked and answered in the past, for example - 
https://github.com/teambit/bit/issues/7958

or you can add `--build` when you run `bit tag`. this is due to the fact you don't currently have any CI in place, so you need to run the actual build pipeline.

**Comment by subham25997** [comment]
When I run **bit tag --build -m ""** I am getting this error:
![image](https://github.com/user-attachments/assets/09a4ee7a-f856-4120-9f62-71d9663162ab)
