### ISSUE TITLE
New command: isolate

### ISSUE THREAD

**Issue by kcampion** [teambit/bit#915]
## Expected Behavior

Actually, when you add and export a new component to "bit", you must have installed the dependencies into the package.json in the root of your project. If you import this component into another project, it will have its own package.json with all his dependencies. It's awesome because this imported component is isolated from the rest of the project.
But the problem is that the initial component is not managed as the imported one; not isolated, and it's hard to share with that.

You can use `$ bit tag --all` and `$ bit export bit.movie-app --eject` then import the isolated one, but before you must have installed the dependencies in the main package.json otherwise you will have an error: `missing packages dependencies (use your package manager to make sure all package dependencies are installed)`.

My suggestion is to create a new command like `$ bit isolate` which detects the dependencies from the main package.json or the javascript file itself, and saves them into a new package.json. The structure will be the same as to import a component. After that, it should be easy to tag then export the component.

## Specifications

  - Bit version: 0.12.11
  - Node version: 9.2.1
  - Platform: osx

**Comment by davidfirst** [comment]
That would be a nice feature, and I can see where this can be helpful.
The issue I see implementing this, is where this new package.json will be saved? 
As the author of the component, you're free to add files from different directories of the project, so there is no one "root-directory" of the component.

**Comment by kcampion** [comment]
The new package.json will be saved into the folder of the component you want to isolate. Maybe a command like `$ bit isolate ./my-super-component` will be easier to use.

**Comment by itaymendel** [comment]
So technically we have added an *experimental* `bit isolate` command.
It does not do exactly what is described in this particular feature request. What it does is creates an isolated dev environment in a temporary file system. By doing so Bit generates the isolated `package.json` for the component that this feature request is about.
Additionally, it provides extensions with this file via a programmatic API.

This means that it is very possible to implement such a feature as an extension.
I don't see how implementing this feature as a core Bit functionality benefits Bit.
What I think is that it is a very good candidate for an extension.
So I'm closing this issue, as it should be resolved by an extension to Bit, rather than a core feature.

<for the reader>
If you have gotten this far, want this feature, but no extension is found - I urge you to develop and release one. For any assistance in writing extensions, please consult the documentation site and reach our to the community over gitter.
